### ISSUE TITLE
Client crash on SMP when pressing "Helmet Hack" key

### ISSUE THREAD

**Issue by linuxdemon1** [MineMaarten/PneumaticCraft#181]
When pressing the "Helmet Hack" key while not wearing the Pneumatic Helmet the client crashes with: 
http://pastebin.com/naPtKqib
Only occurs when playing on a server, SSP unaffected.

**Comment by MineMaarten** [comment]
As the bug isn't reproduceable for me, and no one on twitter seems to get it, https://twitter.com/MineMaarten/status/585181545352290306 , I'm closing this.

Be sure to respond or open a new issue if it does happen with the latest version:)
