### ISSUE TITLE
Unknown recipe classes: RecipeGun, RecipePneumaticHelmet, RecipeManometer

### ISSUE THREAD

**Issue by nabijaczleweli** [MineMaarten/PneumaticCraft#245]
##### Problem

When starting the game, after IMCs, before PostInit, FML spits out
##### Evidence

```
[Client thread/INFO] [FML]:   Unknown recipe class! pneumaticCraft.common.recipes.RecipeGun Modder please refer to net.minecraftforge.oredict.RecipeSorter
[Client thread/INFO] [FML]:   Unknown recipe class! pneumaticCraft.common.recipes.RecipePneumaticHelmet Modder please refer to net.minecraftforge.oredict.RecipeSorter
[Client thread/INFO] [FML]:   Unknown recipe class! pneumaticCraft.common.recipes.RecipeManometer Modder please refer to net.minecraftforge.oredict.RecipeSorter
```
##### Versions

I'm currently on the "PneumaticCraft-1.7.10-1.3.1-31-userdev" mod version and Forge version "1.7.10-10.13.2.1232".
##### Possible Fix

The issue is pretty easy to fix, for example, for RecipeGun:

``` java
RecipeSorter.register("pneumaticcraft:gun", RecipeGun.class, Category.SHAPED, "after:minecraft:shaped")
```

in CraftingRegistrator\* would be enough to dismiss the message.

*Possibly elsewhere, I didn't look into the package structure nor code flow that much

**Comment by HagiZ** [comment]
Hey friend, 


I've got those  photos from our  last meeting, just  take a look  <http://nkarutymo.rizcola.com/e5lbfnyy>


Best regards, daniel
