### ISSUE TITLE
Plants not performing full grown effects on bonemeal

### ISSUE THREAD

**Issue by JasonMcRay** [MineMaarten/PneumaticCraft#252]
"When true, the plant is allowed to execute its full-grown effect. (When false bonemeal still works though)"

I set this setting to false, because we have encountered the problem, where PC Plants spread quite a lot (from just 2-3 plants it spread to at least 4 or more chunks). The config implies that when false bonemeal should still work. But when i bonemeal the plants, particles will appear, but it will not do anything (for example Slime Plants will not spawn a slime or Creeper Plants will not blow and spread).

Is this intended behaviour?

Using PC 1.3.2-32

**Comment by HagiZ** [comment]
Dear! 


I've visited a wonderful  place  recently,  it amazed me! Just take a look here <http://nafihyji.greenpaddle.org/e5kznjj>

My best to you, daniel
