### ISSUE TITLE
Air tanks

### ISSUE THREAD

**Issue by 113820** [MineMaarten/PneumaticCraft#268]
We need an efficient way of storing air for later use instead of responding to demands and wasting energy, my solution to this is air tanks.

Air tanks are tanks which can be filled with air and can endure 200 bars of pressure before heading into the danger zone. Air tanks can be anywhere from 3x3x3 to 9x9x9(direwolf20 will be happy that he can make a 9x9 tank). But to make this work, the output would be limited by 15 bars.

**Comment by Blue64** [comment]
if you restrict the airflow to one-directional, theoretically, you could create anything with 200 bars of pressure. I know, it's a dead thread, but this gives me an Idea! (standby for reference link lol)
