### ISSUE TITLE
Add Crafting puzzle piece

### ISSUE THREAD

**Issue by MineMaarten** [MineMaarten/PneumaticCraft#304]
Allows drones to craft.

**Comment by mainframecn** [comment]
Any information about this puzzle piece?

**Comment by GirafiStudios** [comment]
Install In-game Wiki Mod, and you can get the information by pressing I, while hovering over the item.

**Comment by MineMaarten** [comment]
Tnx Girafi

**Comment by PaulEngineer** [comment]
Can i ask something? how  to use crafting piece?

**Comment by PaulEngineer** [comment]
And how to connect this piece with the program?

**Comment by MineMaarten** [comment]
Girafi said it ^

**Comment by PaulEngineer** [comment]
Yes, now i understood!!!! I saw the In-Game Wiki But it do not say how to connect this piece. Girafi said that but it can not understand that this piece have a few informations about this piece. I know how to use it, but i don't know how to connect it into the programm. Please, seriously, make tutorial on how to use, and how to connect every piece. I need only examples. Nothing else. And then i will understood. The In-Game Wiki mod have few, very few informations for this piece. See it yourself.

**Comment by PaulEngineer** [comment]
For example I'm trying to craft a GunAmmo with instant_damage potion effect. I say it for example. I know that the Crafting piece need Item filter piece. I put 2 Item filter pieces. One with GunAmmo and second for instant damage potion. The Crafting piece had on top on it the GunAmmo with this potion effect. And then? How to make the drone take this two items and craft this GunAmmo? How to make this programm? How to make the drone craft this GunAmmo, and when it do that, then put it into the chest? That I want to say.

**Comment by PaulEngineer** [comment]
Yes, now i understood!!!! I saw the In-Game Wiki But it do not say how to
connect this piece. Girafi said that but it can not understand that this
piece have a few informations about this piece. I know how to use it, but i
don't know how to connect it into the programm. Please, seriously, make
tutorial on how to use, and how to connect every piece. I need only
examples. Nothing else. And then i will understood. The In-Game Wiki mod
have few, very few informations for this piece. See it yourself.

For example I'm trying to craft a GunAmmo with instant_damage potion
effect. I say it for example. I know that the Crafting piece need Item
filter piece. I put 2 Item filter pieces. One with GunAmmo and second for
instant damage potion. The Crafting piece had on top on it the GunAmmo with
this potion effect. And then? How to make the drone take this two items and
craft this GunAmmo? How to make this programm? How to make the drone craft
this GunAmmo, and when it do that, then put it into the chest? That I want
to say.
Στις 26 Απρ 2016 9:34 μ.μ., ο χρήστης "MineMaarten" <
notifications@github.com> έγραψε:
