### ISSUE TITLE
turning drones off?? 

### ISSUE THREAD

**Issue by lieven121** [MineMaarten/PneumaticCraft#316]
Normally drones are always on and that uses a "lot" of pressure so I was thinking a way to stop the rotors and just wait for the next flowcart block/ cc line and make this use very little pressure 
Like it ??

**Comment by MineMaarten** [comment]
Added with this commit: https://github.com/MineMaarten/PneumaticCraft/commit/3381353ea6a9312aa0a202251b1af353d9e10e56
