### ISSUE TITLE
Safety Valve/Pressure Gauge do not scale to Advanced Pressure Tubes

### ISSUE THREAD

**Issue by taigenraine** [MineMaarten/PneumaticCraft#333]
There currently is no 'advanced' version of these anymore, and when placed on advanced pipes they still have the same behavior as when on normal pipes, making it impossible to regulate a system above 7.5 bar.  They should either automatically scale to 20 when placed on advanced pipe (and even better if they adopt the advanced texture too) or have some sort of high pressure toggle.

**Comment by bookerthegeek** [comment]
Wow it took me a lot longer to find this information then I think it should have...

Anyway to include this info in the igw?
