### ISSUE TITLE
[Suggestion] Optional Vanilla-Style planting mechanic for seeds

### ISSUE THREAD

**Issue by Macrophage001** [MineMaarten/PneumaticCraft#339]
I was wondering if you could add this to your mod? The planting mechanic as it stands, while interesting, is somewhat tedious and unnecessarily difficult in some scenarios (Magnet-Mode items and the like).

**Comment by MineMaarten** [comment]
This  was added in 1.5.4. For some reason this issue lost my eye, and wasn't closed back then.
