### ISSUE TITLE
issue: never ending searching

### ISSUE THREAD

**Issue by icomeinpieces** [MineMaarten/PneumaticCraft#342]
the drones will freeze up and cause server lag when they target an entity that is encased in a small cave ex. dungeon. i believe this is due to the fact they are not able to find a path to said entity, perhaps the drones should detect when a path is not found in a suitable amount of time and give up on that entity

**Comment by MineMaarten** [comment]
"could you set it so that if they fail to teleport they disregard that entitiy?"

The whole idea of drones teleporting was added as a last resort to prevent lag. I just overlooked this instance, the attacking AI didn't know the drone was preparing to teleport, and therefore retried, causing lag. fixed in next version.

**Comment by mrgreaper** [comment]
we had another instance of the teleporting behavour, i was using drones to build a large reactor, wen one got to 0.8 psi it did the same teleport behavour, in this case im assuming it was trying to get to the charging pads that were chunk loaded but a fair distance away (maybe 5 or 6 chunks away), i did not think to check if it effected the tps and just assumed it did and destroyed the drone 

Not a very helpful bug report i know and i am sorry for that, i only mention it incase it shows a fringe behavoir that may cause more issues.

**Comment by MineMaarten** [comment]
It's just the Entity Attack piece that has this bug. Other AI's shouldn't have it :)

**Comment by mrgreaper** [comment]
ah cool :), despite that bug the drones have been a godsend :)

**Comment by MineMaarten** [comment]
The label "issue will close upon release" is inaccurate in this case. There isn't a new build available just yet. I completely understand you misunderstood this and this therefore doesn't annoy me :P (about the twitter conversation). I'll post something here when I do release the build with this fix.

**Comment by mrgreaper** [comment]
cool, much appreciated.

**Comment by MineMaarten** [comment]
New build on curse!

**Comment by mrgreaper** [comment]
your an absolute star, thank you!
