### ISSUE TITLE
seeds coming from bone mealing dirt

### ISSUE THREAD

**Issue by Frontrider** [MineMaarten/PneumaticCraft#343]
I don't know if its intended, but this mechanism breaks my tree farm every now and then, by simply not making it possibly for the 2x2 jungle tree to grow.

**Comment by benedict42** [comment]
I got squid seeds from bonemealing netherrack in the middle of water. Bonemealing netherrack always gets you the pneumaticcraft seeds when you place it in the right spot. Is that a bug?
