### ISSUE TITLE
Pressure Chamber Interface name filter only accepts english item names

### ISSUE THREAD

**Issue by ghost** [MineMaarten/PneumaticCraft#345]
I am using the German localization from PneumaticCraft and want to filter my pressure chamber extraction by name. But when using the name filter of the Pressure Chamber Interface it only filters items with the (original) English names.
For example I want my Pressure Chamber Interface to extract Compressed Iron:
German translation: "Komprimierter Eisenbarren"
When I try to filter by starting with a "k" from "komprimiert" it does not work. When using "c" instead from the english word "compressed" it works fine.

It would be nice if you could change this to accept localized item names too.

**Comment by MineMaarten** [comment]
I'm afraid I can't implement this.

Take for example 2 clients on 1 server, one with english, and one with german language. How would the interface be able to decide which filter ot use. it can't, best it can do is grab the server localization, which is english.
