### ISSUE TITLE
bug - wierd one MAJORLY WIERD flux compressor brought fps down by fireing fireworks

### ISSUE THREAD

**Issue by mrgreaper** [MineMaarten/PneumaticCraft#347]
sorry to be filing so many bugs and im not sure this is a fault of pneumatic craft but after 2 hours of going through mods i cant seem to find the source of the conflict, one of our flux compressors started madly firing fireworks, brought my fps down drasticly, it was definatly coming from the flux compressor as you could see them shoot out, wierdest bug i have ever seen.

I thought it may be a conflicting particle effect but as i say in the last two hours i have tested out the map with out certain other mods and it happens even with the most basic of mod sets. had to turn all pnumatic craft stuff off at the moment

**Comment by MineMaarten** [comment]
This indeed was a new years easter egg and should be gone now.
