### ISSUE TITLE
Add self-hack of security station for testing and validation of security puzzle

### ISSUE THREAD

**Issue by War-Wizard** [MineMaarten/PneumaticCraft#348]
Being able to hack an owned station would allow to test the complexity of its puzzle. Addiotionally, I believe it would be a good mechanic to make a security station fully functional after it is successfully hacked at least once, preventing players from creating secured zones that are almost impossible to hack.

**Comment by MineMaarten** [comment]
I like the self-hack to test.

I don't feel a need of adding a 'workaround' for impossible lay-outs, as there aren't any impossible to hack lay-outs ;).

**Comment by danielmills** [comment]
![How is it impossible to make an impossible hack?](https://cloud.githubusercontent.com/assets/10619135/9288662/e9546f54-431f-11e5-8ee9-c5e4470a26c2.png)

**Comment by MineMaarten** [comment]
Pneumatic helmet + security upgrade + block tracker

**Comment by danielmills** [comment]
But if blocks are covering it, how? 

Also would towny, the bukkit plugin conflict with this?

**Comment by MineMaarten** [comment]
You can hack through those with the helmet. Not sure about the plugin
