### ISSUE TITLE
1.6.4 Drones lose picked up items upon relogging

### ISSUE THREAD

**Issue by kerajel** [MineMaarten/PneumaticCraft#350]
Hello

So I am playing on a Monster FTB pack + some additional mods including Pneumaticcraft. I set up a tree farm and I notice that when I do relog all my drones lose items they carry. Thus I lost a bedrock axe already! Can give any logs if necessary.

The problem does not seem to be common which has me worried...

**Comment by GirafiStudios** [comment]
PneumaticCraft have dropped support for 1.6.4 a loong time ago!
The bug is most likely fixed in the newest 1.7.10 build of PneumaticCraft
