### ISSUE TITLE
Add a way to hack security stations without having to reach them.

### ISSUE THREAD

**Issue by 55555bookworm** [MineMaarten/PneumaticCraft#351]
My concern is that someone could just surround their security station in layers of obsidian, there for making it unbackable. It'd be nice if you would add another way to hack a security station, such as a "wireless hacking device" which would allow you to wirelessly hack any security stations that you are within their area.

**Comment by MineMaarten** [comment]
There is one, use a Pneumatic Helmet with Security Upgrade and Block Tracker upgrade, and you can hack security stations remotely

**Comment by dadodasyra** [comment]
That's fun because if your in a box even with the items you cannot set the upgrades on the helmet without a charging station so your stuck

**Comment by ruifung** [comment]
@dadodasyra Why are you commenting on an issue that's 9 years old on an repository that hasn't seen any updates for 7 years now?

I believe you're looking for https://github.com/TeamPneumatic/pnc-repressurized for the currently maintained version.
