### ISSUE TITLE
Breaking Plant, possible bug

### ISSUE THREAD

**Issue by ApptSolutioNZ** [MineMaarten/PneumaticCraft#358]
Running ftb 1.6.4 (latest) SSP, I broke a plant and quickly covered it in dirt surrounding areas as well, now it appears that i can't break the dirt block or place any blocks in that chunk. Its making sounds like its planting and then breaking repeatedly and I can see the seeds popping up through the dirt.
Have restarted the game as seems not to allow any updates to that chunk, had to mcedit player out of chunk, thinking I will have to delete the chunk and regenerate.

**Comment by MineMaarten** [comment]
This sounds really weird. I wish you good luck, but as it isn't reproduce-able and it's MC1.6.4, you're on your own
