### ISSUE TITLE
Load third party content

### ISSUE THREAD

**Issue by Morpheusblog** [MineMaarten/PneumaticCraft#359]
Crash log: [pastebin.com/G97SC1B4](pastebin.com/G97SC1B4) 

There is a problem with forestry.

I'm using
Pneumaticcraft: 1.5.1-49-universal
Forestry: 3.3.0.400-unstable

**Comment by MineMaarten** [comment]
I can't see the log, but I assume it was talking about not being able to register a null fluid. It's fixed by 
https://github.com/MineMaarten/PneumaticCraft/commit/ce78d07b0a2edef9818e74e0470de1a461e0d439

**Comment by Morpheusblog** [comment]
Yes, it was that. 
[pastebin.com/G97SC1B4](http://pastebin.com/G97SC1B4) 

Thanks
