### ISSUE TITLE
Aerial interface with openperipherals

### ISSUE THREAD

**Issue by jilleJr** [MineMaarten/PneumaticCraft#362]
Being able to see the content of the player's inventory with the Aerial interface via OpenPeripherals for ComputerCraft...

Idk if I should ask you or the creator of OpenPeripherals but would be nice if you could see the content of the players inventory, and check it out. Like for example would be cool if I could check if my pickaxe is out of power and if so it replaces it with a new one. Or have the terminal glasses display like what I have in my inventory. Fun stuff like that.

So would be great if you made it so we can check whats in the interface with OP or have your own custom functions, and in the case of your own functions you can spice it up with stuff like an event for when you pick up an item or maybe be able to read what's the currently selected slot.

With great computercraft integration comes great oppertunities :+1: :)

**Comment by MineMaarten** [comment]
If it can look into chests already (IInventory), it should also be able to look into the 'inventory' of the Aerial Interface..?

**Comment by jilleJr** [comment]
Yea but it can't for some unknown reason...

Check this out
I have this setup: chest to the right and aerial interface to the left.
![Setup](http://i.imgur.com/FPNvLsp.jpg)
![Chest docs](http://i.imgur.com/FPNvLsp.jpg)
![Aerial interface docs](http://i.imgur.com/FPNvLsp.jpg)

I don't know but just maybe you override the peripheral, and that's why it's not part of openperipherals. That's just my theory tho

**Comment by jilleJr** [comment]
If that's the case, that you are overriding it, maybe you can make it pneumaticMachine on top and openperipherals inventory on the other sides. But maybe that's not possible with the peripheral API...

**Comment by Vexatos** [comment]
@MineMaarten There is a particular problem with ComputerCraft: If multiple Peripheral Providers provide peripherals for the same block, ComputerCraft will only call the one which was registered first. This means, if the Aerial Interface is an IPeripheral or you add an IPeripheral for the Interface, any peripheral added by OpenP will get ignored (as OpenP peripherals are always the last being registered).

**Comment by MineMaarten** [comment]
It would be because I'm overriding it yes... I'm trying your suggestion jilleJr. Now you can access the pneumaticMachine peripheral from the top/bottom, and I'm not for the sides. Please let me know if you _can_ use the sides to get the inventory now :)
(upcoming version)

**Comment by jilleJr** [comment]
Ahh sweet @MineMaarten you're my star. Now where can I get this version? Wait 'til it's publicly released, and in that case how much time would that take?

**Comment by MineMaarten** [comment]
not sure, when I decide to release :P. I'm thinking of tomorrow, but don't keep me to it :P

**Comment by jilleJr** [comment]
Is it possible to get a small prerelease just to test it? :3 ?

**Comment by MineMaarten** [comment]
A new build is on curse (when approved). Have fun, and please report back if it fixes it :)

**Comment by MineMaarten** [comment]
As I didn't get any reports back I'm just going to assume it works fine :)

**Comment by Vexatos** [comment]
:+1:

**Comment by jilleJr** [comment]
Wow I actually forgot about this, I never tested it 'til now. It does not seem like it fixed it, I still get the pneumaticcraft methods from the peripheral not a chest-like one from openperipherals...
I am running a buggy modpack and it crashed when I hooked up my computer to a chest, and I don't have the time at the moment to check further, but I can say that your fix does not seem to have fixed it.

I will reply later when I can test further but for now I have to sleep :)

**Comment by MineMaarten** [comment]
Not sure what I can do anymore about it though. I would think OpenPeripherals could try and look if they can make it side dependent on their side?

**Comment by jilleJr** [comment]
Factorization got a temporary solution to this problem, as said on the other issue
https://github.com/OpenMods/OpenPeripheral-Integration/issues/8#issuecomment-78715224

>Just found out the perfect temporary solution: [Factorization Parasieve](http://purpleposeidon.github.io/FzDocs/parasieve.html)
>> Place the parasieve against an inventory. Any machine that attempts to access the parasieve will access that inventory through it.
>
>This block does as expected and the peripheral for it works as expected as well. Just perfect with some more prefect on top.
>I'm so happy because I can now play with my dreams and automate my own inventory. \**so cool*\*

**Comment by CaptiveCreeper** [comment]
That works perfectly for accessing the inventory but is there some way to access the "tank" of xp with computercraft?

**Comment by jilleJr** [comment]
If there isn't then there should be a function for it, on the interface. Something like 'getXPLevel()' and 'getXPAmount()'. Catching my drift?

**Comment by CaptiveCreeper** [comment]
i looked on the wiki and did not see any functions specific to the aerial interface.  Only the ones related to pressure that all machines have.  If i missed something i would be happy to be corrected.

**Comment by Vexatos** [comment]
A solution to that would be installing Computronics, it should make the functions of both mods available; of course, that's just a workaround.

**Comment by MineMaarten** [comment]
There is no method for it currently, no. But this is one I can (and will) add :).

**Comment by CaptiveCreeper** [comment]
I looked at the wiki for the mod Computronics and don't see how this would help with accessing xp could you please explain.

**Comment by Vexatos** [comment]
It does not help accessing the XP, that's on @MineMaarten's side to do. It would be a temporary solution for accessing both PneumaticCraft and Openperipheral functions from the same side, though.
