### ISSUE TITLE
Assembly controller does not recognize inserted programs

### ISSUE THREAD

**Issue by kotoroshinoto** [MineMaarten/PneumaticCraft#364]
version tested: 1.4.3-40 as part of direwolf20 pack version 1.0.3

**Comment by kotoroshinoto** [comment]
It recognized the connected machines, but the UI element still issues a warning that no program is present and there is no ability to select/set a recipe

**Comment by kotoroshinoto** [comment]
It seems the machines still run though. Weird. Maybe its just a UI problem?

**Comment by DarkStarDS9** [comment]
Yep this was an UI problem and has been fixed a few versions ago, sadly DW20 is a bit behind :-/
