### ISSUE TITLE
cc when using a to large area 

### ISSUE THREAD

**Issue by lieven121** [MineMaarten/PneumaticCraft#366]
if you use things like this 
function getPlayer()
 if D ~= nil then 
  if D.isConnectedToDrone() == true then
   D.addArea(-1*10^7,1,-1*10^7,1*10^7,200,1*10^7,"Filled")
   D.addWhitelistText(player)
   D.setAction("entityImport")
  end
 end
end
the computer says to long without yieling

**Comment by MineMaarten** [comment]
A drone isn't made for this. And I'm afraid it never will be. An area of ((110+110)*10)^7^3 =~10^27 :O
