### ISSUE TITLE
Drone duplication

### ISSUE THREAD

**Issue by lieven121** [MineMaarten/PneumaticCraft#368]
i start with one drone 
i reboot and suddely there are 3 or 4 drones 
now i have 8 drones
dont know what is causing this

**Comment by GirafiStudios** [comment]
What version of PneumaticCraft are you using?

**Comment by lieven121** [comment]
newest 
and now i have 2 drones ????  
and ist random because yesterday everything was normal but the day before that i had it to

**Comment by MineMaarten** [comment]
It's a vanilla bug afaik, I've seen it happen with vanilla creatures too. It's some saving/reloading error when an entity leaves/enters a chunk.
