### ISSUE TITLE
Suggestion: Multiblock Elevators and More.

### ISSUE THREAD

**Issue by rmrocks01** [MineMaarten/PneumaticCraft#369]
Because the elevator is one of the coolest things in this mod, I wanted to suggest cool features to it.
I think it would be a lot better if we could make multiblock frames, giving us the ability to move in the elevators a little rather than be confined to a one block space. I would also like to see the callers to have a queue like real elevators (e.g. someone on the ground floor calls the lift then sets it to go to floor 5, and after that someone on floor 13 can call the lift while someone else is on it but it will stop at any floors requested before reaching the 13th floor.), and finally the ability to have a caller outside of the elevator "room" (as made by the multiblock frames.) that can only call the elevator to that floor. Thank you for reading! sorry if its a lot to ask.

Edit: I found out you can place a button on the side of the caller, ignore the part about the outside caller.

**Comment by MineMaarten** [comment]
" think it would be a lot better if we could make multiblock frames"
That's in already, try connecting up elevator frames next to each other, and also with the Elevator Bases.

" I would also like to see the callers to have a queue like real elevators"
That will add more annoyance than it's worth, for the user that is. For example if you hit the wrong floor number, you can now recover by simply hitting another floor.

I'd like to add with the outside caller that you can also camouflage it now. So another reason to not have to add that :).
