### ISSUE TITLE
Cannot add player to security station

### ISSUE THREAD

**Issue by DavidDiack** [MineMaarten/PneumaticCraft#370]
Hi there. Sorry for posting this on GitHub, as I already reported it on Twitter, but I feel that it's easier to keep track of an issue here.

Like the title says, I am unable to add a player to my security station. When I type their name into the field, and click the [+] button, nothing happens.
Version 1.7.10-1.5.2-50.

Thank you very much.

**Comment by MineMaarten** [comment]
A, thanks, yes, this much better to manage it :). I probably had forgotten about this issue already if it wasn't posted here..

**Comment by DavidDiack** [comment]
I don't see other complaints about this issue, so could it perhaps be a conflicting mod?

**Comment by MineMaarten** [comment]
I'll get back to you when I've done some tests myself, I don't have time right now to test right now.

**Comment by lieven121** [comment]
this works fine for me (1.7.10-1.5.2-50) did you add some kind of upgrades or so and so yes try place a new one

**Comment by MineMaarten** [comment]
Same for me. I can't reproduce this.

**Comment by DavidDiack** [comment]
I decided to try it without using a resource pack and it worked. (I was using Faithful).
So maybe it doesn't work when a resource pack changes the look of a menu button.
The reboot button and every other "menu button" I've seen on a mod does work though.

Thanks :)

**Comment by MineMaarten** [comment]
That's really weird. How would the looks of a button influence that.... Oh well, if it worked..

**Comment by AEnterprise** [comment]
is it possible that the resource pack also modified where the button was?

**Comment by MineMaarten** [comment]
Possible, but highly unlikely. I'm actually suspecting that it was just a coincidence, and that the resource pack wasn't the cause.. unless it can be reproduced reliably?

**Comment by DavidDiack** [comment]
I think it is because of the resource pack. I tried putting the resource pack on and off with various components removed such as the GUI textures and buttons, but it only worked without that resource pack. I am not sure if it does this with all resource packs or just the one I was using (Faithful OptiFine).
