### ISSUE TITLE
when relog the dispenser upgrade is not visible until you open gui (charging station)

### ISSUE THREAD

**Issue by lieven121** [MineMaarten/PneumaticCraft#373]
i have seen this issue on your stream and in my sp 
and first i did think it was just a visual but my drones ingnore it 
when flying above the drones still recharge but they ingnore if they pressure is low to go to the charging station

**Comment by MineMaarten** [comment]
It should just be a minor sync issue, meaning it shouldn't affect how drones behave.

**Comment by lieven121** [comment]
weird i thought that was the reason for my drones having 0 bar when there is a charging station very close
