### ISSUE TITLE
Suggestion:Pressure Gauge for Advanced Pressure Tubes

### ISSUE THREAD

**Issue by Kn0xX** [MineMaarten/PneumaticCraft#377]
Hello!So the current Pressure Gauge don t really work on Advanced Pressure Tubes because it emits "redstone signal of which the strength = 2 x pressure(bar), so a pressure of 3.5 bar results in a redstone signal of strength 7.". So if I have greater then 8 bar in the tube it will emit a constant 15 red stone signal power and on higher tier tube it will emit almost every time.I would like to emit 15 when the tube has 20 bar s and start drop the signal power when the pressure drops.I use RedNet Controller form MFR and I set it up to turn on my MFSU and start converting EU to pressure when the pressure falls down from 8.I would like to do this with a Pneumatic Dynamo. So when the pressure falls form the dynamo or from the tube to 16 where it won`t generate the Pressure Gauge starts emit a lower signal and turn the MFSU on.

**Comment by MineMaarten** [comment]
Use an Advanced PCB. Use IGW-Mod to see how to use
