### ISSUE TITLE
Plants not growing when block directly above

### ISSUE THREAD

**Issue by DreamingRey** [MineMaarten/PneumaticCraft#379]
I'm not 100% sure if this is a bug or intended, but for me it feels like a bug and I couldn't find anything here or on google about that. I'm sorry if it actually is not a bug :)

PneumaticCraft Plants won't grow when there's a block directly above them, they will only grow if there's at least one air space above. So, they WILL grow, if for example there's dirt 4 blocks above them, but they won't if the dirt block is directly above the plant (I will include screenshots for clarification, I hope it gets fully clear that way, as my explanation might be a bit weird). It obviously doesn't matter which block is above the plant, just any block directly on top of it stops it from growing.
Bonemealing the plant is not affected and works as normal, the plant just won't grow by itself.

I discovered that issue while building a Steve's Factory Manager auto-farming setup which has Block Gates directly above the plants.

I tested this in the Direwolf20 1.7 Modpack which includes PneumaticCraft-1.7.10-1.4.3-40-universal.jar, I did not change anything in the PneumaticCraft config.

![2015-01-21_22 28 45](https://cloud.githubusercontent.com/assets/10135889/5845665/2df5e66e-a1be-11e4-98fc-95205b9dbd0f.png)
In this image you can see that the middle plant did not grow at all, while growth did appear on the plants to the left and right. I used Rain Plant Seeds for that small testing setup, but also other types of PC plants are affected the same way. I gave the plants more than enough time to grow and still the middle one with the block directly above didn't grow at all, so I'm not just impatient, the plant actually will not grow.

![2015-01-21_22 28 52](https://cloud.githubusercontent.com/assets/10135889/5845664/2df18a88-a1be-11e4-9058-e802ce229367.png)
Here you can see the auto-harvesting setup I first discovered the issue with, just in case it helps or is related.

(And sorry about all the "grow"s and "above"s in my sentences, my English is a bit weird today.)

**Comment by DarkStarDS9** [comment]
That's a light issue. Plants check the light-level of the block above / below (hanging plants). As far as I can tell, this is usually done to favor light coming straight down (as opposed to stray light). Might be a copy/paste error though. MineMaarten? If this is not intentional the line to fix it is [Line 99 in BlockPneumaticPlantBase](https://github.com/MineMaarten/PneumaticCraft/blob/b45b491c4f7a46ef5a14ed848177a28107acfb4c/src/pneumaticCraft/common/block/pneumaticPlants/BlockPneumaticPlantBase.java#L99), just remove " + (isPlantHanging() ? -1 : 1)" :)

**Comment by MineMaarten** [comment]
I _think_ there was a reason why I did it, it might be because for some reason if I checked the light at the location of the block itself I always got light level 0. But I can check it.

**Comment by MineMaarten** [comment]
ok, I think it was some leftover code, which indeed isn't necessary @DarkStarDS9 , fixed in next version.

**Comment by DreamingRey** [comment]
thank you guys! much appreciated :)
