### ISSUE TITLE
guard drone

### ISSUE THREAD

**Issue by cdfa** [MineMaarten/PneumaticCraft#382]
Can you make a programming puzzle piece that will protect a player (specified in a text piece)? Drones would be the ultimate guards because they can fly, fit in a 1x1x1 and cary lots of different weapons. It would be ideal if the drone attacks any hostile mob in a certain area centered on the player.

**Comment by MineMaarten** [comment]
That would not be a different but more a way to program him. It would be possible already by using something like ComputerCraft, but there are plans to add relative coordinates to the drone, so you could select areas relative to the player for example.

**Comment by cdfa** [comment]
Ah, well that's all I need then :). I've thought about ways to do it with computercraft, but I couldn't find anything that can get the player coordinates and has a infinite and interdimensional range.

Thanks for making a awesome mod!

**Comment by MineMaarten** [comment]
I think the Pocket Computer can get the coordinates of the player carrying it. And that one can send it to a normal Computer :)

**Comment by cdfa** [comment]
Well I know of the way with the gps program, but this requires at least 4 other computers hosting a gps server and it has only a limited range, let alone interdimensional.
