### ISSUE TITLE
Pneumatic Craft Seeds Not Growing (DW20 1.0.3)

### ISSUE THREAD

**Issue by DMIL421** [MineMaarten/PneumaticCraft#389]
Hey MineMaarten,

I'm playing DW20's 1.7.10 (version 1.0.3) and experiencing an odd issue.  I set up a Steve's Factory manager farm (similar to Direwolf's on FC2), but I am not seeing any growth whatsoever on any plants outside of the FireFlower seeds.  I've gotten about 3 stacks of them, while none of the other plants have grown at all. I can bonemeal them and have them grow, but they do not grow naturally.  I've set up Ritual of the Green Groves under them, and added the Agricarnation from Botania to see if it makes a difference.  I have not seen any changes in all other plants.

Images of the setup below:

![2015-01-27_12 30 22](https://cloud.githubusercontent.com/assets/10730366/5925484/0bf40980-a621-11e4-9c7e-c7f7d78a77ef.png)

![2015-01-27_12 30 37](https://cloud.githubusercontent.com/assets/10730366/5925487/15fc4cc6-a621-11e4-8608-e8faab70b6e8.png)

![2015-01-27_12 39 01](https://cloud.githubusercontent.com/assets/10730366/5925570/a76d9fca-a621-11e4-8bc9-aff70afe4fb1.png)

Light levels are 9 (or above).

I can confirm that they plants are not being broken and re-dropped.  Both the visuals for the plants and the WAILA tooltips show no growth on the plants over several hours.

Let me know if there is any more information I can supply to assist.

**Comment by MrKunji** [comment]
I guess there was a recent change to fix it.

**Comment by DMIL421** [comment]
I was guessing so as well, but as I couldn't find it in any of the changelogs, I posted this bug report. Did I miss something?

**Comment by DMIL421** [comment]
I did take a look at the closed bug reports... found an identical report there... MineMaarten has it listed as fixed in the next version.  Closing this bug report.

**Comment by MineMaarten** [comment]
yup :)
