### ISSUE TITLE
Duplication of Compressed Iron with Terrafirmacraft Wrought Iron

### ISSUE THREAD

**Issue by Bunsan** [MineMaarten/PneumaticCraft#390]
Testing using pneumaticcraft in a TFC environment. TFC produces a wrought iron ingot that is ore dictionaried to ingotIron and ingotWroughtIron. If placed in a pressure chamber it will produce compressed iron, however the wrought iron is not consumed and keeps producing more and more compressed iron. In my instance minecraft iron works as intended. In addition blowing up vanilla iron with a TFC powder keg behaves as expected and produces compressed iron, however wrought iron was just destroyed.

Forge10.113.2.1272

Mods present. 
Terrafirmacraft-0.79.15.538
pneumaticcraft-1.7.10-1.0.4.83
Minetweaker3-1.7.10-3.0.9
MineTweakerRecipeMaker-1.7.10-1.1.0.11
ModTweaker-1.7.10-0.6-0
CodeChickenCore-1.7.10-1.0.4.29
NotEnoughItems-1.7.10-1.0.4.83
NEIIntegration-MC1.7.10-1.0.3
TerrafirmacraftNEIplugin-1.7.10-1.3.0.11
NBTEdit_1.7.10
fastcraft-1.16
MobiusCore-1.2.3_1.7.10
Opis-1.2.3_1.7.10
Waila-1.5.8a_1.7.10
worldedit-forge-mc1.7.10-6.0-beta-01

**Comment by DarkStarDS9** [comment]
That might be something I fixed in an experimental branch, MineMaarten - using oreDict in canBeCompressed but NOT using it in clearStacksInChamber. See:

https://github.com/DarkStarDS9/PneumaticCraft/commit/1947e56d7ab969d130b7907f9568aa1f5fc6262d#diff-51840e548a2bc99068e0ab8df457c3e6R315

**Comment by MineMaarten** [comment]
I wouldn't be surprised if I did that :P. Old code is old xD

**Comment by MineMaarten** [comment]
I've fixed the iron explosion losses with this commit: https://github.com/MineMaarten/PneumaticCraft/commit/5be426e220ea1adf8aa96a6e55e820f89bea8249

I'll see if I can cherrypick your commit to fix the other one DarkStar :)
