### ISSUE TITLE
[1.5.5] Crash on load

### ISSUE THREAD

**Issue by JasonMcRay** [MineMaarten/PneumaticCraft#394]
When I try to start my modpack with updated version of PneumaticCraft (was using 1.5.3; updated to 1.5.5). My client crashes when loading.In the 1.5.3 of course it was not crashing.
Crash log: http://pastebin.com/iFvz8XqF

**Comment by xJon** [comment]
Also on my server: http://pastebin.com/WS9NJkQj

**Comment by MineMaarten** [comment]
Update to at least forge 1.7.10-10.13.2.1254. I should have made it a dependency. In next version you'll get the right feedback.

**Comment by mailleseraph** [comment]
My server crashed with this error and I was running 1277

**Comment by JasonMcRay** [comment]
Updated forge to 1263 and crash no longer occurs.
