### ISSUE TITLE
magical crops bug

### ISSUE THREAD

**Issue by lightdamned** [MineMaarten/PneumaticCraft#397]
drones won't plant any magic seed, tryed with all different setting but it won't do it, 
i used direwolf20 code for the automation but unlike ender-lily seed he won't plant it. 

by the way the "harvest part" works fine he can recognise the different meta-data, but i think a new action for drone would be nice (like plant using hoe or something like that or use an item on a block like thaumcraft golems)

**Comment by MineMaarten** [comment]
Don't use the 'place' piece in this case. Use the 'right click block' piece instead. It should fully simulate a player right click at that point, and should work. This should also work for your second suggestion.

Please report back with a confirmation that this works, so we can close this :)

**Comment by lightdamned** [comment]
won't work already tried it on 3 different kind of dirt (regular dirt, fertilized dirt (random things) fertile soil (minefactory reloaded)) 
basically the drone recognise the other seeds but not magic crops mod (and there is a problem with the drone because when it try to plant something on regular dirt he will also destroy the farmland making impossible to plant on it--> dnstech pack, i'm gonna try it on direwolf20 1.7 soon)

**Comment by lightdamned** [comment]
it doesn't work on dw20 pack

**Comment by hron84** [comment]
@lightdamned 
Did you tried from one block higher? I think if drone destroys the farmland, then it's too close to that, you have to keep one block air between you and the farmland...

If this is not apply for you, then could you please make screenshots (or a short video) to document this problem for us? Also, please provide your versions (exact modpack version and/or exact PneumaticCraft version) to help us to investigate your problem.

**Comment by MineMaarten** [comment]
the real question is, does it work when you right click the block manually, as a player? if not, then it's definately not a drone bug

**Comment by lightdamned** [comment]
With manually, do you mean me? 
Yes i can plant the seeds by hand, and the golems too, i will test with different kind of seed and if you want i will try to record the bug on video

**Comment by MineMaarten** [comment]
yes please :)

**Comment by MineMaarten** [comment]
waaaiiit.... Did you put the 'right click block' setting to right click the _top_ of the block, instead of the bottom (which is the default) ?

**Comment by lightdamned** [comment]
I tryed both in the soil (on the top) and in the plant (y+1 of the soil, bottom) as i said i used dw20 code as base, in fact it works with ender-Lily seeds or other kind of seeds

**Comment by lightdamned** [comment]
https://www.youtube.com/watch?v=GnjgzCP-wlc
check out! :D i did every tipe of change, i recorded only the main attempts

**Comment by MineMaarten** [comment]
okay, with the soil selected (Y = 3 in your case), and with the side to be the 'Top', it should definately have worked. That's how Vanilla's Wheat seeds work. I can only assume that Magical Crops has some weird logic going on... I'm afraid I can't fix it on my side though, sorry!

Thanks for the efforts of recording and uploading anyway!
