### ISSUE TITLE
Elevator redstone control bug

### ISSUE THREAD

**Issue by LZee** [MineMaarten/PneumaticCraft#399]
I think the elevator redstone control has a bug. If I stand in the elevator and start with redstone signal, the elevator goes up, but I dont. If I jump right before I start, and fall down on it when it comes up, then it works correctly. The elevator works correctly with the Elevator caller.

Elevator status: max extension: 0,0 meter  - always

PneumaticCraft-1.7.10-1.5.6-59-universal
forge-1.7.10-10.13.2.1291-universal

**Comment by MineMaarten** [comment]
Are you sure it isn't coincidental? Both methods (redstone/elevator caller) execute the same code to make the elevator go up, and the entity standing on it.
