### ISSUE TITLE
[suggestion] Automated Drone Programmer

### ISSUE THREAD

**Issue by Nevrage** [MineMaarten/PneumaticCraft#400]
hey,

I was thinking about a block into which you could write a program just like a regular programer, but instead it would apply automatically the said program and release these drones when provided a drone.

**Comment by MineMaarten** [comment]
Not sure if a dedicated block would be the way to do it. Instead I'm thinking of allowing Drones to use puzzle pieces supplied to an inventory adjacent to the Programmer, and adding a Redstone Behaviour tab in the Programmer, in which you can program a drone when a certain redstone signal is supplied. This, combined with another drone (or any other modded 'right click' simulator), should allow you to automatically program, and place drones.

**Comment by AEnterprise** [comment]
maybe something that would also be nice and is similar: a way to update the program of the drone remotely so you don't always need to pick it up?

**Comment by Nevrage** [comment]
I'm really not sure I have understood but that will allow drones to dynamically modify their own programs based on redstone signal and inventory state ?
thats not bad but what I had in mind was something like an automated drone deployer if one gets killed.
Or that block could be provided a drone by any other mod when something emits a redstone signal in the world and emits it.

**Comment by MineMaarten** [comment]
Using the feature I'm planning to add, you can automatically program a Drone. You can then use this to create a set-up which can detect if a Drone has died (by checking if a Drone entity is within an area), program a Drone, and deploy it using some fake player.

**Comment by AEnterprise** [comment]
cool, that would programming and fixing drones so much easier

**Comment by Nevrage** [comment]
Sounds great, thank you.
Though, is there a way to identify which drone has died ?

**Comment by MineMaarten** [comment]
Not really. You'll have to be creative, and like make every different drone cause a different 'heartbeat signal'. You could for example make the drone emit a redstone signal at a certain location. Or make it connect via CC and monitor via CC if the drone is connected (= alive).

Anyway, I've implemented both your feature, and @AEnterprise suggestion, this will close when released :)

**Comment by AEnterprise** [comment]
thanks alot @MineMaarten it will make testing and messing around with new programs so much easier
