### ISSUE TITLE
etching acid recipe requires 2 gunpowder

### ISSUE THREAD

**Issue by Frontrider** [MineMaarten/PneumaticCraft#403]
We tried to craft it, but the recipe is wrong. We needed 2 gunpowder instead of one.

**Comment by MineMaarten** [comment]
Where does it say it only requires one?

**Comment by Frontrider** [comment]
NEI. Every other recipe is fine.

**Comment by MineMaarten** [comment]
well, I checked it and it's fine. And it should, as NEI looks up the recipe right from the actual recipes.
