### ISSUE TITLE
[Request] Provide CC API for checking pressure

### ISSUE THREAD

**Issue by hron84** [MineMaarten/PneumaticCraft#404]
Please provide a CC API for being able to check pressure at least in compressors/chambers. It would be good to prevent exploding things.

**Comment by MineMaarten** [comment]
have you tried it yet? it's in already. Every tube/compressor/machine is a peripheral, which has a 'getPressure()' method.

**Comment by hron84** [comment]
@MineMaarten yes, and I cannot get a peripheral from the machines. E.g. I put down a computer right next to a compressor, but it cannot identified as a peripheral (peripheral.wrap returned with nil). Could you help me which ComputerCraft is known to work with your machines?
