### ISSUE TITLE
Liquid Hoppers Duping Liquids on GregTech

### ISSUE THREAD

**Issue by Android25** [MineMaarten/PneumaticCraft#405]
I noticed while testing a machine setup that if the Liquid hopper is connected to a GregTech fluid pipe, which is in turn connected to any tank-like inventory (including more fluid pipes), the liquid starts to slowly duplicate. The duplication is faster with more speed upgrades. It seems to be due to the GregTech pipe sloshing, when liquid is pushed back into the output of the liquid hopper. Using a shutter on the GregTech pipe to stop output in that direction stops the duping.

My setup for testing this was simply a liquid hopper inputting to the top of any GregTech fluid pipe, which then outputs on any side (except the top obviously) to a tank. One bucket of anything into the liquid hopper will eventually fill the tank, regardless of size.

Edit: I assume it could be fixed by simply not allowing the liquid hopper to accept liquids being pushed into the output side.

**Comment by MineMaarten** [comment]
I've carefully looked at my code, and it looks very similar to how BC wooden fluid pipes work. As it really shouldn't matter at which side the Liquid Hopper gets it's fluids I can only assume it's on GregTech's side....
