### ISSUE TITLE
Crash occurs sometimes when using elevators

### ISSUE THREAD

**Issue by Puremin0rez** [MineMaarten/PneumaticCraft#410]
Had it occur twice when people were messing around with elevators.

http://pastebin.com/t5HHKRYR

Crash occurs on the server.

**Comment by MineMaarten** [comment]
PneumaticCraft version?

**Comment by Puremin0rez** [comment]
Version 1.6.0, just grabbed it last night :)

**Comment by MineMaarten** [comment]
hmpf.. This one is hard to track down. I'm pretty certain it's a hidden StackOverFlowException (blocks keeping themself infinitely block updating). Could you take a screenshot of where it happens exactly? To see if there are any suspicious blocks, and/or I've got a testing set-up to try it myself?

**Comment by Puremin0rez** [comment]
It's pretty hard to replicate, I've only had it happen once since posting the crash report and I have no idea what triggers it but I think it has to do with setting insane speeds on it and spamming the control block...

From what players have told me, the issue happened once while placing a second caller next to an existing caller. The other time, the issue happened from setting very fast speed on the elevator and spamming the caller block. Interesting enough, one of the two caller blocks disappeared entirely and then as soon as the one next to it was clicked, the crash occurred.

If I can find a good way to replicate this i'll letcha know.
