### ISSUE TITLE
Config item to disable Heat mechanic on energy converters (Request)

### ISSUE THREAD

**Issue by pyure** [MineMaarten/PneumaticCraft#414]
We were hoping to use PC as the sole energy bridge in our pack, but the new Heat mechanic makes this impossible: everyone would be running at 0% efficiency 100% of the time when converting their RF to PC because we can't figure out how to cool down the machines fast enough to keep up.  Surrounding the machines with Ice only keeps up with a few seconds of operation, when our players are typically converting energy for hours at a time.

We'd prefer to use PC for conversion because it requires larger infrastructure and investment than a standard/dedicated/boring energy bridge mod.  The configuration options are also excellently flexible to allow us to tweak the ratios as necessary.

Request: Would it be possible to add a config option to disable this or make it stop at X% efficiency instead of 0%? (In honesty we would likely set it to 99%.  Loss due to heat serves no purpose to us even in our hardcore packs.)

**Comment by pyure** [comment]
edit: I see there are some new blocks: heat sinks, heat conductors, vortex tubes.  I can't find any information on these but they may be solutions to my problem.

**Comment by MineMaarten** [comment]
Install IGW-Mod and you'll get all the info you need.

**Comment by pyure** [comment]
Understood, thanks.

**Comment by pyure** [comment]
Installed IGW-Mod, its fanstatic, although I do wish I could find the material online as well.

Just a balance comment: there doesn't appear to be a way to run the energy conversion machines with 10 speed upgrades without them overheating drastically.

Ideally, if I have a massive structure of cooling infrastructure, sacrificing an entire building's worth of space, I should be able to run a single conversion machine at full speed with 100% efficiency.  As it is, the 10-speed-upgrade-allowance for these machines may be irrelevant since they cannot be used.
