### ISSUE TITLE
Mod cant run on server KeyBindingPressedEvent

### ISSUE THREAD

**Issue by Kenshij** [MineMaarten/PneumaticCraft#418]
[10:29:58] [Server thread/ERROR] [FML]: Caught exception from PneumaticCraft
java.lang.NoClassDefFoundError: modwarriors/notenoughkeys/api/KeyBindingPressedEvent

Caused by: java.lang.RuntimeException: Attempted to load class modwarriors/notenoughkeys/api/KeyBindingPressedEvent for invalid side SERVER

I think you whant to register a KeyPressed on the Server, some function are nor marked as clientside only.

**Comment by MineMaarten** [comment]
Please post the full crashlog

**Comment by Kenshij** [comment]
http://pastebin.com/tUE6R99x

**Comment by MineMaarten** [comment]
Hmm.. the main question here is why you would want to add a keybinding mod to your server??

**Comment by Kenshij** [comment]
Good question, after i kicked the keybinding mod out its working.
Sorry for the issue, unhappily its hard to track what mod is client/server only.
