### ISSUE TITLE
Etching Acid Bucket recipe

### ISSUE THREAD

**Issue by iTpyn** [MineMaarten/PneumaticCraft#419]
Starting from 1.5.5-58 NEI shows incorrect recipe for etching acid bucket (it shows only 1 gunpowder needed instead of 2). Tested all latest versions from here 
http://minecraft.curseforge.com/mc-mods/224125-pneumaticcraft/files

1.5.4-56 is the last version not affected by this issue

**Comment by MineMaarten** [comment]
Ahhhh, you're right. Something went wrong when adding OreDict support for the Pressure Chamber in 1.5.5! Many thanks for tracking down the exact version where it went wrong, it really helped!

Related to #403, sorry for closing the issue @Frontrider!

I think I've fixed it. This will close when I release :).
