### ISSUE TITLE
[Suggestion] Drone Programming: relative coordinates for an area 

### ISSUE THREAD

**Issue by notchriss** [MineMaarten/PneumaticCraft#421]
Hi, is it possible to make it in one way or another?

I.e. if a drone could "remember", or be linked to, a certain block, and then it would calculate coordinates for all the areas in it's programming puzzle as offsets from that block. Lets say I have a harvesting drone who puts items in the chest, so that if I move a linked block, and then move i.e. chest so that it stays in the same place in relation to linked block, drone won't need reprogramming, as far as the drone is concerned the chest hasn't moved at all. Drone just has to notice center block has moved and recalculate all the coordinates for his areas.

It's just one of the ways to implement it, I'd be happy with anything as long as I can create a custom frame of reference for a drone, and after I move drone along with chests, Drone Interfaces and so on, I won't need to reprogram it anew to find those Drone Interfaces, Chests, etc. Or maybe there's already a way to do it? (Minecraft 1.7.10, PC 1.6.1)

**Comment by MineMaarten** [comment]
As a matter of fact, I've very recently released a version of PneumaticCraft which has relative coordinates (version 1.6.3). http://minecraft.curseforge.com/mc-mods/224125-pneumaticcraft/files/2228870

This for the most part does what you're suggesting. Let me know what you think, and if you think more is required to make your idea work out

**Comment by notchriss** [comment]
Thanks for the reply, I've read patch notes and watch the video. I think this definitely very interesting and useful, and a big part of what I suggested. I also like that drones can now be programmed automatically, using inventory chests next to Programmer for puzzle parts, definitely very useful. I will try and update asap.

Although I am not sure if I got one thing right, the initial values of variables, they are still hardcoded at the time of puzzle programming (with GPS), right? Or is it possible to just initialize them as i.e. offsets from the current drone's coordinates the moment drone is placed in the world?

What I am trying to achieve is to build a combat drone carrier of sorts, using Archimedes Ships mod. Before the ship starts to move, I need to collect drones back to my inventory or chest, and after ship stops I launch them again. And here is the problem, if the drone was programmed to i.e. patrol around ships perimeter in 50 tiles radius from ship's center, shooting zombies, after the whole ship moved lets say 1k tiles north, the way I understand it, drone needs it's initial variables to be reprogrammed with GPS again, or it would fly back 1k tiles south and patrol the area where the ship initially was. I could do most of the programming with OpenComputers, the problem is then I need drone to provide coordinates for Drone Interface which is going to move along with ship, so I am back at the same problem.

**Comment by MineMaarten** [comment]
"Or is it possible to just initialize them as i.e. offsets from the drone's current coordinates"
Yes, I've added a few 'special variables'. There are two atm (and you can read about them in IGW-Mod):

$owner: Gets the coordinates of the owner of the drone, you as player.
$drone: Gets the coordinates of the drone itself.

So you could use the $drone variable here. Or, do it via a single hardcoded GPS coordinate, and calculate the two needed coordinates by taking away or adding offsets to that.

**Comment by notchriss** [comment]
Well then apparently there's everything I needed :) Thanks a bunch!
