### ISSUE TITLE
Interaction issue with AE2 resulting into duping

### ISSUE THREAD

**Issue by thatsIch** [MineMaarten/PneumaticCraft#427]
A user came to us, identifying a dupe bug by installing PneumaticCraft with AE2

https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/979#issuecomment-78306686

Any ideas?

**Comment by Nezraddin** [comment]
Hello,
I was the user who reported it. It was a matter of me not updating to the latest version, after figuring out the bug was connected to pneumaticcraft. With the newest version the bug disappeared.
I apologize for this mistake on my side.

**Comment by thatsIch** [comment]
closing then I guess, sorry for stealing your time.
