### ISSUE TITLE
Aerial interface preventing functionality of rightclick-hold items

### ISSUE THREAD

**Issue by CWW256** [MineMaarten/PneumaticCraft#430]
First discovered this while trying to shoot a bow. The aim animation would just continuously loop as long as the right mouse button was held down. Releasing the mouse button would never actually fire the arrow. This was affecting vanilla and all modded bows I tested. This also affected the horn of the wild from Botania which uses the right mouse hold to break plants in an area around the player. Holding the mouse would start to play the animation and sound, but the sound would end without producing the plant break effect even though the right mouse button was never released. It also affected eating. The eating animation and sound would play, the food item would disappear from your inventory, and your hunger bar would fill, but shortly after the hunger would drop back down to the level it was before eating and you would find (if you sort your inventory with the invtweaks function) the food is still in your inventory.

I dismantled my entire base trying to find the problem and realized that when I removed the aerial interface the problem went away.

I can place the aerial interface and there is no problem, but once it reaches the 10.0 working pressure the right click problem comes back. Breaking the interface immediately fixes it.

Unfortunately if I create a fresh world and attempt to reproduce the problem, I can not. Everything seems to work, but I can consistently reproduce this in my main play world with the exact same mod set.

Some pictures (not sure if they will help).
http://puu.sh/gBV7q/a41b0c87c7.jpg
http://puu.sh/gBVdv/e065d5713b.jpg

If there is any other testing I can do to help figure this out I will. Providing mods/versions/etc.

EDIT: After additional testing, I am even able to add a new aerial interface in the main play world and apply pressure with a creative compressor and the problem does not occur. I am stumped as to why just placing and pressurizing this particular interface causes the problem.

**Comment by MineMaarten** [comment]
Might it be possible that the connected Transfer node is doing something strange that does this?

**Comment by CWW256** [comment]
Will test with other forms of item transport and edit results into this comment.

**Comment by MineMaarten** [comment]
Going to close this as I don't think it's my issue / I can fix it from my side.
