### ISSUE TITLE
Drones refuse to place Wither Heads

### ISSUE THREAD

**Issue by aetherpirate** [MineMaarten/PneumaticCraft#431]
Attempting to automate Wither Boss creation. I made two programs, one for a drone to place the soul sand-- works fine. Another for a 2nd drone to place the heads, it doesn't recognize wither heads as a valid item to place. It works with other blocks. Is this intentional, or a bug?

**Comment by MineMaarten** [comment]
Wither Heads might not be a block internally. Try using the 'right click block' piece instead of the 'Place' piece. Make sure to select the soul sand blocks as area (as that's the block you're right clicking), and select the 'top' as the side that's right clicked (by default the bottom).

**Comment by aetherpirate** [comment]
Thanks! That worked!
