### ISSUE TITLE
Assembly Controller 

### ISSUE THREAD

**Issue by rodseb** [MineMaarten/PneumaticCraft#433]
hi
I have a problem for the assembly controller boards
PneumaticCraft-1.7.10-1.6.3-65-universal

before
<a href="http://www.hostingpics.net/viewer.php?id=553205RecipeAdvancedPressureTube.png"><img src="http://img15.hostingpics.net/thumbs/mini_553205RecipeAdvancedPressureTube.png" alt="Heberger image" /></a>

after

<a href="http://www.hostingpics.net/viewer.php?id=79352320150323222620.png"><img src="http://img15.hostingpics.net/thumbs/mini_79352320150323222620.png" alt="Heberger image" /></a>

**Comment by MineMaarten** [comment]
I think you simply don't understand how the machine works?
It's on the wiki.
Also, I'm seeing 1.6.4, so even if it was a legit issue, the version is not supported.

**Comment by rodseb** [comment]
Hello
Alor why the recipe button is in the inventory.
missing the 8 slots (4 for resources  + 4 the result) of the machine, you can not use the

<a href="http://www.hostingpics.net/viewer.php?id=63022120150324235033.png"><img src="http://img11.hostingpics.net/thumbs/mini_63022120150324235033.png" alt="Heberger image" /></a>

follows in wotre wiki + tutorial is using the 1.6.x

**Comment by MrKunji** [comment]
You need two Assembly IOs in the assembly line, one for the input, one for output, there aren't actual slots. The wiki have this piece of information, if I reccal correctly.

**Comment by rodseb** [comment]
I provided all green

<a href="http://www.hostingpics.net/viewer.php?id=84399420150325001845.png"><img src="http://img11.hostingpics.net/thumbs/mini_84399420150325001845.png" alt="Heberger image" /></a>

How do I import the resources?

**Comment by MrKunji** [comment]
http://www.minemaarten.com/wikis/pneumaticcraft-wiki/pneumaticcraft-wiki-assembly-machines/
All information you'll need

**Comment by rodseb** [comment]
For me, it lacks the slot resource ?


![](http://www.minemaarten.com/wp-content/uploads/2013/10/RecipeAdvancedPressureTube.png)

![2015-03-25_00 18 45](https://cloud.githubusercontent.com/assets/11620540/6815240/7e7f16e2-d287-11e4-9640-deb29d842782.png)

**Comment by MrKunji** [comment]
The input is a chest on the side of a blue Assembly IO Unit, the output is another chest on the orange IO Unit.
Then you need the corresponding Program to be in the Controller.

**Comment by rodseb** [comment]
ok thank you, I had trouble connecting boxes
