### ISSUE TITLE
Drone Issue

### ISSUE THREAD

**Issue by Deathwinng** [MineMaarten/PneumaticCraft#439]
Hello, I wanna say that I love this mod! Especially drones, doors and elevators, simply awesome!
But I noticed a bug in drones. I program it just to pick up items from chest and place them. The drone has 10 dispenser upgrades and when it take the items, it goes, places 5-10 (sometimes 1-2 stacks) of them and comes back to take more and that's repeat until the chest is empty (and sometimes when the chest is not even empty). And when that happens it just stay where it is like it ran out of items to place but it has like 9 stacks left in it. And I have to take it with the wrench an place it again. But the same thing happens after that.
Using 1.6.4-66 version of the mod.
Keep the awesome work and sorry for my English. :)

**Comment by MineMaarten** [comment]
Confirmed, found the cause, and fixed it!:)

The drone, rarely when trying to place a block, couldn't, because the drone itself was in the way. Therefore the drone was like "well, I can't place any blocks, so I'll continue with the next command". This is a bug obviously.
