### ISSUE TITLE
[Bug?] Elevator causes fall damage

### ISSUE THREAD

**Issue by aschmois** [MineMaarten/PneumaticCraft#440]
When going down an elevator and it has a high speed, the elevator goes down but steve stays put for about a second so he receives fall damage by the time he catches up. Is this intended?

**Comment by MineMaarten** [comment]
not intended. Version?

**Comment by aschmois** [comment]
Seen in version 66, 67, 68. I only see this happening on multi block elevators. And it happens a lot more when the speed is really high.

I can also reproduce it by standing right in between two elevator blocks.

**Comment by budgej** [comment]
I am getting this on a multiblock elevator as well.  Seems to be worse when the TPS drops.  Over time the elevator gets farther away from me visually, yet my character bounces higher and higher up, as if the client and server disagree on where the elevator's at.  Almost always results in death at the bottom.  Version 1.6.8-72 in a custom pack.
