### ISSUE TITLE
Variable $drone in Coordinate puzzle piece freeze the game

### ISSUE THREAD

**Issue by cvl43177** [MineMaarten/PneumaticCraft#441]
Replicateable condition:

Make a program for drone that consist of:
Start -> Coordinate Operator (given any name) + Coordinate 
For Coordinate, use Variable with name "$drone"
Program it into a drone (filled or not)
Place it into the world
result: javaw.exe use up maximum CPU percentage (96% for me) and no longer possible to play (not crash)

This is using the version PneumaticCraft 1.6.6-68 on and Forge 10.13.3.1366

**Comment by MineMaarten** [comment]
Hmm, I can't reproduce it... I've programmed the drone with this program:
https://www.dropbox.com/s/qbkaty2ge07v5fz/testCaseDrone.PNG?dl=0

And put down multiple for good measure:
https://www.dropbox.com/s/p5s75uv8sa8eebd/2015-04-14_21.52.58.png?dl=0

Ram seems to behave like normal. Any suggestions on how I can reproduce this?

**Comment by cvl43177** [comment]
The problem is apparently specific to Forge 10.13.3.1366 with certain combinations of mods I had installed. . It is no longer appear in Forge later version (1370+). I will retract this report as the problem is more likely due to Forge and has been fixed.
