### ISSUE TITLE
"canSustainPlant" instead of "check for dirt" when planting seeds

### ISSUE THREAD

**Issue by Robijnvogel** [MineMaarten/PneumaticCraft#442]
Dear MineMaarten,

In order to make mods that have plants in them more compatible with mods that add different kinds of soils to plant plants on, Forestride from Biomes Of Plenty, suggested that mod authors use the Forge canSustainPlant flag to check for plantability, rather than checking whether the block to be planted on is dirt.

I have actually looked up in your code how you do this, before suggesting anything and I found this comment that suggests that checking for dirt is exactly what you do.

"// when the entity on the ground check whether the block beneath it is
// dirt, and the block above it is air, if yes, then plant it."

Can you consider changing this? In new updates Biomes Of Plenty is going to add a lot of soils that will cover whole biomes. I can imagine that a lot of PneumaticCraft users are using BoP and it would be sad if they were to suddenly find complete biomes void of their colourful plastic plants and full of useless soil.

A stitch in time saves nine (Voorkomen is beter dan genezen)

**Comment by Robijnvogel** [comment]
This Issue just became a bit more pressing. I thought BoP was only doing this in their 1.8 releases, but I am already finding whole plastic-plantless biomes on my 1.7.10 worlds now.

**Comment by MineMaarten** [comment]
so... what's wrong with this again? I'm using canSustainPlant right?

https://github.com/MineMaarten/PneumaticCraft/blob/master/src/pneumaticCraft/common/block/pneumaticPlants/BlockPneumaticPlantBase.java#L89

**Comment by Robijnvogel** [comment]
Sorry, I was referring to these lines
https://github.com/MineMaarten/PneumaticCraft/blob/master/src/pneumaticCraft/common/item/ItemPlasticPlants.java#L320-321
I guess that comment outdated and should only be about water now?

But I don't really know why there are no PC plastic plants generating in my BoP biomes then. :/
So this stays an issue.

**Comment by MineMaarten** [comment]
This code is only executed for flying seed entities.
