### ISSUE TITLE
Question regarding possible API changes

### ISSUE THREAD

**Issue by ReikaKalseki** [MineMaarten/PneumaticCraft#445]
After updating to the latest PnC version, some people are seeing NoClassDefFound: IAirHandler messages. Has the API changed incompatibly?

**Comment by MineMaarten** [comment]
As you can see right here, there hasn't been a change to the API for over 2 months now: https://github.com/MineMaarten/PneumaticCraft/tree/master/src/pneumaticCraft/api

And IAirHandler for 6 months. Plus the fact that it should be backwards compatible.

More info? Does this happen with PnC installed? Or could it be that you're accidentally trying to load the class without PnC being in there?

**Comment by ReikaKalseki** [comment]
I do not currently use PnC myself (this is coming from another user), so I do not know all the details. What I was told is that updating PnC caused the PnC converters I have to crash with a NoClassDefFound on IAirHandler.

I do not ship the PnC API (I do not think I ever did).

**Comment by MineMaarten** [comment]
Ok, without more info I can't help, I can only say that the API hasn't changed significantly, so it shouldn't be a problem.

"I do not ship the PnC API (I do not think I ever did)."
I'm sure you did at least at the beginning, when you added support for it. I remember getting a lot of crash reports, after which I had to tell people to remove my API from the DragonAPI. So, yes. But if it isn't the case anymore, good :)
