### ISSUE TITLE
Log spam with Drones in Last Millenium dimension from extra utilities

### ISSUE THREAD

**Issue by devryb** [MineMaarten/PneumaticCraft#450]
This spams over and over in the log until the server crashes with drones in the world

http://pastebin.com/WydeDY6D

**Comment by MineMaarten** [comment]
Are you using the latest version, 1.6.7? If not, try it. I should have fixed this.

**Comment by devryb** [comment]
Ah ok were using an older version, thanks.

**Comment by MineMaarten** [comment]
But, it did resolve the issue then?:)

**Comment by devryb** [comment]
I won't know until FTB updates it in the Trident pack and I haven't seen this yet in any other modpack. For now we just rolled back that world a couple hours to get things running again.
