### ISSUE TITLE
crash w/ latest ee3 0.3.478

### ISSUE THREAD

**Issue by loordgek** [MineMaarten/PneumaticCraft#453]
https://gist.github.com/loordgek/b74e9f6d881e099af8d7

**Comment by MrKunji** [comment]
Diasble EE3 integration in Pneumaticcraft's config as a workaround.

**Comment by Wolwrig** [comment]
Agreed, @MrKunji. 

Under the *third_party_enabling* section of the PneumaticCraft.cfg file set **B: EE3=false**

**Comment by MineMaarten** [comment]
It's something due to a change in the EE3 API. just by recompiling this should be resolved.

**Comment by MineMaarten** [comment]
1.6.8 should work (on curse in a sec)
