### ISSUE TITLE
Cannot Insert seeds into Forestry Multifarm

### ISSUE THREAD

**Issue by SmugApple** [MineMaarten/PneumaticCraft#456]
I am unable to insert any of the PneumaticCraft seeds into a forestry multifarm except for the squid plant seeds.

I am using the smallest size multifarm and the circuit board is set as an automatic farm with four different types of seed. 

I have tried inserting the seeds by hand, with shift-click, via a hopper and via itemducts. They will not enter the farm. 

Squid plants enter and are planted fine. 

PneumaticCraft 1.6.3-65-universal
Forestry 3.4.0.7
Forge 10.13.3.1305
Minecraft 1.7.10

(first time doing a bug report so tell me if any detail is missing)

**Comment by MineMaarten** [comment]
Won't fix due to plant deprecation, oil will be used as replacement feature.

**Comment by 016Nojr** [comment]
So no forestry farms except squid seeds? :/ Oil be used as replacement feature?

**Comment by MineMaarten** [comment]
That's right. https://imgur.com/a/gEysk for more info. It's just too much effort to figure it out (I've spent time already trying to figure it out). That combined with the fact that the plants will be removed made me do this. Sorry :(
