### ISSUE TITLE
Crash on Server Side

### ISSUE THREAD

**Issue by Amaxter** [MineMaarten/PneumaticCraft#458]
http://hastebin.com/yenahurimi.coffee
With latest version this crash occurs on server startup.

**Comment by Oxosorrel** [comment]
Try rolling Farseek back to 1.0.6 ... I had the same crash with Farseek 1.0.7 and latest pnuematicraft, both under forge 1395 and 1403... and had similar crashes on other mods, even after yanking out pneumaticraft. Rolling back Farseek fixed it for me. 

I reported to farseek dev here: https://github.com/delvr/Farseek/issues/1 if rolling back farseek fixes it for you, let them know.

**Comment by MineMaarten** [comment]
Ah thanks for the addition Oxo. I already was like O_o, because I had no clue what might have caused it. Thanks.
