### ISSUE TITLE
heat mechanic concerns

### ISSUE THREAD

**Issue by pyure** [MineMaarten/PneumaticCraft#459]
Just an informative piece:

We're finding the heat mechanic to be inconsistently intrusive.  There's no really good reason why it should suddenly impact the advanced machines even when they're running without any overclocking (speed upgrades).

Even with a full array of compressed blocks + heat sinks (15 blocks per machine, sinks on all sides) its impossible to run a flux compressor at decent efficiency with, say, five speed upgrades. 

A good cooling system should effectively allow your users to use the maximum number of speed upgrades, and on these machines, speed upgrades are absolutely critical.

For what its worth, we like the heat mechanic in principal, but we hope a future version will make it more responsive to cooling measures.  Used IGW two months ago to brush up on available cooling measures.

**Comment by pyure** [comment]
![2015-05-09_18 40 21](https://cloud.githubusercontent.com/assets/8617528/7552315/f3139b0a-f67b-11e4-8283-48cb4d27036e.png)
![2015-05-09_18 41 25](https://cloud.githubusercontent.com/assets/8617528/7552316/f6df9b58-f67b-11e4-9650-68e0b7839eff.png)

**Comment by pyure** [comment]
Update: have also tested vortex tubes and heat grate modules.

The vortex tubes were incredibly disappointing.  Pressurized, at a glance they seem to create a nice negative-heat value.  But testing showed that even at 20bar pressure, the temperature of the flux compressor actually INCREASED considerably (confirmed the cooling end was pointing at compressor and the machine was properly pressurized)

Air grates modules were somewhat better.  We can use nothing but heat sinks around a machine and several air grates to improve their performance.

Image: Annoyingly, when using air grates, the heat sink flush against the compressor is actually more efficient at drawing heat than compressed iron + heat sinks, notwithstanding that its red.
![2015-05-10_10 16 38](https://cloud.githubusercontent.com/assets/8617528/7554639/d282b2cc-f6fd-11e4-8211-cd7ec838cd43.png)

Sadly no matter what we do, we can't seem to draw heat out of the compressor quickly enough.   Even when the heat sink is down to 45C, the compressor can be as high as 185C.  The differential between adjacent blocks shouldn't be so high.

Would love to see more focus on this mechanic; its great in theory, just needs some attention to improve the fun factor.  In this case, a big heat-sink array costing hundreds of iron should allow users to use maximum speed upgrades. 

As it stands, unless I'm missing something, the ten-max limit on speed upgrades appears to serve absolutely no purpose: there's no way to actually use it.  

I'm really trying to make this work.  Let me know if there's anything specific I can test or clarify, I'm happy to help work on this.

**Comment by belathus** [comment]
Fluids work with PneumaticCraft's heat system. It also functions off of DeltaT. That said, cryotheum has a temperature resistance of 50 but a static temperature of -245C. Heat sinks have a temperature resistance of 14 and a static temperature of +22C. What this means is, if you can keep the compressor below approximately 150C, cryotheum is a better cooling medium while above heat sinks work better.

**Comment by pyure** [comment]
I don't believe PneumaticCraft has its own native gelid cryotheum unfortunately.  The overriding issue is that at 10 speed upgrades the compressor runs around 3000C or something insane and there's no way to actually use that maximum.

**Comment by MineMaarten** [comment]
I do agree with everything stated. I must admit I balanced the heat system around a system with 0 or 1 speed upgrade. Admittedly I haven't even tried putting in 10. I will look into rebalancing it :). Many thanks for the feedback. This is exactly the type of feedback I like on a recent feature like this :)

**Comment by pyure** [comment]
Goodness, thanks a bunch MineMaarten.  I'll be toying with this mod a lot over the next while so let me know if I can help by testing anything in particular.

**Comment by MineMaarten** [comment]
Ok, I think I've rebalanced it. Some stats: 

For the Advanced Air Compressor (the coal based one), the Advanced Liquid Compressor, and the IC2 converters I've decreased the produced heat by 4x, so they generate 4 times less heat.

For the Flux ones I had to do 20x reduction to make 10 speed upgrades worthwhile.

This yields the following:
-You've got a 62% efficiency with no speed upgrade, without any cooling
-96% if you connect up a single heat sink
-This set-up has 10 speed upgrades
https://www.dropbox.com/s/h8flvdlm0tcbehm/2015-05-11_18.07.34.png?dl=0
and has an efficiency of 35%, which is pretty good in my opinion. I don't want to allow 100% efficiency that easily, as increasing the speed by that much should have a drawback.

Let me know what you think, but I think this is pretty good :)

**Comment by pyure** [comment]
That was quick.

I'm not super clear on the setup.  According to your description it sounds like you have 10 speed upgrades, a single heat sink and 96% efficiency.  If so that's way too easy. 

However, the image you linked seems appropriate (in my mind) to a 90% efficiency scenario.   There's still some room for cooling below if you wanted to get it 100%.

Obviously a smaller setup would also work if you needed the space but didn't mind spending pressure on air grate modules.

Lastly: don't forget that your configs also handle efficiency ratings.  We use your mod a bit differently than most packs: compressed air is the only viable energy bridge between RF and EU, so we set the config percentages to 100% and let the Heat mechanic drive the difficulty.

Dunno if this helps, but if you wanted to dropbox a .jar I can test that within 24 hours easily.

**Comment by pyure** [comment]
Woops, I misread.  Your setup gives 35% with 10 speed upgrades.  Even with the configs set to 100 I feel this is a bit low.  I see room for improvement above and below the compressor but not enough to overcome the problem.

Key issue here: we  shouldn't be able to get 100% "that easily" but the question is, do you want them to be able to get 100% at maximum speed "at all"?

Personally I think 100% should be "possible." without spending air pressure on vortices and air grates (which would count against your efficiency since they cost air pressure).  If I spend 1000 iron on the problem in heat sinks, compressed iron blocks and space, that's no longer "that easy" don't you think?

**Comment by MineMaarten** [comment]
"but the question is, do you want them to be able to get 100% at maximum speed "at all"?"

Not necessarily. Compare it for example with IC2 speed upgrades, which increases speed, but decreases efficiency. Now this system doesn't decrease the efficiency on its own. That's where the heat system comes in.

Now with the image shown above you can get an incredible output (3000l/tick), at a 35% efficiency, with a decent but not stupid cooling set-up.

Knowing that the system needs an exponentional amount of heat sinks the further you get from the heat producer, it _will_ be impossible to get to 100% efficiency with 10 speed upgrades while also keeping the balance of 35% with this set-up.

If that doesn't work for you, you'll have to use 9 speed upgrades instead.

**Comment by pyure** [comment]
Okies fair enough.  

Viewed from a different angle: We currently have configurations for these efficiencies, which no longer make as much sense if we're also tackling efficiency in-game.  

They currently default to 40% per compressor, which means by default, depending on the order of operations and whether the configurations still do anything, I'd be getting 40% of 35%.  Would you be interested in replacing that configurable efficiency with configurable heat-efficiency-impact?

In almost any modpacks I think your 35% for maximum speed upgrades is completely reasonable, but in some specific oddball tech packs where I want PC to have a better energy conversion ratio than, say, Galacticraft, I'd need the flexibility.

(If you're not aware, both PC and GC have machines that allow you to create an energy bridge between different energy systems and with flexible configurations. Very, very handy for modpack designers.)

**Comment by pyure** [comment]
Thanks MM.  I saw the new commit; I'll review it tonight.

The configuration change wasn't appropriate for this thread.  If I still feel a need to harass you about that I'll raise another issue.
