### ISSUE TITLE
Acid bucket recipe accepts fresh water

### ISSUE THREAD

**Issue by JasonMcRay** [MineMaarten/PneumaticCraft#460]
The recipe for etching acid accepts fresh water from Pam's Harvestcraft as an ingredient. This allows you to get a free bucket each time you make one.

I tried to use ModTweker to hardcode the recipe to use ONLY vanilla minecraft bucket, but its still going to accept Fresh Water. Is possible that Pressure Chamber accepts items and "converts" them to oredict entries? Because thats what it seems like.

Tested with:
PneumaticCraft: 1.6.9
Forge: 1403
Harvestcraft: 1.7.10h

**Comment by MineMaarten** [comment]
So you're saying it accepts fresh water (which on it's own isn't a problem), but it doesn't actually consume this fresh water?

**Comment by MrKunji** [comment]
The things is: four fresh water are crafted with a bucket of water (returning a empty bucket), but when used in the Pressure Chamber can make Etching Acid, and once the acid is placed, you get a free bucket.

**Comment by MineMaarten** [comment]
That actually sounds strange that Pam registers it as ore dict equivalent to a bucket then? or is it just me?

**Comment by MineMaarten** [comment]
Oh no wait, in recipes it makes sense I guess, as then you won't get back the empty bucket... hm...

**Comment by JasonMcRay** [comment]
Yup. I havent installed Iguana Tweaks and their Clay bucket. But if it works bit similiar that Pam's Harvestcraft Fresh Water, that would be also an issue.

**Comment by JasonMcRay** [comment]
Also wouldnt be better to not look for oredict equivalents at all? Instead call for oredictionary directly?

**Comment by JasonMcRay** [comment]
I see plenty of pneumaticCraft updates but this issus is still not fixed. Has it been forgotten?

**Comment by MineMaarten** [comment]
Two reasons:
1. Fixing it isn't trivial.
2. As it's 'just' an intermod quirk, it has a lower priority than other bugs have.

But it most certainly hasn't been forgotten, and I'll try to get it in next version.

**Comment by MineMaarten** [comment]
There you go ;)

**Comment by JasonMcRay** [comment]
Awesome, good job, thanks a lot.
