### ISSUE TITLE
Enabling/Disabling Node Connections

### ISSUE THREAD

**Issue by TYKUHN2** [MineMaarten/PneumaticCraft#464]
The ability to enable/disable connections between different nodes so that nodes touching eachother don't necessarily connect.

**Comment by TYKUHN2** [comment]
Oh and I ment in the security station for those wondering.

**Comment by MineMaarten** [comment]
Not going to implement this because of the following two reasons:

1. I like the current limitation of networking space
2. I like the current simplicity in configurating a network
