### ISSUE TITLE
Aerial Interface EntityItem

### ISSUE THREAD

**Issue by eduvm** [MineMaarten/PneumaticCraft#469]
Firs, sorry my English, not my default language.

My Aerial Interface is configured with Dispense Upgrade to keep me fed.

This suddenly stopped working, and now i am receive this on Server Console:

 [Server thread/WARN] [FML]: Attempted to add a EntityItem to the world with a invalid item at (88,12,  61,20, -464,05), this is most likely a config issue between you and the server. Please double check your configs.

I checked and the message log appear every time that i am supposed to be fed.

I tried to remove and put the Aerial Interface again and not worked.

PS.: The Aerial Interface is supplied with Applied Energistics Export Bus

**Comment by MineMaarten** [comment]
I think I've fixed it, I'm not 100% sure though. Let me know if it has not, when using the new upcoming version :)
