### ISSUE TITLE
Compress IGW images

### ISSUE THREAD

**Issue by Ephys** [MineMaarten/PneumaticCraft#470]
It takes ages to upload PC to a server because the assets for IGW are 9mB big (and my connection is awful), can you please compress your assets ? There shouldn't be any noticeable difference and it can seriously reduce the size. If you need a compressor, I use https://compressor.io/compress and it works pretty well

**Comment by MineMaarten** [comment]
compressing it? and then what, decompressing it codewise when I actually want to use them?...

**Comment by Ephys** [comment]
You don't need to do anything code-wise, 

I just compressed the pictures from TSteelworks' manual, didn't have to change anything except the assets themselves and everything went well (using Minecraft's texture manager) http://screencloud.net/v/9r2x (left uncompressed, right compressed ingame)
