### ISSUE TITLE
Drone attacking entities cause FTB Trident Server crash.

### ISSUE THREAD

**Issue by Barney626** [MineMaarten/PneumaticCraft#471]
Hi, I am unsure whether this is a common issue but when a drone uses a sword to attack an entity (entity attack command) the server crashes after the 2nd or 3rd hit from the drone irrespective of mob or sword type. 

Running FTB Trident 1.0.0, No added mods ,Forge server.

Potentially something to do with the battlegear mod.

Crash report: http://pastebin.com/PqFNK9Dd

Thanks

**Comment by MineMaarten** [comment]
I think this issue is on BattleGear 2's  side.
