### ISSUE TITLE
Drones fall off charging station and stop recharging

### ISSUE THREAD

**Issue by dalgrim** [MineMaarten/PneumaticCraft#475]
I've found an error where drones are falling off/pushed off (by Thaumcraft Golems) of the charging station. What happens is as soon as the drone is not in the block-space as the charging station they stop recharging. This renders them useless as they are still treated as an entity at that point but will not recharge.

This is in the Direwolf20 1.3.1 pack for FTB1.7.10.

![dronecharge](https://cloud.githubusercontent.com/assets/12730893/7959979/117e0b90-09cb-11e5-846c-056a806009ce.jpg)

**Comment by dalgrim** [comment]
Here is a screenshot of where I find the drone when it falls off:
![droneoff](https://cloud.githubusercontent.com/assets/12730893/8024081/d3347df6-0cf4-11e5-9c75-3e5e0dc0aade.jpg)

**Comment by MineMaarten** [comment]
I can see this happening yes. I guess I'll have to make the drone re-enable the propellors when it leaves the block it should be staying in.

**Comment by dalgrim** [comment]
thanks!!

**Comment by MineMaarten** [comment]
that's intended behaviour. The only thing the Charging Station with dispenser upgrade is doing is charge anything that is on top of it. The only thing the drone is doing is go above the charging station, and turn off to save power. usually it will still charge, but when it falls of it obviously doesn't :P
