### ISSUE TITLE
[Feature] Pressure Chamber

### ISSUE THREAD

**Issue by DireTry20** [MineMaarten/PneumaticCraft#483]
you can't read the pressure of a pressure chamber with computer craft with out a valve which leaks air.

possible fixes (that i can think of):
- allow the reading of the pressure chamber from anywhere (most useful)
- allow solid blocks to stop air from escaping or just white list computers and modems.

**Comment by MineMaarten** [comment]
or... measure on a tube, not pressure chamber :P
