### ISSUE TITLE
ComputerCraft wrapping

### ISSUE THREAD

**Issue by DireTry20** [MineMaarten/PneumaticCraft#487]
all Pneumatic Machines wrap as the same Machine type. 
eg. Both a compressor and a tube will wrap as "PneumaticMachine_0" or "PneumaticMachine_1" ect

It would be great if they could be different. 
eg. "PneumaticCompressor_0"

PS. im not *100%* sure that this as a bug with PneuCraft, it might be a CC bug. but it seems to be PneuCraft

**Comment by MineMaarten** [comment]
It's not considered a bug really, I knew this would happen actually. I did this for code simplicity. But I can change it for you ;). Let's hope I won't break many existing programs by doing so.

**Comment by DireTry20** [comment]
Thx
