### ISSUE TITLE
Elevator roofs

### ISSUE THREAD

**Issue by drrk** [MineMaarten/PneumaticCraft#490]
It would be nice if you could add a roof to elevators, it would make it more realistic. 

Thanks :)

**Comment by MineMaarten** [comment]
You could do it yourself for aesthetics. As this is a pressure powered elevator from the bottom rather than one where the motor is on top, it wouldn't be suitable.

**Comment by drrk** [comment]
I think you misunderstood me - I am talking about a roof that is say 3 blocks above the floor of the elevator and rises with the elevator. Currently if you have a tall elevator you look up and see all the way up, which isn't like any elevator I have ever use, even ones that are pressure powered from the bottom.

Incidentally, having discovered that the mod is open source (something that seems to be very rare with minecraft mods) I had planned to attempt the addition myself.

**Comment by MineMaarten** [comment]
Meh, that might be a bit unrealistic yes. But don't think I'll like the looks of it with a roof either...

A mod being open source isn't that rare ;). You could do a PR, but in  this case I don't think I will accept it, sorry :|
