### ISSUE TITLE
[Mod Incompatibility] Tubes mod version of liquid plastic not compatible, plastic mixer will not accept.

### ISSUE THREAD

**Issue by utoc** [MineMaarten/PneumaticCraft#492]
Greetings

I'm running PneumaticCraft 1.8.1-83 with FML 1448 and am having trouble creating plastic.

We've refined oil into LPG and LPG into liquid plastic into a drum.  We're unable through any means we find of inserting the liquid plastic into the plastic mixer via buckets or EnderIO fluid conduits.  I've heated up the plastic mixer to 600C and cooled it off to -50C and still we can't get any of the liquid plastic to insert into the plastic mixing machine.  I cannot find any further documentation on the process if I have done anything wrong.  I'm not sure if this is a bug or user error.

Any assistance would be appreciated.  If this is the wrong avenue, please accept my apologies and close the ticket.

**Comment by MineMaarten** [comment]
Just pumping fluids in by any means should work... Does it work when using other methods, like BC liquid pipes / fluidducts / Liquid Hopper ?

**Comment by utoc** [comment]
I've attached a few images:

Transfer nodes: https://i.imgur.com/GjhJvqn.png (no texture at all)

BC Transfer pipes: https://i.imgur.com/WKrzXoe.png (texture looks like water)

TE Fluiducts: https://i.imgur.com/jYcbCP6.png (texture looks like lava)

I tried the fluid hopper pointing at the top, it also did not work (texture looks like water).

The result of all these is that the PlasticMixer GUI looks like so: https://i.imgur.com/YNeJVU4.png

**Comment by utoc** [comment]
Just for grins, I tried to directly extract the plastic from the Thermopneumatic Processing Plant with TE into the side and the top of the plastic mixer.  Same issue, it does not accept the fluid: https://i.imgur.com/4zxldr4.png

**Comment by MineMaarten** [comment]
Weird... In my development instance it works fine, with the ForgeCraft instance (having over 100 mods) works fine as well..
https://www.dropbox.com/s/nwca360oa2cfb5x/2015-06-19_14.45.35.png?dl=0

Not sure what I can do to reproduce it...

**Comment by utoc** [comment]
I'll remove a few mods in my test enviroment and see if I can narrow down whichever mod may be interfering.  I'm running the BBQSauce pack.

**Comment by utoc** [comment]
I tried creating plastic in single player with my exact same setup: success!  It appears that you cannot create plastic in a server/client environment.

Screenshots: https://i.imgur.com/w3Hjiio.png and https://i.imgur.com/EPPajNv.png

**Comment by utoc** [comment]
One more note: Putting dye in the plastic mixer results in white plastic regardless.  Is this intended behavior? https://i.imgur.com/34vN5PN.png

**Comment by MineMaarten** [comment]
yes... please read on how to properly use the Plastic Mixer. (In-Game Wiki mod)

**Comment by MineMaarten** [comment]
So on Forgecraft (dedicated server) it works fine.. so I'm not sure what's up, does it work now, on a server, for you?

**Comment by utoc** [comment]
I'm awaiting FTB to update to -84, once it does I will start removing one mod at a time until I find out what is causing the incompatibility.  I will get back with you on this.

**Comment by utoc** [comment]
Hello!

I had time to test this over the weekend.  The "Tubes" mod is interfering with the plastic/plastic buckets and even texture in multiplayer.  I removed the mod to test further and still cannot get the plastic machine to make plastic from liquid plastic in multiplayer, only single player.

The plastic mixer accepts the liquid plastic in both SSP and SMP, however in SMP (server/client), it does not convert the liquid plastic to plastic at any temperature from -250C to +1000C.  In single player, it converts the liquid plastic to plastic at 33C.

Let me know what you think of this.  I wonder if you could test making plastic in your plastic mixer on Forgecraft from liquid plastic on both single and server/client.

Here are some screenshots that may help:

Single player, temperature at 33C (no vortex used): https://i.imgur.com/3A42QIv.png

Multiplayer, temperature the same, 33C: https://i.imgur.com/FT8gAAQ.png

**Comment by utoc** [comment]
@MineMaarten I think Tubes may be abandoned at this point.  I'm closing this issue since they have one open on their end.
