### ISSUE TITLE
Using a bucket to add any fluid (diesel, LPG, kerosine or Gasoline) you will lose your bucket

### ISSUE THREAD

**Issue by utoc** [MineMaarten/PneumaticCraft#494]
Greetings,

We're running PneumaticCraft 1.8.1-83 with FML 1448.

Currently when placing buckets of gasoline, kerosine, LPG or diesel into ExtraUtilities's Drums, you lose your bucket.  WAILA does show the amount of fluid in the drum increases by 1000mb.  The correct behavior is that the bucket should be transformed into an empty bucket.

Is this a PneumaticCraft issue or a ExU issue?

**Comment by MineMaarten** [comment]
Probably my issue.

**Comment by utoc** [comment]
One more note to add: You cannot get plastic from a Plastic Drum.  If you right click with a bucket, you will remain holding an empty bucket.
