### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by RikuSS4** [MineMaarten/PneumaticCraft#497]
I would like the drones to have an option to sneak right click. Also, when use dig on a drum from Extra Utilities, the drum disappears. Is the drone supposed to do that? I would like it to be able to basically do the same as left clicking with an item it holds, like when using silk touch pickaxe pick up the block.

**Comment by MineMaarten** [comment]
>Also, when use dig on a drum from Extra Utilities, the drum disappears. Is the drone supposed to do that?
I hope you mean it breaks and drops on the ground? In that case, yes, that's supposed to happen.

**Comment by RikuSS4** [comment]
It does not drop the item. I tried with a silk touch diamond pick. Same thing. The drum just disappears. I am using minecraft version 1.7.10, direwolf20 modpack version 1.4.1, and forge version 10.13.3.1408. I thought about using a wrench, but it needs shift right-click to pick up the drum. Which is why I requested it be added.
