### ISSUE TITLE
Lazy drones not going back to their charging station.

### ISSUE THREAD

**Issue by Axylxys** [MineMaarten/PneumaticCraft#501]
That one is a bit hard to replicate as it seems to happen once in a while. As the title says, the drone performs his tasks seemingly well, then drops to the ground and does nothing. After picking it up i notice it's at 0 pressure, while there's a charging station waiting for the drone a bit further: full pressure, nothing else obstructing the station.

Everything is chunkloaded, i was even nearby when it happened last time, watching the drone place blocks for me (a basic building program, placing blocks in a wide area). I was literally thinking at that time "Eh that drone is really working well." then bam, it dropped as it ran out of pressure, in a seemingly well-timed attempt to make fun of me. Oddly enough, it ran with the exact same program one hour ago and worked fine. 

It also happened some days ago with digger drones, they were almost done then both of them stopped going back for their pressure. I charged them again by hand, then sent them again on their task, same result: they cleared as much as they could and fell to the ground. Though i was almost done so i finished with a shovel and didn't bother thinking much through this.

That very same case happened on my farm as well, and yesterday i found the two drones on the floor despite them having not one, but two charging stations full and only a few blocks away. One of them was literally 3 blocks away from the station as i put it right near the farm field to make sure they wouldn't miss it, but no way. Maybe that's linked to the "drone can't teleport" bug below but, i don't think they need to teleport when they're sitting next to the station, right ?

In all cases the programs are different, drones don't have the same upgrades (all of them have the item life upgrade, some have speed or dispenser, some have none of those), neither do the stations (dispenser + security + various amount of speed upgrades).

I don't think there's any mob with an invisible EMP device shooting drones out of the sky, that said i'm out of ideas on what could cause them to stop recharging. Any idea, or any workaround to that maybe ? It's a fairly annoying one as that means they're not reliable (if my farming drones run out of energy and stop working, that's potentially my whole base going out of power within a few hours if i don't notice). :(

**Comment by MineMaarten** [comment]
Hmm this one may be harder than the other one.. Especially because I watched the charging behaviour of drones for #496 , and they appeared to go to a charging station fine when they didn't need to teleport.

How many drones do you have? Keep in mind that a Charging Station only allows one Drone to be charging on it at a time. So if all Charging Stations are occupied, the drone will not charge, ultimately will fall down. Might that be it?

**Comment by Axylxys** [comment]
I thought about the charging station being already taken so i made sure it was not the case. The farming drones are two, and they have two stations (each one is close to its assigned drone, and both drones are in range for both stations if one of them fails). 

The drone placing block was alone and i was nearby so i can confirm the station was full, empty and not blocked in any way. 

As for the digging drones, they were two for a single station (it was a short work sequence) but i was nearby as well and neither of them even tried flying back to the station.

**Comment by MineMaarten** [comment]
Ok weird... The last thing I can think of (by going through the decision making in the code) is that it can't go to a Charging Station because of a Security Station protecting the Charging Station from the drone. You don't have those by any chance?

**Comment by Axylxys** [comment]
No security station indeed, i don't even have one to begin with. I tend to think it's not related to the drone itself but more like, the station suddenly isn't detected anymore by the drone, maybe ? So they think they don't have one and never bother to run back.

I placed again the drone that bugged like that earlier (the block placer). I didn't touch the station inbetween, and this time he came back properly to get his pressure back. :/

**Comment by MineMaarten** [comment]
The Charging Stations aren't cached. Every time the drone tries to find a place to tap air, it will begin with a clean lookup through the charging stations...

**Comment by Axylxys** [comment]
So that could explain something if for some reason he can miss the detection, could any kind of interaction be responsible for that ? It's obviously not the range (happened from as close to 3 blocks, up to about 50 blocks). On that specific case above, the station is up in a tree to be safe from mobs, with a single air compressor, and a chest nearby. No machine, force field or anything that could interact with it that i can think about.

**Comment by Axylxys** [comment]
If it helps, here's the setup:

http://pasteboard.co/1uqbDwEl.png

The building area is in the warehouse behind, the floor, so not really far either. The screenshot below is the result of several building trips by that little drone, one out of 5 resulted in the bug so far. Also, he's set to place blocks close, and he seems to go randomly in a different way each time he's flying back, making that funny abstract masterpiece of tin blocks, that's quite entertaining to watch !

http://pasteboard.co/1uqlwcZk.png

**Comment by MineMaarten** [comment]
I'm really not sure :|. The only limitation would be the range, but if you say that's good then I believe you... If the range wasn't you would see enderman particles anyway (even though the actual teleporting is broken atm)

**Comment by Axylxys** [comment]
Out of curiosity, what's their actual range ? I remember seeing the ender particles quite a few times (not for such cases though) and i guessed it was something about the drone being too far, i didn't know it was about actual teleportation though. But yeah, no particles when it happened for the cases explained above, they were just flat inactive on the ground.

Is there anything i could investigate to help find the cause if it happens again, maybe ? I don't mind doing some effort around that and try to investigate the bugs, especially such a frustrating one. Could it come from another mod messing up the drone interaction with the station, can they even be affected by something else ? Just some food for thought, i'm not a modder myself so i only learn by trial and error and trying to fix what breaks on the server.

**Comment by MineMaarten** [comment]
The range is 75 blocks, sufficient for most applications. As I've never encountered this strange behaviour I can't reproduce so not help you find out I don't think...

The checking whether or not to go to a charging station really is as simple as doing:
-execute when the pressure of the drone is < 1 bar.
-Loop through every charging station in the world.
-For every charging station in the same dimension as the drone, if the pressure of the charging station is > 1 bar, no other drone has claimed it, and it has a dispenser upgrade, add it to a 'valid charging station' list.
-Sort the list from closest to furthest charging station.
-For every charging station in that list, check if it's allowed by the security stations close by, and if so, try to find a path. If found, fly over there, and algorithm is done.

There is a slight chance the fix I implemented to allow drones to teleport to charging stations might also affect this, but I'm not sure. I recommend trying this version when it comes out, and see if you can see similarities in situations where it fails if it fails again.

I can't do anything more I'm afraid, until there is a reproduce-able scenerio

**Comment by Axylxys** [comment]
Alright, thanks for the details again. When it will happen (if it does) i'll double check everything in case i can find a new detail i missed. 

That said, i'm thinking about possible workarounds. I suspect the new drone controller could avoid that, as it can receive the pressure at all time through the block itself, however it's less entertaining than the real drones.

Is there a way to emulate that behaviour and reliably force the drone to go back and charge its pressure no matter if he's already high ? I guess i could add that in the programming sequence to make sure it goes back to charge between each cycle of the program, but i don't remember seeing a puzzle piece for that, though i'm pretty new to all of this so i could miss it. I'd rather have the drone run back all the time for its pressure and waste a bit of time than risk it dropping on the floor.

If it's not possible, then it would be my first feature suggestion, that sure would come handy to avoid such issues !

**Comment by MineMaarten** [comment]
Yup, the Programmable Controller definately would be an option. You could also:

1. Use the Standby Piece. This turns off the drone's propellers stopping it from using any air while idling (waiting for plants to grow).
2. Use the Goto piece to make the drone navigate on top of the charging station. Just by being on top of the charging station drones will charge.

**Comment by Axylxys** [comment]
That's a good trick, i'll do that if it happens again. I like the "go to" anyway and i tend to give them a spot outside of the field so they have no risk getting stuck in a tree or something, i'll just place that one right on top of the charging station, i didn't think it was that simple.

**Comment by xxVladxxx** [comment]
Just wanted to pop in and mention that I'm having the same problem.  However, I am using 1.8.2-84 from the Direwolf20 FTB pack, so if it's been remedied since then (I didn't see any mention of it in the changelog, though), then all the better.

My setup looks like this:
http://i.imgur.com/hbkkXhk.png

I'm working on digging out that area on the ground with the exposed stone, and there's three charging stations up top.  I've got about 12 drones digging away happily, with two additional ones picking up all the stuff that's dropped from the dig.  However, despite there being three charging stations ready to go, occasionally a drone will just decide it's not worth the trip and just take a nap after digging a block.  It's good to know for future reference that they've got a 75-block range for the charging station (and seeing as this dig is actually a HUGE sphere, that would have been a problem eventually), but these stations are well within that range.  I even collected all the other drones and watched one run completely out and fall to the ground.

**Comment by Kexmonster** [comment]
I've had this same issue recently and found that after my server crashed, the drones weren't able to detect the charging stations that we're placed before the crash. I found that just moving the charging stations one block to the side - to a new block - resolved the issue and the drones were able to find them. However they did still not detect them with just breaking and placing it again, so moving it to a new block was neccessary.
