### ISSUE TITLE
Drone not interacting properly with RotaryCraft Extractors

### ISSUE THREAD

**Issue by Axylxys** [MineMaarten/PneumaticCraft#502]
Probably a minor bug report, so far i've had the drones interact correctly with most machines, however they miss entirely the RotaryCraft Extractors. In case you are not familiar with that mod, it has 4 top and 4 bottom slots. Items go in the first one on top, then the machine goes through various steps to extract stuff and pushed them automatically until they reach the last bottom slots.

Intermediate slots are blocked, and most pipes or automatic systems can only get items from the last bottom slot (the output one). However, drones seem to ignore it and only pickup items on the first slot, which is the input one. Not really useful, and playing with the side config (i tried bottom, all, etc) doesn't change anything, as if they don't apply to these machines.

It can easily be fixed by outputting to a chest before drones pickup stuff but i thought it's worth mentionning here.

Also, are such reports worth posting ? I don't want to spam pointless stuff in there, but i'm exploring PneumaticCraft so i'll probably find some minor issues like that or notice some details, i'll happily report them if you're interested in that kind of feedback. :)

**Comment by MineMaarten** [comment]
After looking at the code (both mine and Reika's) I can indeed see something I forgot to check. I'll fix it.

>Also, are such reports worth posting ?

Most definately! I'd rather have too many than too few reports. Invalid issues I can simply close. But minor bugs like these often don't get reported as they are.. minor. However I'm glad you're taking the time to report them, if nobody reports them they'll never get fixed ;). So thanks and keep it up :)

**Comment by Axylxys** [comment]
Thanks to you ! I'll make sure to report anything strange i see, i'm really enjoying your mod as well as your answers here, so i'll be more than happy to contribute to make it even better. There are so many abandonned mods or modders who don't bother checking endless pages of bugs and reports, it's refreshing to see someone as involved as you are.
