### ISSUE TITLE
[Suggestion] The Pressure Chamber mechanics and possible improvements

### ISSUE THREAD

**Issue by Axylxys** [MineMaarten/PneumaticCraft#503]
Well, i had to make a post on that one. The chamber is so frustrating i sometimes wonder if i missed something about it, but it doesn't look like it, so... let's get started.

1) The items being processed inside the chamber get picked up all the time by anything that picks up loots: item collectors, the blood magic Sigil, and probably much more. It's a quite common mechanic and many mods add such features to avoid items staying in the world needlessly, while the pressure chamber is doing exactly the opposite. That usually means sticking it in a dark corner somewhere far away, and having to click off the Sigil everytime i pass nearby. 

While the idea itself is fun (as well as seeing the items) it would be really awesome if you could add an upgrade that prevents the loots from being teleported/moved/whatever, it would make the chamber much more useable in a base rather than a big hurdle i have to hide somewhere because anyone passing by gets all the items and suddenly wonder why their inventory is full of seeds or iron.

2) About the input/output doors: my first reaction was "woah, cool !". The animation and concept is great, until i realized it doesn't really like to craft anything at a decent pace. It has a bad habit to close after a few items, blocking whatever was incoming in the pipes. I tried to bruteforce with a Mekanism pipe sending 128 items, no way. It seems like after 16 items the door will close and it's doing the cycle over and over. Speed upgrades were actually detrimental based on my quick testing, i had more items backtracking to the chest than actually making it through to the chamber.

In the end i just removed all speed upgrades so items have more time to get in, and overall it just seems like 50% of the crafting time is about items trying to make their way inside rather than actual crafting. 

That seems a bit counterproductive and i have no idea how/if it can scale to a higher production rate, it seems like an early game hurdle with no real end game QoL upgrade.

A more expensive and faster/fully automated version would be cool, or some upgrades to fill it by hand or at least have it grab entire stacks rather than a few items at a time. It would be more fun if it didn't feel like there's an airport in depth security check for every item trying to go in. :)

3) The output seems needlessly complicated as well. The name filter (the one where we can type the name of an item for exemple) doesn't "remember" its settings in the GUI, so i can't see what it was set to when i open it again. The item filter isn't big enough to cover every recipe so the only solution i found was to make one chamber per recipe (plastics all going to a single one) to avoid the headache of setting up by hand the outputs whenever i want to craft something.

Again this is fair and involving for an early game crafting session, but doesn't scale well to automated systems and stronger production potential. Not sure how this could be improved, but maybe have a way to select a recipe automatically or even another tier of chamber blocks with separate chambers. Something like, input goes to a sub-chamber, when the crafting is done they move to another one, and the output door can only select items from that second chamber. 

It's rather annoying when doing several recipes in a row and the chamber starts spitting items as soon as they enter because the filters overlap.

Overall it looks like the chamber has too many potential failures happening. It can fail if someone has an item pulling gadget, if the filter are not set properly it can disrupt the crafting entirely, items can't be inserted by hand yet all the micro-management is pushing the player to sit near the chamber, on top of the various pressure mechanics (though those aren't really hard). Hopefully that made some sense, thanks for reading !

**Comment by MineMaarten** [comment]
1)
To fix #214 I'm going to turn the entities inside the pressure chamber into custom entities, unrecognizable by any mod mechanic to pick up items. 

2)
The trick is to use something that can insert 64 items at a time, like a drone or omnidirectional hopper which has been upgraded with several speed upgrades. As this has been asked by many people still (I had to explain this far too often), I'm thinking of making the interface wait 10 ticks after the last item was sent through before closing the door. Right now it closes right after the first item has been inserted.

3)
It does remember, it just sometimes has a syncing issue where the GUI doesn't properly get updated with the textbox contents. Also something to fix.

About the suggestion of more chamber blocks, this is where your creativity comes in in my opinion ;). As pressure chamber interfaces auto-output to adjacent inventories (including other pressure chamber interfaces), you could build two pressure chambers next to each other.

I do wonder why you would ever do that, as don't have to reinsert items to process them. For example, you want to create an Empty PCB (using the pre-oil mechanics, so plant seeds). You grab a creeper plant seed and a piece of iron. Throw both into a pressure chamber (with or without interface). Provided there is enough pressure, the iron ingot will turn into compressed iron, the creeper plant seed into a piece of plastic, and both will convert right away into a PCB. All in the same pressure chamber, and if the outputting interface is properly configured it will only extract PCB's.

What I used to do in my worlds to automate pressure chambers (using AE2) is have to 2 pressure chambers: 1 to process seeds into plastic, and 1 for _everything else_. The plastic processor interface was set with a name filter set to "plastic", and the everything else filter was filtered on the specific components with the regular item filter.

**Comment by Axylxys** [comment]
Oh, i didn't know for the 64 items. I used Mekanism pipes (32 and then 128 items/tick) and they never worked properly, though that is probably because they send items very fast rather than make a huge stack and send it all at once. That's why i assumed it had a 16 items limit as i never got it to take more than that.

For the syncing issue, i never got it to show the text after closing it once, that's why i assumed it was the default behaviour. Maybe because it was in a Compact Machine (so, another dimension).

Also i didn't know about the other stuff, like the auto-output and chain crafting, that's when i wish there was more info readily available about PneumaticCraft !

As a side note, i'm not sure if it's related to the in game wiki or the pressure chamber, but it crashes and send me to desktop when i try to open the Pressure chamber link in the IGW, while other entries work fine (latest version on curse for both mods).

**Comment by MineMaarten** [comment]
>Also i didn't know about the other stuff, like the auto-output and chain crafting, that's when i wish there was more info readily available about PneumaticCraft !

Auto-output should be in In-Game Wiki. The chain crafting I hoped people would find out and spread the  world by themselves, as it would be something you could accidentally find out, or could think of trying, like "hm having to take the ingredients out and back in doesn't seem to make much sense does it, I wonder if can be done quicker" :P.

>but it crashes and send me to desktop

Even then a crashlog should be available, albeit taking a little bit more effort to grab. A 'crash-reports' folder should be in your instance folder holding the entire log of the session. Depending on what the crash log says it might be better to open a new issue for PneumaticCraft/IGW.

**Comment by Axylxys** [comment]
That must be why i missed it, i didn't have the IGW wiki installed when beginning with your mod, and when double checking before posting this, it crashed of course. I opened a new issue on the IGW side as it seems to be mainly an IGW issue. :)

It's a really fair point for the chain crafting, though many mods tend to add silly mechanics as well, so usually the whole "eh that's too dumb, there must be a better way !" thought process gets overshadowed by the usual feeling of "boring... let's find the quickest way to mass produce and automate this", especially when it's only a step into getting to more interesting machines.

There should be maybe some hints towards more "out of the box" thinking, as at first glance it just looks like some gating behind time-sinks, as many mods tend to do. PneumaticCraft is a bit of an oddity, with less reliance on tiers and heavy crafting and more on creativity, while from far away it looks just like "another tech mod". It actually took me 3 games with your mod installed to finally look into it and i was really surprised to see so many tools and gadgets rather than the 150th flavor of ore processing, farming and ressource gathering.

Though that's far from the topic now, and just my opinion after a few days. At least i will curse that Pressure Chamber a bit less from now, and maybe even appreciate it once the custom item entity improvement is out. :D

**Comment by MineMaarten** [comment]
>and i was really surprised to see so many tools and gadgets rather than the 150th flavor of ore processing, farming and ressource gathering

The biggest goal of the mod is to try to add features no other mod (I'm aware of) adds. When coming up with a feature often the question "Which feature am I missing from Vanilla and mods" is answered.

"I wish there was something that warns me when a Creeper sneaks up on me..." --> Pneumatic Helmet Entity Tracker, with an Iron Man flavor.
"Hmm ComputerCraft is quite hard to learn, and Thaumcraft golems are somewhat limited" --> Drones.

There are more of these ;).

**Comment by Axylxys** [comment]
I think such stuff should be more advertised on the mod's presentation, as it's not obvious at first glance.

Though the most awesome part is Drones for sure. I'm not a developper, coder or anything, so they're like a fun version of Turtles without the headaches and all, but more importantly they seem (so far at least) especially awesome when it comes to their behaviour on server side. 

They have about as much tick time as the average vanilla mob (!), don't suffer from the bugs/annoyance of other mods (such as Thaumcraft golem disappearing or dieing for no reason, which is what actually got me into looking for alternatives) and seem in a rather polished state with nearly infinite possibilites and fun tools on top of that (i'm totally gonna make that hidden drone to grab someone and carry them to me, lol), though i'm sure i'll find more little bugs or issues while exploring them. 

They just seem like a blessing in the Minecraft world where anything slightly complicated can bring an obnoxious amount of lag, crashes and chaos on a server. I've had stupid zombies getting stuck and lagging the whole server, minecarts bugging out, golems falling under the world or disappearing randomly, AM2 bosses slowing down the server to 2 ticks per second when they're unable to reach their target, or even some engines, tanks and pretty much any item i could think about acting up at some point, but so far drones seem almost magical in the way they're smoothly performing complicated tasks, finding their way around everything and ignoring whatever hazard around them (they can even get out from RotaryCraft jet turbine air vacuum !). I wish i was a coder to have an idea of how you managed to pull that off, lol.

About the helmet, i hope there will be a way to power it on the fly some day, it's really fun but i was disappointed to see it's unrealistic to keep it on for more than a few minutes at a time, as having to run back again and again for pressure outweights the benefits in most situations (at least to me). But maybe i'll make a dedicated suggestion thread for this. It's just hard for me to stay on-topic for some reason !

**Comment by MineMaarten** [comment]
I've implemented number 2 and fixed number 3. Number 1 will be done when closing #214 which I intend to implement really soon as well :).

**Comment by MineMaarten** [comment]
>About the helmet, i hope there will be a way to power it on the fly some day, it's really fun but i was disappointed to see it's unrealistic to keep it on for more than a few minutes at a time, as having to run back again and again for pressure outweights the benefits in most situations (at least to me). But maybe i'll make a dedicated suggestion thread for this. It's just hard for me to stay on-topic for some reason !

Well, have you ever thought about using the Aerial Interface plus a Charging Tube Module together ;), I have added the Charging Tube Module specifically for this ;).

**Comment by Axylxys** [comment]
Well, thanks for letting me know about its existence to begin with. :D So that comment on the pneumatic helmet doesn't make much sense indeed. I went through all the upgrades and the Pneumatic Helmet entry of the IGW but didn't think about checking the Tubes & Modules section, that one was well hidden, lol.
