### ISSUE TITLE
Fatal Error on game world load

### ISSUE THREAD

**Issue by donglesaur** [MineMaarten/PneumaticCraft#504]
Every time I try to load my world save, it has a fatal error and crashes, not sure why but here it is
http://pastebin.com/069cGHQV

**Comment by donglesaur** [comment]
any help or idea why ths is happening would be appreciated

**Comment by MineMaarten** [comment]
Not sure, but I'll have to fix it, it's probably related to #468 for some reason... What I do know is that it happens on chunk borders, as soon as a chunk with two machines (both on a different chunk) next to eachother load..

**Comment by MineMaarten** [comment]
wait, it's a client crash... hmm

**Comment by MineMaarten** [comment]
I think I've got it, let me know if it fixed it once the version is out :) (1.9.1).

**Comment by donglesaur** [comment]
Thank ya so much man : )!!!

**Comment by MineMaarten** [comment]
I assume that fixed it then :P

**Comment by donglesaur** [comment]
i just updated to the newest verion ya got out (1.9.1 if im not mistaken) and sadly no it's not, I can send you the world file if you want to have a better look, I think the cause may be a large elevator I have thats about 10x14 and 80 something blocks tall, andf the game cant handle loading all the elevator shafts

**Comment by donglesaur** [comment]
http://pastebin.com/bpKFqyst here's a pastebin with even moar errors, again if you need the world file let me know, anyway i can help you with this truly awesome mod, you did real good work on it and this crashing i quite unfortunate
