### ISSUE TITLE
Drone interaction with Ender IO machines: detecting slots

### ISSUE THREAD

**Issue by Axylxys** [MineMaarten/PneumaticCraft#505]
I couldn't get the drone to import properly from Ender IO machines output slots. He grabs everything inside, including the input, no matter how i set it up. I set up only one side of the machine to Import inventory from, and tried everything on the Ender IO side (disabled all other sides, output only for the side the drone will access, various combinations of everything) but the drone will still empty everything.

Tested on a Sag Mill. Meanwhile, it worked well with Mekanism smelters by filtering the output side on the machine itself.

It seems like Mekanism machines will block everything based on their own configuration, to make sure nothing can steal their input or bypass their settings, while Ender IO machines have a more loose interaction and will allow the drone to take all the items no matter how they are set, unlike the pipes or various item transports that work properly.

I just can't see how to make it work right now, as an item filter setting is unrealistic given the amount of recipes processed, the drone options allow only to specify the side of the block and not the location of the output slots (unless i missed something there ?) and the machine itself can't stop the drone from accessing all its contents. 

Edit: After trying with the latest logistics drones it works with them, though not really practical for a complicated setup. Now trying to figure why the bigger drone can't do it while the simple one can.

Edit 2: A normal drone using the logistics puzzle piece works as well, however it only takes items from a single slot at a time. For exemple, if there's a single item in output slot 1 and a whole stack in output slot 2, it will take the single item and never bother about the stack unless the first slot is empty (which never happens while the machine is running as it fills it in priority). That is with plenty of dispenser upgrades of course so not a storage issue.

**Comment by MineMaarten** [comment]
Duplicate with #502
