### ISSUE TITLE
Etching Acid recipe

### ISSUE THREAD

**Issue by JasonMcRay** [MineMaarten/PneumaticCraft#507]
After updating to PC 1.9 the Etching Acid pressure chamber recipe is gone. Well not entirely gone but the recipe output is "fire". Here is screeshot:
![2015-06-28_17 44 33](https://cloud.githubusercontent.com/assets/4236895/8397018/5e61d774-1dbd-11e5-936c-566f460fde69.png)

**Comment by MineMaarten** [comment]
Yup, I definately derped right there! This is pretty severe, so I'll release a new version ASAP
