### ISSUE TITLE
Client crash when setting the Item filter puzzle piece properties

### ISSUE THREAD

**Issue by Axylxys** [MineMaarten/PneumaticCraft#508]
Here's the log, i opened the puzzle piece, unchecked the metadata box, then pressed Esc to leave that screen, it crashed. Client side only.

http://pastebin.com/pDyCu1Tb

**Comment by MineMaarten** [comment]
That's a pretty serious bug, I wonder how it went unnoticed that long :P. It happens as soon as you click on pure text (not part of a checkbox/radio button), so for example the title of the GUI of a puzzle piece.

**Comment by Axylxys** [comment]
I can confirm that (just crashed after reading your post :D ). and yes, i remember clicking somewhere on the upper screen, that must have been on the title part.
