### ISSUE TITLE
[Suggestion] Warrior drones, about the Entity Attack puzzle piece.

### ISSUE THREAD

**Issue by Axylxys** [MineMaarten/PneumaticCraft#509]
Toying with that puzzle piece while trying to have a drone guarding my warehouse, here's what i noticed:

1) Lycanite mobs aren't considered as "mobs" for some reason. They seem to belong to a different category than mobs, creatures or players, the same category as... drones. I just can't get the drones to attack lycanite mobs without attacking each others as well, unless i specify their names in the exclusion filter. However, this doesn't go too well with renaming other drones.

I'm not sure if it's possible but a @Drone category would be awesome, and maybe even expand that with other mod creatures that don't fit @mobs or other categories. Having a sentry drone hunting the working ones seem a bit counter productive, lol.

2) The drone pathfinding during target acquisition is a bit weird. They tend to slow down and do a lot of ups and downs or left and right while flying once they "aggro" something. It takes quite some time to reach the mob and if he is moving as well, they barely can, that is with max speed upgrades. It would be cool if they could instead speed up once they target something (maybe like a speed boost for that combat mode), or...

3) ... have some kind of ranged options ! It would be plain awesome to have some combat upgrade module, adding ranged weapon, maybe even something visible like the dispenser upgrade for the charging station. Rotating machine guns, mini air pressure cannons, some vacuum bombs, there's just so much potential there with dedicated modules/puzzle pieces, maybe even ban other ones when they're in use or add pros/cons to each one. Like a drone carrying a bomb would be slower, guns could have different ranges, etc...

On a more simpler consideration, anything ranged would help alleviate the slowness of drones, while fun they're rather ineffective at catching mobs before they can do harm in the wild, even vanilla mobs (a baby zombie was totally impossible to catch for a max speed upgraded drone). That makes them rather poor sentries even if they seem like the perfect ones for that, although their damage can be rather good and they're deadly... if they can ever reach their target.

**Comment by MineMaarten** [comment]
Working on it ;) https://twitter.com/MineMaarten/status/615907338478694400

**Comment by Axylxys** [comment]
LOL that is awesome, i'm totally gonna make those as soon as they're available !
