### ISSUE TITLE
drop item of drone

### ISSUE THREAD

**Issue by marco6971** [MineMaarten/PneumaticCraft#510]
I don't know if it is volunteer or not, maybe you did it to make this more difficult.
I try to get a farm of plastic seed with drone, I have used computercraft to do program, the layout of the farm is one row for every seed, the program works properly but when the drone drop the seed this hit the ground in a different position compared to that of the drone.
It's possible to drop the item in the same x and z of the drone?

sorry for bad english

**Comment by MineMaarten** [comment]
Are you sure you configured the drone to put it in 'straight' mode (meaning the item will drop straight down from where it's dropped)?

Also, you can now right click plastic plant seeds to plant them, so instead you could use the 'right click block' piece on the soil :).
