### ISSUE TITLE
Pressure Chamber: Items are too far away from eachother, wait until the items are blown to the middle

### ISSUE THREAD

**Issue by Axylxys** [MineMaarten/PneumaticCraft#511]
I'm getting this strange message as a red Problem in my Pressure Chamber. It's a 3x3x3 chamber so, there's only one block in there, i can't see how items aren't "in the middle". Right now it's filled up with stacks of seeds that it does not process at all, despite having enough pressure.

Is that a bug or is there some item number cap or something i'm missing ? I can't seem to get it to work again, it worked for a while then got stuck in that state.

http://pasteboard.co/1AasfreN.png

**Comment by MineMaarten** [comment]
Hmm I assume the flying flowers (which have a tendency to fly away :P) make it so the pressure chamber can't compact the items together... This is annoying, but as a fix I recommend using different colors of plastic instead, and redye it to white using the (vanilla) crafting recipe. I won't fix this, as the plant system will be discarted soon and oil will fully take over.
