### ISSUE TITLE
Crash when looking up NEI recipes (v1.9.x)

### ISSUE THREAD

**Issue by xeronut** [MineMaarten/PneumaticCraft#512]
http://pastebin.com/uKWn9HGC

Occurs when I left-click or hit 'R' to look up a recipe in NEI.  Only happens with these latest two 1.9.x releases - I can revert to 1.8.x and not have the issue.

Forge 1291
CodeChickenCore 1.0.4.35
NEI 1.0.4.95
PneumaticCraft 1.9.1-86

All other mods listen in crash.  Thanks for your time!

**Comment by MineMaarten** [comment]
hmmm it's probably because I built PneumaticCraft to a too old version of Forge..

**Comment by MineMaarten** [comment]
orr.....you have an old version? I just updated to a new version and it still seems to work. Could you try with the latest/recommended version of forge?

**Comment by MineMaarten** [comment]
Going to assume the outdated version of forge.

**Comment by xeronut** [comment]
Aye, outdated Forge (1291).  I updated to 1448 and issue resolves.
