### ISSUE TITLE
Client crash with pneumatic helmet

### ISSUE THREAD

**Issue by Axylxys** [MineMaarten/PneumaticCraft#513]
I just tried the aerial interface with the charging module to charge my helmet. It worked, so i went to a charging station and added a few upgrades (block tracker, range, speed). After equiping the helmet again it crashes as soon as it reaches the end of initialization process. With the crash log i guess it's because of a Better Storage crate that it can't read properly.

http://pastebin.com/e4s6AWQ5

**Comment by MineMaarten** [comment]
It appears to be the case yes... I'll add some more checks for this so it will simply ignore inventories like this.

**Comment by MineMaarten** [comment]
Fixed, but after looking at where it crashed I do think it's a weird corner case with Better Storage. But meh :P
