### ISSUE TITLE
Advanced Pressure Tube high update time with Charging Module

### ISSUE THREAD

**Issue by Axylxys** [MineMaarten/PneumaticCraft#515]
After the daily Opis check on the server i noticed an Advanced pressure tube taking the top spot on the list, timing at 543.074μs. I have a lot of those and it's the only one showing that behaviour, it's also more than 5 times the average tile entity update time (most are between 15 and 85) so there's clearly something wrong.

Opis pointed me towards the tube section supporting the Charging Module below the Aerial Interface i used as a test setup. However, it's inactive: i'm using it only to charge the helmet when i use it, and i don't have it on currently. Maybe it doesn't like the fact i'm trying to send pressure in there while i have no item to receive it.

Here's the setup:

http://pasteboard.co/1FinDgb3.png

The tube is linked to my main pressure network, a single flux compressor powering all my warehouse so the tubes run everywhere. The interface is at the end of a small branch right near the compressor, and the single part showing unusual update time is the one with the module, where my cursor is.

I'm also running one version behind the latest one (i miss the last patch from 2 or 3 days ago) in case it matters, though i don't think there was anything about that in the patch note.

The Opis results for PneumaticCraft parts:

http://pasteboard.co/1FiBVtTK.png

**Comment by MineMaarten** [comment]
(first of all, sorry for the delay, I 'had' to attend Minecon :P)

I can only assume this is caused by the Charging Module. If it was on the side (meaning charging inventory slots) I would have understood why it would use more than average, as it's going through the entire player inventory every tick to see if it's chargeable. For just 4 armor slots it shouldn't be a big deal.

I'll look into it anyway.

**Comment by Axylxys** [comment]
Glad to see you're back ! I think it's just running a loop at some point while doing the checks. For the record if it helps, i'm wearing full bedrock armor (RotaryCraft) so nothing at all to charge.
