### ISSUE TITLE
[enhancement] Aerial interface energy transfer

### ISSUE THREAD

**Issue by SmokeyTheBandicoot** [MineMaarten/PneumaticCraft#516]
If the aerial interface can pipe in/out items from a player's inventory why shouldn't it inject RF to remotely charge RF-powered armor and items in player's inventory?

**Comment by MineMaarten** [comment]
Not a bug that it can't atm, but it does sound like a nice feature :). I thought about this one but never wrote it down. Thanks for doing so :P
