### ISSUE TITLE
Multifarm not accepting Fire Flower or Ender Plant Electron Tubes

### ISSUE THREAD

**Issue by urbndude** [MineMaarten/PneumaticCraft#517]
Whenever I try to insert an intricate circuit board with a fire flower or ender plant electron tube, the forestry multiform doesn't accept it and it is dropped onto the ground.  It s only with these two specific tubes.  It doesn't matter if its just 1 tube in the circuit board or all 4, it still won't accept it.  I originally noticed it with Forestry 3.5.6.15.  I also tried the 3.6.2.19 version of forestry and it had the same issue. 

Using PneumaticCraft 1.9.1-86

**Comment by MrKunji** [comment]
In the most recent versions, plants are being deprecated in favor of oil.

**Comment by MineMaarten** [comment]
MrKunji is right. Duplicate with https://github.com/MineMaarten/PneumaticCraft/issues/456 also
See https://imgur.com/a/gEysk for the new system :)
