### ISSUE TITLE
A question about the latest updates

### ISSUE THREAD

**Issue by xJon** [MineMaarten/PneumaticCraft#518]
After I updated my client with the latest version of PneumaticCraft I got this message on chat:
![image](https://cloud.githubusercontent.com/assets/8945347/8510530/b7f71498-22f4-11e5-9036-299748b05ca9.png)
Also I checked my config and I saw that the generation of plants is set to 0, and the generation of "oil per chunk" is set to 15.0.
I wanted to ask, what is this "oil", and how it replaces the types of plants.
Thanks!

**Comment by MrKunji** [comment]
You can check In-game Wiki for information ;)
But how it goes: get oil, create a Refinery (different heat levels breaks the oil in more stuff, there's a NEI recipes button in the Refinery GUI), when you get Liquid Plastic, put it in a Plastic Mixer to cool and/or dye it.

**Comment by xJon** [comment]
@MrKunji And if I have Buildcraft installed?

**Comment by MrKunji** [comment]
Both types should be compatible, I guess.

**Comment by xJon** [comment]
@MrKunji They don't override themselves?

**Comment by MrKunji** [comment]
I play only with BC oil enabled, I can't confirm rigth now.

**Comment by MineMaarten** [comment]
PneumaticCraft oil is BC oil compatible. if it finds BC's oil it will use it. It will generate with both BC's mechanic (oil spouts) and mine (oil lakes) though, in new chunks. You can leave that or disable either one if you want to.
 For more info about the changing of the system and the reason behind it:

https://imgur.com/a/gEysk

**Comment by xJon** [comment]
@MineMaarten So I guess I'll disable it and keep the BC type. Personally I like the change. :)
Thanks!
