### ISSUE TITLE
PneumaticCraft helm durability issue

### ISSUE THREAD

**Issue by JasonMcRay** [MineMaarten/PneumaticCraft#519]
When I craft PC Helm with Empty Canisters I get a helm with 0 durability. When i get hit once, the helmet breaks. Tried to fill it with Pressure first. Same problem.

When I craft PC Helm with Full Canisters, it works properly.

More info on InfiTech issue tracker: https://github.com/JasonMcRay/InfiTech-1.7/issues/274

**Comment by MineMaarten** [comment]
oh! interesting! This is a very old issue that I never managed to track down! This might be the problem (as I never crafted it myself to test it, just spawning from creative)! Thanks! I'll do some tests!

**Comment by MineMaarten** [comment]
TOTALLY CONFIRMED! TY! :O
