### ISSUE TITLE
Aerial Interface + Dispenser Upgrade Auto-Feed not working

### ISSUE THREAD

**Issue by Xiaminou** [MineMaarten/PneumaticCraft#520]
I have tried everything I can think of to insert items in the Aeriel Interface when it has the Dispenser Upgrade but it's just not accepting any food. I have tried every side, different foods, different method of insertion. My hunger was 0 the whole time.
Everything else works fine, I can import/export items without the Dispenser Upgrade, I can import/export liquid XP with it.
I don't know if this is a bug or there is something else to do that is not mentioned in the IGW.

**Comment by MineMaarten** [comment]
'different methods of insertion', have you tried an ordinary Hopper? As you need to supply the items one by one, as else it would 'overfill' your hunger, which the mechanic doesn't allow.

**Comment by Xiaminou** [comment]
yes I have, I have tried translocator set to only ever export 1, I have tried export bus without any upgrades etc...

**Comment by MineMaarten** [comment]
Ok.. I'll try to reproduce it and see if it somehow broke out of nowhere (Aerial Interface hasn't been touched in a while)

**Comment by Xiaminou** [comment]
Yeah, I haven't tried it with only pneumaticcraft. However I do have 249 mods in my modpack so it's possible that one of them is somehow conflicting.

**Comment by MineMaarten** [comment]
possibly... I've just tested it with the latest version and it works fine :|.... I'm sorry..

**Comment by MineMaarten** [comment]
Any mod that tinkers with hunger? like hunger overhaul?

**Comment by Xiaminou** [comment]
Only applecore to display hunger/staturation restored.

**Comment by Xiaminou** [comment]
Okay after testing in SSP (which I should have done in the first place), It works.

**Comment by MineMaarten** [comment]
oh! I should do some SMP testing then...

**Comment by Xiaminou** [comment]
Well it might be something with Cauldron, who knows.

**Comment by Xiaminou** [comment]
Okay, so I moved the setup to another place, and for some reason it works. Sorry for wasting your time.

**Comment by MineMaarten** [comment]
No, every side apart from the top and bottom works the same way...

**Comment by MineMaarten** [comment]
Just tested on SMP and works fine as well..

**Comment by Xiaminou** [comment]
Well I don't know I must have derped somthing, maybe a hidden redstone signal, don't know.

**Comment by MineMaarten** [comment]
I can only think of not enough pressure, as redstone doesn't have influence ;)

**Comment by Xiaminou** [comment]
Well there was enough pressure since it worked for liquid XP

**Comment by MineMaarten** [comment]
hmm... anyway, let me know when it occurs again ;), hopefully in a reproduceable way :|

**Comment by Xiaminou** [comment]
Small update, it stops working after every server restart, I have to take the Dispenser Upgrade out and put it back in to make it work again. Might have something to do with why it didn't work in the first place.

**Comment by MineMaarten** [comment]
I've tested this on both SSP and SMP, but it seems to work fine still for me :|. After looking at the code it also looks there there shouldn't be a reason why it would stop working (the checking for whether or not there's a dispenser upgrade doesn't happen on world load, but on interval).
