### ISSUE TITLE
Elevator crashing client on logging in

### ISSUE THREAD

**Issue by NoireMann** [MineMaarten/PneumaticCraft#521]
Sup!

I have a very disgusting trouble.

The point is that client is crashing on logging in a server. 
It happens when newbies are logging at the first time and they can`t even start the game, because server is terminating the connection.
I have some elevators near the spawn point, so, crashlog says it is directly related to the elevator.
So, i think it might be related to some elevator problems. I am using multiblock evelator, btw.

Client-side crashlog is going here: http://pastebin.com/bXEX70Qg

I am using the latest version of PneumaticC (1.9.1) 

Thank you.

**Comment by MineMaarten** [comment]
I _think_ I've fixed it.
