### ISSUE TITLE
Crash with Reika's updated mods

### ISSUE THREAD

**Issue by huntert98** [MineMaarten/PneumaticCraft#528]
http://pastebin.com/t0GWS0uA

Crashes with the updated versions of RotaryCraft, ReactorCraft, etc.

**Comment by Too-DAMN-Much** [comment]
having this as well.

**Comment by MineMaarten** [comment]
@ReikaKalseki any idea? I'd assume it has to do with the recent block tracking blacklist. I'd love to look into the commit(s) about that myself, however it's a PITA to find due to them being named "Update".

**Comment by huntert98** [comment]
@MineMaarten It's his lastest downloads on his page, v7a

**Comment by SJ1133** [comment]
Similar Crash: http://pastebin.com/iKEjzTVu

**Comment by ReikaKalseki** [comment]
I do not ship the PnC API. At all. Try updating PneumaticCraft. If it still fails to find the class, then it is a classloading error.

**Comment by SilverScreamBr** [comment]
@ReikaKalseki crash persist with lastest version of both mods

**Comment by MineMaarten** [comment]
@ReikaKalseki I'm not pointing any finger here. In fact, I'm thinking the chance is higher it's on my part than yours. However, I do like to see what has changed since, in your mod for it to break. Which due to the commit behaviour is not feasible. Hence my question.

**Comment by ReikaKalseki** [comment]
I started referencing your API in v7 as per #491. However, I do not ship your API.

I have seen this behavior before, where referencing another mod's interface suddenly made even the owner mod unable to reference the class unless I also shipped it, with Minechem's IDecomposerControl.

**Comment by ReikaKalseki** [comment]
I tested myself. Adding the API to my own jar works. Can I ship the PnC API safely until I work out a better fix, or does it change frequently?

**Comment by MineMaarten** [comment]
Sure, if I properly change the version in the @API it _should_ work fine if I add things. and I add things quite often..

**Comment by ReikaKalseki** [comment]
Adding new classes should be fine. It is only incompatible changes that will break.

**Comment by SilverScreamBr** [comment]
@ReikaKalseki i'm have a new crash before updating your mod to 7b http://paste.ee/p/gS6oR

**Comment by ReikaKalseki** [comment]
OK, shipping the API is not working either because of jar signing issues.

I am going to remove the interface implementation. MineMaarten, could you please provide some sort of alternative to making a block implement IBlockTrackEntry for the purpose of blacklisting?

**Comment by accessdenied0** [comment]
Dear @ReikaKalseki,

It is possible to fix this temporally just deleting the specific API-parts in DragonAPI_7b? Or should I just waiting for your new release?

access_denied

**Comment by SJ1133** [comment]
@accessdenied0  Did you delete it in version 7b? cause its not working for me that way

**Comment by accessdenied0** [comment]
@SJ1133,

Yes, I opened the "DragonAPI 1.7.10 V7b.jar" and just removed the "pneumaticCraft\" dictionary completely.

It works fine in my case,

access_denied

**Comment by KaneHart** [comment]
@accessdenied0 Sadly using DragonAPI1.7.10V7b.jar with the API Inside or removing it causes it to still fail for me.

**Comment by MineMaarten** [comment]
"MineMaarten, could you please provide some sort of alternative to making a block implement IBlockTrackEntry for the purpose of blacklisting"

No, the event should just work fine. Implementing IBlockTrackEntry and always returning false on shouldTrackWithThisEntry doesn't have an effect, so I'd suggest removing it. The helmet can track multiple IBlockTrackEntries, with the inventory one being activated (unless you cancel it with the event).

**Comment by MineMaarten** [comment]
Could someone try reproducing it with -Dlegacy.debugClassLoading=true in the VM arguments?

**Comment by wujekbrezniew** [comment]
You're welcome http://pastebin.com/3M0mTFq0 I only delete MultiMC annotations.

**Comment by ReikaKalseki** [comment]
> No, the event should just work fine. Implementing IBlockTrackEntry and always returning false on shouldTrackWithThisEntry doesn't have an effect, so I'd suggest removing it.

**Comment by accessdenied0** [comment]
@KaneHart, 

I use personally Rotarycraft, Electricraft, ExpandedRedstone, Legacycraft and of course DragonAPI.
But I don't think the Pneumaticcraft API (or the interface) is in any other mod of his. Do you still get the same crash-report, maybe it is not the same...

access_denied

**Comment by KaneHart** [comment]
@accessdenied0 Sorry forgot to update this. It was cloudflare catching screwing up my updater. It actually did work I had let MineMaarten know on IRC but forgot to update this.

**Comment by MineMaarten** [comment]
@ReikaKalseki  Not yet no.

Also, I'm seeing this in wujekbrezniew's log:
>[20:13:53] [Client thread/ERROR] [LaunchWrapper]: Exception encountered attempting classloading of %s
java.lang.SecurityException: class "pneumaticCraft.api.recipe.IPressureChamberRecipe"'s signer information does not match signer information of other classes in the same package

I must admit my eyes aren't trained on ASM and classloading, but might that have something to do with it? Later in the log it hardcrashes on classloading that particular class.

I'll add that feature to be able to blacklist block track entries in general (probably another Event), not a topic of this issue though. That said I really think this is not my issue here. I'd suggest continuing this on Reika's issue tracker.

**Comment by ReikaKalseki** [comment]
The crash is ultimately caused by classloading stupidity, yes. If it is anyone's fault, it is FML, and even they may not be at fault here.
