### ISSUE TITLE
Repair the third_party_enabling

### ISSUE THREAD

**Issue by Tsyklop** [MineMaarten/PneumaticCraft#530]
I disabled support IGW: B: IGWMod = false

But I still wrote it:

![2015-07-08_16 44 48](https://cloud.githubusercontent.com/assets/6783568/8571647/cc6a347a-2590-11e5-85a1-40b3c6312039.png)

Repair Please!

**Comment by MineMaarten** [comment]
You can disable this in the IGWMod.cfg file instead.

**Comment by Tsyklop** [comment]
oh. Thanks!
