### ISSUE TITLE
Desync with Elevators on SSP when changing the config option for height per base

### ISSUE THREAD

**Issue by MineMaarten** [MineMaarten/PneumaticCraft#531]
Apparently displays wrong info on the status GUI.

**Comment by Fayti1703** [comment]
Can confirm:
![2015-07-09_07 14 52](https://cloud.githubusercontent.com/assets/5366784/8588429/aff46d4a-260a-11e5-9d78-fe7e89ceabcc.png)
![2015-07-09_07 14 41](https://cloud.githubusercontent.com/assets/5366784/8588430/b017af12-260a-11e5-8390-5dd2e4d93841.png)

I:"Height per Elevator Base"=8
