### ISSUE TITLE
[Suggestion] Minimum Temperature of -273,15 °C or 0K

### ISSUE THREAD

**Issue by beepbeat** [MineMaarten/PneumaticCraft#532]
MAybe you can add a Minum Temperature for everything that can be cooled down to respect absoulute Zero, until Scientist s prove, that there is no absolute Zero.

**Comment by MineMaarten** [comment]
Yeah, I was thinking about that yes ;). Slower than no movement molecules can't go can they ;)

**Comment by belathus** [comment]
... maybe they vibrate in the opposite direction? ... that doesn't really work...

The only way to get below absolute zero is the vortex tube, correct? I wonder if using Euler's Turbine Equation would still allow it to violate absolute zero.
