### ISSUE TITLE
Add static Minigun turret + item Minigun

### ISSUE THREAD

**Issue by MineMaarten** [MineMaarten/PneumaticCraft#533]
As the ammo and minigun model is there already, why not also add these gadgets ;)

**Comment by Axylxys** [comment]
As an adept of defensive systems i can only support that idea !

**Comment by MineMaarten** [comment]
How is the drone minigun working? Can it keep up with baby zombies? I didn't actually test that ;P

**Comment by Axylxys** [comment]
Planning to test the minigun extensively as soon as i get enough time for that (maybe later today), i'm quite curious to see how it performs regarding update time (that one is usually tricky with all automated defense systems), pathing and tracking, range and overall reliability vs several type of mobs, i'll make a detailled report. :)

**Comment by Axylxys** [comment]
Ok i really wanted to see how it works lol, so i did a bit of testing mainly in a solo game.
It took me a little while to find how to mount the minigun, and that it actually takes a sword to calculate damage output (that's great though !).

Overall it looks very positive, the drone is doing well to acquire new targets and destroy them. I sometimes got it to hang up a bit, mainly when i spawned a mob behind me (so i was standing between the drone and the target), however it wasn't consistant enough to know if it's an intended mechanic and the player character can block line of sight. Either way i was very pleased to see it's not real projectile and the drone can't do collateral damage. My girlfriend will probably thank you for that, as she's usually not too happy when she dies on a lost grenade/missile/bullet spam/bomb/arrow from my various weapon systems while juste passing by. :D 

However the issue i reported before seems to remain: other drones. So far the only reliable way i found is to not rename them at all and just make an exclusive filter on "Drone", that's a bit annoying as the name/color helps a lot to sort them out, especially as it also gets reported on Opis so with a rename, it's easy to track which drone is doing what. It defeats a bit the point of renaming the drones and a @drone filter would really be handy for setting that up.

I'm also a bit scared of the various unexpected targets the drone could find on a server environement, as the categories don't seem to take into account mods very well. Major offender is Lycanite mobs here, the @mobs category doesn't take them into account, and probably some other mods mobs as well (i've been too lazy so far to try to spawn all types of mobs i can). So doing a filter to only target mobs and animals yields poor results, while targeting all and excluding players and specific entities can quickly turn into something overly complicated.

A chunkloader upgrade would also go along really well with such drones as they can chase a mob outside and i'm not sure how they'll behave once they reach an unloaded chunk.

Now to come back on topic, i think the turret could use a higher cap for range increase upgrade (16 blocks isn't that much for a static turret), also i hope there will be a way to increase its damage without the sword pickup, as the base damage is really quite low. :)

**Comment by MineMaarten** [comment]
>and that it actually takes a sword to calculate damage output (that's great though !)

That's an unexpected side-effect I actually like as well. It makes sense now I think about it.

About the @drone filter, it's a different topic, but I guess I can add it, it's simple enough to do.

About other unexpected targets, it's hard to add filters for all of them. The filter should work fairly well though. @mob checks in code for the entity class that can target other entities, which should cover all aggressive mobs. @animal should cover the ones that can be bred (IIRC), which covers most passive mobs. @living covers everything that has health (so also 'animals' and 'mobs').

About the chunk loader upgrade, it's on my todo (I'm fairly sure it's on this issue tracker already). I haven't gotten around to do it. It's pretty involving to add.

About the static turret/item turret, I'll see about the damage. I agree it could be a bit higher. On the other hand a low base damage induces people to use potion effects like instant harming, which is pretty effective.

**Comment by Axylxys** [comment]
I suspected the sword trick wasn't intented, it looked too weird to be planned. :D 

That said, the base damage is too low to really be effective save for maybe early game (unless there's another legitimate way to have it stronger than 1dmg per shot). The potion ammo look fun but not terribly practical: to effectively protect an area, it means quite a few drones/turrets and they're likely to have many targets. Having to make a potion factory to power them looks a bit overkill when in the end, it's more of a "flavor" feature rather than real end game stuff.

There are plenty of ways to automate mob killing in some common mods or even better, to prevent them to spawn, i don't think it should become overly complicated to have the turrets do their job. Using them already implies to have progressed enough through the mod, as well as having quite a few materials, keeping up with the air pressure generation and most likely an automated ammo factory behind.

A @Drone filter will probably allows to overcome most of the targeting issues also. :)

**Comment by MineMaarten** [comment]
Agreed with the fact that potion ammo should be considered extra and not the main usage.

A nice thing about the automated ammo factory btw, Gun Ammo first was a Pressure Chamber recipe. I've changed it to a shapeless crafting recipe to allow drones to craft Gun Ammo themselves using the Craft command :D. So the only thing that would require to be automated is making compressed iron, gold and gunpowder available for the drone.

**Comment by Axylxys** [comment]
Haha i thought about that, when i saw all the ammo types my first thought was "Nooooo not the pressure chamber !!" as it reminded me about the various plastic recipes, and i could foresee the hell of processing thousands of ammos in the chambers.

I'm glad you chose that shapeless recipe, indeed, and it's quite a balanced one (easy enough by mid game, once such devices become useable). :D
