### ISSUE TITLE
Pressure Chamber breaking at chunk border

### ISSUE THREAD

**Issue by 016Nojr** [MineMaarten/PneumaticCraft#535]
If the pressure chamber is in a chunk border, one of the sides gets "broken" when entering a singleplayer world. I can break those blocks and the chamber will still function as normal

Using Direwolf20 1.5.0 with some additions
Pneumaticcraft 1.8.2-84

**Comment by MineMaarten** [comment]
I can reproduce this. However, this only seems to be visual. Breaking a 'broken' block of the side breaks the pressure chamber properly, and so does it when a 'non broken' block is broken. Also simply relogging fixes it.

Or if this what you meant by 'still function as normal',  that you can still break it as normal?

**Comment by MineMaarten** [comment]
I've fixed the visual part of the bug, I just need to know now if it was more than just visual?

**Comment by MineMaarten** [comment]
So let me know if indeed it was only a visual bug. If not , updating to 1.9.3 (just released) will _not_ solve your issue, it will just hide it (as the visual part is fixed).

**Comment by 016Nojr** [comment]
I could break the "broken" blocks, and it would still open the interface. I did not test if i could make stuff in it tho :/

**Comment by MineMaarten** [comment]
oh :|, then it's not only visual...
