### ISSUE TITLE
the problem of language

### ISSUE THREAD

**Issue by anar4732** [MineMaarten/PneumaticCraft#536]
your mode "Turkish" do you intend to translate into a language? 

------------------------------------------------------------------------------------------

"thaumcraft" mode is not installed "when thaumcraft upgrade" should be

------------------------------------------------------------------------------------------

monitoring the temperature of the blocks or block eklene some kind of tool knows "temperature meter"

------------------------------------------------------------------------------------------

(this text is translated into the English language by a robot)

**Comment by MineMaarten** [comment]
It's hard to make up what you're trying to say. However, I'll try.

>your mode "Turkish" do you intend to translate into a language?

I know Turkish. I myself am incapable of making a Turkish translation. I'm fully dependent on a Turkish person who also is capable of English to create a translation. I would accept a pull request on that if this happens. This has been done for other languages already.

>"thaumcraft" mode is not installed "when thaumcraft upgrade" should be
monitoring the temperature of the blocks or block eklene some kind of tool knows "temperature meter"

I'm not sure what you mean here, sorry:(

**Comment by anar4732** [comment]
firstly, thanks for your response.
I'll try to write more understandable

-------------------------------------------------------------------------------------------------

you need to add an item to see the temperature of the blocks.(°C)

--------------------------------------------------------------------------------------------------

if the Turkish translation if I do:
the mod "has been translated into Turkish by Anar, site : www.4732f.tk"
could you add?

---------------------------------------------------------------------------------------------------

(this text is translated into the English language by a robot)

**Comment by MineMaarten** [comment]
>you need to add an item to see the temperature of the blocks.(°C)

Good idea. I relied on people having WAILA too much. I won't make it a new item though, I'll simply add it to the Manometer, as that's a measurement item already.

>if the Turkish translation if I do:

If you're saying "If I do the Turkish translation could you add:" I want to see that seeing the problems you have with English it might not be smart to let you do the translation, sorry.

>"thaumcraft" mode is not installed "when thaumcraft upgrade" should be

Oh and I think I know what you mean with this, is it by a chance "The Thaumcraft upgrade can be found in creative even though Thaumcraft is not installed"? If that's the case, that's fixed in latest version already.

**Comment by anar4732** [comment]
my English writing is so bad.... (as you've already noticed)
but I read English very well, and I know how to twirl it into Turkish.
if you need translation if you can tell me...
also note that it has been translated by a robot of this type.

----------------------------------------------------------------------------------------------------

I think the "barometer"to measure it would be ridiculous for the work of...
instead, the "barometer"remove
"multimeter"add both to measure the temperature of the air and that it might make much sense.

----------------------------------------------------------------------------------------------

thanks for your interest....
