### ISSUE TITLE
Elevator not proper working since last update

### ISSUE THREAD

**Issue by TheMrCaveman** [MineMaarten/PneumaticCraft#537]
Elevators behave weird after last update.
You get up with elevator for a while and then you get stuck between wall and elevator. 
https://youtu.be/6AYgz5HhOW4

**Comment by MineMaarten** [comment]
I was afraid of this happening :|. I've added tweaks to the Elevator to make it much more reliable when the server is lagging. Desyncs occured at that moment. This did have the added risk other occasions would break. I'll look into it :(
