### ISSUE TITLE
Aerial interface suggestion (add feeding options)

### ISSUE THREAD

**Issue by phrostt** [MineMaarten/PneumaticCraft#542]
A suggestion. When I first built it I thought that it was so cool that I stopped carrying food with me. Problem is if you have food that gives you 2 hunger bars, but you are missing 1 hunger bar it wont feed you. So because of that, if you are missing hearts, your regen will never kick in due to hunger which will not get replenished until you get more hungry.

My suggestion is make it feed you the food if you are missing hearts. You could do this by changing the behavior of the security upgrade, since the current security upgrade is not very useful.

**Comment by MineMaarten** [comment]
Please split up bugs/suggestions (no matter how small they are). This prevents me from closing issues when only one of multiple points are implemented, and therefore the rest of your bug reports/suggestions are discarded. For this time I'll do it for you

**Comment by MineMaarten** [comment]
About the suggestion, you want it to behave it that way. I'm not sure if everyone does though. Therefore I think the best way is to add an extra tab when you have the feeding upgrade in there, which allows you to customize when to feed. As soon as you don't have max food level, as soon as you don't have max health, and such.

**Comment by phrostt** [comment]
Awesome and thank you!
Ill keep in mind about the split.
