### ISSUE TITLE
[Crash] PneumaticCraft: Oil lakes crash upon world load

### ISSUE THREAD

**Issue by tntblockman** [MineMaarten/PneumaticCraft#545]
Hi MineMaarten,
I keep getting a world load crash, something to do with the generating of oil lakes.  But I'm sure you can have a much better insight into the cause of the issue. The only other oil in this custom pack I can think of, would be the Gregtech oil . But other than that, don't think there are any other mods which add oil.  

Quick fix #1 is to rollback to PneumaticCraft version 1.7.10-1.6-73.
Quick fix #2 is to change config option from "oil_generation_chance=15.0" to "oil_generation_chance=0".
Quick fix #3 remove PneumaticCraft.

PneumaticCraft versions: from "1.7.10-1.9.0-85" to  "1.7.10-1.9.4-91"
Fastcraft is installed
crash log: http://pastebin.com/RYvd5PnS
Modlist: http://pastebin.com/U3yZJzvx

**Comment by tntblockman** [comment]
If I disable oil lakes (oil_generation_chance=0) in the config, can PneumaticCraft still use Gregtech oil?

**Comment by MineMaarten** [comment]
if Gregtech oil is 'liquid-dictionaried' with BC oil, then yes. I don't know much of GT.

**Comment by MineMaarten** [comment]
I can only imagine that GregTech is forcing the block associated with its oil fluid to null, causing my worldgen to get confused about which block to use. I'll hotfix and release this. I'd like to hear if this indeed was the fix.

**Comment by tntblockman** [comment]
Thanks for looking into issue.  Tried hotfix 1.7.10-1.9.4-92 with a fresh test world, but it's crashing on world load.
crash log: http://pastebin.com/UNDhuUL4

**Comment by MineMaarten** [comment]
And 1.9.6? I did I fix of my fix >.>
http://minecraft.curseforge.com/mc-mods/224125-pneumaticcraft/files/2247690

**Comment by tntblockman** [comment]
Yes sorry my derp in not using the correct version would help.  Yeah can confirm 1.7.10-1.9.6-93 fixes the issue.   Many thanks again for fixing this issue and so damn quick too. :)

**Comment by MineMaarten** [comment]
awesome :), sorry for the inconvience :P
