### ISSUE TITLE
Feather falling interacts wierdly with higher speed elevators - requires debouncing

### ISSUE THREAD

**Issue by usafphoenix** [MineMaarten/PneumaticCraft#546]
While not a game-breaking bug or anything that causes a crashed client, visual stuttering and glitching can occur when feather falling (or similar enchant) is applied with a elevator (tested with 4 or 5 speed upgrades which,  IMO makes a realistic speed descent/ascent--- player will fall/bounce about/stutter (having a hard time explaining the visual effect it has, sorry!)
But---is it possible to, while the player is on the elevator blocks, remove or temporarily disable player effect:featherfalling?

**Comment by usafphoenix** [comment]
while, i also realize, doing so could potentially cause issue if a person is riding up an elevator and fall off it...and their feather falling is disabled and not returned after they are no longer on the block---could end in a lot of suicide reports of Steve's who had a really bad mondays in the mines of minecraftia.

**Comment by usafphoenix** [comment]
a potential way to fix this is, when the function to lower the elevator is called, determine for, within the first second or two if the player hitbox is not within a certain range of elevator lift hitbox (the player is in freefall, and will bounce once they catch up to lift), if so----reduce the speed that the lift is lowering. this has the negative effect of reducing efficiency while lowering, but still enables them to go to higher levels quicker if dealing with player enchants or player-fall-speed too complex or prone to bugs.

**Comment by usafphoenix** [comment]
i have an idea of how it could be fixed. feather falling works by changing the speed at which the player falls while wearing the boots, right? so could the elevator blocks apply a similar effect to the player to set the fall rate according to how fast the elevator is moving? would that maybe work? or am i dumb? lol

**Comment by MineMaarten** [comment]
I didn't know about this glitch. However, I'm fairly sure I've fixed it with the fix of #537 :). Try again in 1.9.7, which should be released soon (hopefully in a few hours). Let me know afterwards if this indeed fixed it :)

**Comment by MineMaarten** [comment]
It went up yesterday, should have been fixed with this ;) http://minecraft.curseforge.com/mc-mods/224125-pneumaticcraft/files/2247882

Let me know
