### ISSUE TITLE
Pressure Chamber Interface - can't extract items

### ISSUE THREAD

**Issue by iTpyn** [MineMaarten/PneumaticCraft#553]
I've updated PneumaticCraft from build 84 to build 95 and noticed that i can't extract items from the interface. Pressure Chamber does its job, items get to the interface, hatch on the output side (which is connected to the tube) opens and thats it. Items get stuck.
Quick test showed that build 85 is the last version not affected by this issue, and the first version affected is 1.9.1-86 (the one with the new pressure chamber interface texture).

**Comment by iTpyn** [comment]
Type of the tube doesnt matter - same thing happens with BC pipes, Thermal Dynamics ducts, EnderIO conduits, etc.

**Comment by Forecaster** [comment]
I found that the interface would automatically output items into a buildcraft pipe attached to it.

**Comment by iTpyn** [comment]
Thanks you've corrected me.
It actually does automatically output items to the BC Pipes and to the Extra Utilities Transfer Nodes.
But it still doesnt work with Thermal Dynamics Ducts (with or without servo installed). 
![2015-07-19_11 46 16](https://cloud.githubusercontent.com/assets/10965662/8765260/0e3a2fa2-2e0d-11e5-81c4-052b849705d6.png)
It doesnt work with EnderIO Conduits either (no matter if the conduit is set to auto extract items or not).

**Comment by Forecaster** [comment]
Have you tried putting the chest next to the interface?

**Comment by iTpyn** [comment]
Yes, it can output directly to the chest, what diffence it makes? The problem is that the interface worked fine with ducts and conduits until 1.9.1-86, now it doesn't.
Outputting to the chest and using the duct/conduit to extract items from it is just a workaround.

**Comment by MineMaarten** [comment]
Yes, when the outputting floodgate is open, it should allow for other means (like ducts) to pump items out. The fact that BC pipes work is because I added support for it to automatically eject into these pipes.

**Comment by MineMaarten** [comment]
I am derp >.>. Note here that the side that's allowed to be extracted should be the same as the one used to insert items... https://github.com/MineMaarten/PneumaticCraft/commit/16d56dacabddfdac450962c2ff00497a4db00bd5#diff-15ac281b237a3eff4b16c4c282296b05R436

Yes, that's a derp that will be fixed in upcoming version.
