### ISSUE TITLE
Omnidirectional hopper speed upgrades

### ISSUE THREAD

**Issue by pyure** [MineMaarten/PneumaticCraft#555]
The 3rd and 5th speed upgrade (specifically) do not seem to confer any additional benefits to an omnidirectional hopper.  Possible bug?

0: 2.5 items/s
1: 5.0 items/s
2: 10.0 items/s   
3: 10.0 items/s ***
4: 20 items/s
5: 20 items/s   ***
6: 2 items/tick
7: 4 items/tick
8: 8 items/tick
9: 16 items/tick
10: 32 items/tick
11: 64 items/tick
12: 128 items/tick
13: 256 items/tick

**Comment by MineMaarten** [comment]
Sounds like a derp on integer division :P. I'll look into it, tnx
