### ISSUE TITLE
Have logistics frames only be visible while holding a frame or configurator

### ISSUE THREAD

**Issue by Forecaster** [MineMaarten/PneumaticCraft#556]
Cause glowing neon frames on your machines aren't always aesthetically appropriate.

**Comment by MineMaarten** [comment]
Yes, I'd definately want to add some way of hiding the frames. Personally I like the aesthetics of them though, so I want to see about something that doesn't show them only while you're configuring... I'll come up with something..

**Comment by Forecaster** [comment]
You could have it so they're visible by default, but a player could shift + right click air or something like that with a configurator to toggle it for himself?

And if they're hidden they'll appear when you're holding a frame or configurator, maybe partially transparent?

**Comment by MineMaarten** [comment]
Well, with this you do need to consider multiplayer. Other people should see your build in a way you intend it. So having it 'local' by clicking your configurator wouldn't work. Also can't make it global as it will toggle all frames on the server ;)

**Comment by Forecaster** [comment]
Well, they're not something I'd want to have visible all the time.

**Comment by MineMaarten** [comment]
I can understand that, but I want them to be visible unless you explicitly tell them not to.
