### ISSUE TITLE
Pneumaticcraft Pneumatic Door "Camouflage" not working with Chisel2 Blocks

### ISSUE THREAD

**Issue by JasonMcRay** [MineMaarten/PneumaticCraft#562]
The UI of the pneumatic door from Pneumaticcraft has a place to put a block so the operating mechanism can be disguised. It works perfectly with every block tested EXCEPT Chisel2 blocks which have no effect. Chisel2 blocks used to camouflage the mechanism properly, but stopped working a couple revisions back.

Tested with: 1.9.3-90

**Comment by MineMaarten** [comment]
Hmm I'd assume Chisel has changed its code recently. If this is the case, you should find either one of the two things in your log around the init phase:

"Neither Chisel 1 or Chisel 2's main mod class could be found, even though chisel is in the instance. Report to MineMaarten plax!"

or

"Chisel reflection failed:
<stacktrace>"

Could you verify this?

**Comment by JasonMcRay** [comment]
Chisel reflection failed is indeed present in the log: http://pastebin.com/QNN3TtKP

**Comment by lafflam** [comment]
Confirmed startup log contains the following:

[Server thread/ERROR] [PneumaticCraft]: Chisel reflection failed:

**Comment by MineMaarten** [comment]
Chisel moved some things around, it's fixed for next version :). Thanks for the report.

**Comment by JasonMcRay** [comment]
Thank you very much

**Comment by JasonMcRay** [comment]
Not sure if there can be done something more about this, but when I for example use Energised Voidstone (chisel:voidstone2 meta:2) it gets all transparent. Some few others are behaving the same (mostly happens to those that are animated)
![2015-07-25_16 24 36](https://cloud.githubusercontent.com/assets/4236895/8889812/ad39ab4c-32e9-11e5-85b3-73feaac17399.png)

**Comment by MineMaarten** [comment]
I'm afraid not. To get this effects working Chisel uses some special effects which is beyond me to support. I probably could, but it sounds like a lot of exceptions ;). I'm afraid you'll have to use different materials.
