### ISSUE TITLE
Everything disabled by default

### ISSUE THREAD

**Issue by Wolf68k** [MineMaarten/PneumaticCraft#563]
Not sure if this was intentional or what
I was previously using 1.6.8-72 and the configs were fine.
I updated to 1.9.1-86 and didn't notice right away but the configs got overwritten so that everything was disabled; plant generation, mob drops seeds and effects.
I've even tried letting it load a fresh config with 1.9.9-97 and everything was still disabled.

**Comment by MineMaarten** [comment]
Check the log, it contains the reason why it disabled it. Also when you log into your client world, it said that it did disable the config options. You can set it back if you want, but,

https://imgur.com/a/gEysk
