### ISSUE TITLE
Oil aesthetic improvements

### ISSUE THREAD

**Issue by ruifung** [MineMaarten/PneumaticCraft#564]
Would it be possible to give oil a more... liquid look? Because right now it looks like a solid gray block.

**Comment by MineMaarten** [comment]
Personally I'm not really an aesthetics person, so I didn't mind it much. I have notified Glassmaker of this though, the creator of this texture. He created a few versions. Personally I like version 2 the most, but let me know:

Original: http://i.imgur.com/x4q5S5k.png
Version 1: http://i.imgur.com/aWhl6YD.png
Version 2: http://i.imgur.com/mzjEAqW.png
Version 3: http://i.imgur.com/erzyS2V.png

**Comment by Forecaster** [comment]
#2!

**Comment by GirafiStudios** [comment]
I agree, I quite like version 2.

**Comment by ruifung** [comment]
Yep, version 2.

**Comment by MineMaarten** [comment]
Ok, next version will include version 2 ;). Thanks to Glassmaker :)
