### ISSUE TITLE
Drone w/ Entity Tracker caused Server Crash when picking up ammo

### ISSUE THREAD

**Issue by jefmajor** [MineMaarten/PneumaticCraft#568]
We're running a bit of a strange server pack so that may be part of the issue, it's FTB Infinity 1.8.2 with PneumaticCraft (Version 1.7.10 1.9.9-17) installed manually.  

I programmed a drone using the programming machine to perform a program thusly:  start -> load from inventory -> area (single point, x, single point y of a chest containing ammo, the basic type), followed by entity attack with a text label and an area specified of two points of space x and y.

Here is the pastebin link to the error report:  http://pastebin.com/Syhxjhm6

**Comment by MineMaarten** [comment]
Fixed with https://github.com/MineMaarten/PneumaticCraft/commit/fff9886948cab9a5d77472330087f1bb0300d44b
