### ISSUE TITLE
Unable to extract gasoline from a drum once bucketted in

### ISSUE THREAD

**Issue by utoc** [MineMaarten/PneumaticCraft#576]
Hello!

I ran across an issue in Pneumaticcraft build 1.9.9-97 where once I placed a Pneumaticcraft gasoline bucket into a Extra Utilities drum, I was unable to retrieve it out with a bucket.  I had to use Thermal Expansion's Fluid Transposer to get a bucket from it.

Sorry for a brief bug report, I don't think you really need more information but don't hesitate to contact me if I have neglected anything meaningful.

**Comment by MineMaarten** [comment]
And this does work when filling other non lava/water/milk buckets? So like biofuel, creosote oil, ... any other mods' liquid basically?

**Comment by utoc** [comment]
Kerosene, LPG, Diesel, Oil and other non-Pneumaticcraft fluids work fine, this seems to be unique to gasoline.

**Comment by MineMaarten** [comment]
Are you using Buildcraft? As Gasoline is liquiddicted with BC Fuel. Does it work just with Buildcraft?

**Comment by utoc** [comment]
I am using Buildcraft.  Odd thing happened.. I can reproduce this all day long in an existing world.  I made a new world just for grins and I cannot reproduce this issue.  I'm able to get buckets out of gasoline drums all day long.  Any thoughts on this?

**Comment by MineMaarten** [comment]
I'm not sure. Maybe the registry of a clean world has decided differently on which bucket/block of fueld to use, either PneumaticCraft's or BC's.

**Comment by utoc** [comment]
I'm going to tinker with it for a few days, if I can't get it to bug out again by Friday then I will probably just ask to close the bug report since it would only apply to people who added PneumaticCraft to an existing world with BuildCraft already installed and that is probably a very very tiny percentage of users.

**Comment by utoc** [comment]
I'm going to close this issue as I cannot reproduce it with a new world.. only existing worlds.  I will reopen it if I have something more to go on.  Thanks for the help.
