### ISSUE TITLE
Show ghosted GPS positions when wearing pneumatic helmet

### ISSUE THREAD

**Issue by DexCisco** [MineMaarten/PneumaticCraft#578]
It would be nice to be able to see the position of a GPS coordinate when working with coordinates that are inside a block.  e.g. as Thaumcraft nodes are visible through blocks.  Especially useful when you have multiple GPSs and you are trying to figure out which is which by holding them.

**Comment by MineMaarten** [comment]
I want to enchance it also when not wearing a helmet really, so that will be a thing.
