### ISSUE TITLE
drones crashing

### ISSUE THREAD

**Issue by gerb82** [MineMaarten/PneumaticCraft#581]
i am using pneumatic craft in the modpack blast off,
and when i put a drone down and tell it to pick up a diamond sword and attack a creeper in my test world it crashes exactly when the drone kills it.

am i doing something wrong/this is a known issue/need more details?

**Comment by DexCisco** [comment]
I had the same issue, but the error log pointed to Infernal Mobs as the problem.  I had to remove Infernal Mobs so I could reload the game.

**Comment by gerb82** [comment]
it happens to me also when it's a normal creeper

**Comment by MineMaarten** [comment]
Crash log or it didn't happen.

**Comment by gerb82** [comment]
http://pastebin.com/WLdZxsG4
link to crash log

**Comment by gerb82** [comment]
if needed i can send a video of what i did

**Comment by MineMaarten** [comment]
This is a Battlegear 2 bug.

**Comment by gerb82** [comment]
ok, i will report this to the mod creator and to the blast off pack developer.
thanks for the help
