### ISSUE TITLE
Coordinate piece not saving coordinates.

### ISSUE THREAD

**Issue by ruifung** [MineMaarten/PneumaticCraft#582]
When entering a constant coordinate in the coordinate piece, changes to the coordinate are not saved when you press escape.

**Comment by MineMaarten** [comment]
Are you wearing a Pneumatic Helmet by a chance? I know this is causing problems

**Comment by ruifung** [comment]
Yeah, I'm wearing a pneumatic helmet.. I'll try without the pneumatic helmet and see.. That being said, the Area puzzle piece saves coordinates properly for me. It's the coordinate piece that isn't. (making me have to hardcode 3 different sets of coordinates into the program.

**Comment by ruifung** [comment]
Nope, it's not the pneumatic helmet. With or without, when I press escape the coordinate piece does not save the coordinates ( and defaults to 0,0,0). It does however, save if I choose to use it for variables instead ( but kind of useless as I cant set the initial values ).

**Comment by MineMaarten** [comment]
Confirmed and fixed ;)
