### ISSUE TITLE
Chamber Interface Item Filter won't accept more than one item

### ISSUE THREAD

**Issue by fzzhd123** [MineMaarten/PneumaticCraft#584]
I have been trying to figure out the best way to set up my pressure chamber, and I wanted to use the item filter setting on the interface. The problem is that it only accepts one item. If I put something in, the filter will only accept that item in the slots.

**Comment by ruifung** [comment]
Are you on the latest version of pneumaticcraft? I believe the latest version fixed this?

**Comment by MineMaarten** [comment]
Duplicate with https://github.com/MineMaarten/PneumaticCraft/issues/580 , version 1.9.11 indeed fixes this.

**Comment by fzzhd123** [comment]
I thought i was, ill check
