### ISSUE TITLE
IndexOutOfBoundsException with Lycanite

### ISSUE THREAD

**Issue by ruifung** [MineMaarten/PneumaticCraft#588]
http://paste.ee/p/SXSvF
Related issue: Lycanite/LycanitesMobs#116

**Comment by MineMaarten** [comment]
I think this is Lycanite Mobs' issue, it doesn't like the getDropItem() method. However, I'll add some protection from my side (by way of try catching).

**Comment by ruifung** [comment]
Yeah I know its lycanite mobs issue, but I figured that if thats the case you probably can add some checks from your side to at least stop it crashing. =P
