### ISSUE TITLE
GUI ledgers opening speed

### ISSUE THREAD

**Issue by LuigiHutch** [MineMaarten/PneumaticCraft#590]
A small enhancement I would love is:
A way to speed up the ledgers (or tabs) opening speed as I feel they open quite slowly at the moment and they could be quicker.

**Comment by Fayti1703** [comment]
Ledgers? Are you talking about (Pressure Chamber) Interfaces? If so, try inserting a few speed upgrades.

**Comment by MineMaarten** [comment]
He's talking about the gui tabs you see in about every pneumaticcraft GUI.

**Comment by MineMaarten** [comment]
Meh, sorry, I like it this way :P

**Comment by LuigiHutch** [comment]
Fair Enough :)
