### ISSUE TITLE
Add amazon like ordering system

### ISSUE THREAD

**Issue by MineMaarten** [MineMaarten/PneumaticCraft#592]
Drones will be used to deliver (code already there). I was thinking of possibly being able to sell Oil (and their products). A 'tablet' item will be used to place orders.

**Comment by MrKunji** [comment]
@HarleyCraft, would you give some tips?

**Comment by HarleyCraft** [comment]
You can make a config entry for it, players could put ids of items they want to be "purchasable" on the config, and using this list you can create a GUI for players to choose what to buy. I did something like this in my mod, if you want some reference (or not).

**Comment by AEnterprise** [comment]
maybe for servers also a way for players to sell items to others with this?

**Comment by MineMaarten** [comment]
@HarleyCraft : I feel this is something for mods like MineTweaker... But I'll see..

@AEnterprise : That's a very cool idea!

**Comment by SuddenReality** [comment]
Why Not also use this method also to have say fake dodgy dealers... then you have to check there details against something, but if your an idiot.. it drops tnt?

**Comment by MrKickkiller** [comment]
@MineMaarten: Don't forget to add a shotgun too... So i can shoot those drones when they fly over my lawn! And is this MFAA-Approved? :D
