### ISSUE TITLE
On my server, some item drops act like a seed and go far away

### ISSUE THREAD

**Issue by ExDomino** [MineMaarten/PneumaticCraft#594]
As I said in the title, sometime, when an item is dropped on the ground, it acts like a seed and go far away before despawning. It happens more often when RotaryCraft stuffs, like shafts, cooling fins and other, but I already lost a ME Cable in that way. I don't know what is the problem but I'm thinking it's an issue with PneumaticCraft because your seeds act like that.

**Comment by MineMaarten** [comment]
go far away?

**Comment by ExDomino** [comment]
Go far away, in the sense of when the item is dropped (from the inventory or from a block breaked), it starts to move really fast and when it colides with a block, is disapears. It's I think a normal behavior for seeds that come from your mods, but it sometime (rarely) happens with some items from other mods as well.

**Comment by MineMaarten** [comment]
The thing is is that it is simply not possible that my plants have to do with it, I'm afraid. The code that does this only is executed for my plants: https://github.com/MineMaarten/PneumaticCraft/blob/master/src/pneumaticCraft/common/item/ItemPlasticPlants.java#L292

So I think it's some other mechanic doing this. Sorry.

**Comment by ExDomino** [comment]
Is there a way to disable this behavior completely?

**Comment by MineMaarten** [comment]
Again, it is not because of the plants. There's no way to disable it apart from removing the mod. You might try copying the world, removing the world, and see if it happens still. I'm sure it will still be happening.
