### ISSUE TITLE
Vortex tube cool temperatures

### ISSUE THREAD

**Issue by NinjaOukie** [MineMaarten/PneumaticCraft#595]
Good day MineMaarten I watch Direwolf's channel and play some minecraft myself. Busy with your mod i noticed something on your "vortex tube" specifically cooling side temperature. im not sure if the "C" stands for the metric celsius but in any case there is no way in actuality in any scale of temperature that a system (the system. system being a defined space) would reach negative 1000 nevermind 8000. I am a chemical engineer student therefore thermodynamics (the study of heat and energy) is a love of mine. not even deep space to my knowledge reaches below 0 kelvin which is -273 deg C metric. the reason for this is as soon as your cooling down beyond what naturally occurs and nearing 0 kelvin in lame mans terms the temperature difference is to big and more energy flows from the suroundings into. furthermore to human knowledge nothing (not even atoms nevermind anything else) can exist at 0 kelvin... i hope i didnt make it to complex an explanation

i would not call this a bug, afterall its only a game... but again looks like with the refining and rest of the revamp your trying to make a accurate mod so i thought you would appreciate the input.

ps sorry for any typing errors... and pneumaticraft is a good mod continue the good work.

**Comment by MrKunji** [comment]
Well, there were some changes few days ago:
https://github.com/MineMaarten/PneumaticCraft/commit/a31394b47612cc64eb565a64a78d59cb8384bc41

**Comment by pyure** [comment]
Yep, duplicate (triplicate) of #532 and resolved.  Yay realism :)

**Comment by NinjaOukie** [comment]
apologies

**Comment by NinjaOukie** [comment]
anyone have an idea about the temperature for refining has been made acurate to thos of the actual industrial process

**Comment by MineMaarten** [comment]
It is not. Real life refining happens around 350 degrees C, PneumaticCraft starts at 100C. A compromise with balance has been made. It is simply too hard to get to 350 early game with a simple set-up. Bare in mind that it's exponentially more hard to get to 350C over 100C.

**Comment by NinjaOukie** [comment]
ok guessed as much with the pressure range as "low" and "high" also has different scale than industry but in industry "low" pressure is considered to be around 50-100bar but takes 2-3 industrial massive compressors in series to achieve.
