### ISSUE TITLE
[Suggestion] Programmer: Copy branch

### ISSUE THREAD

**Issue by RViper80** [MineMaarten/PneumaticCraft#597]
Would it be possible to add a way to copy a whole section of puzzle pieces like what can be done using middle-click to copy one piece?

I have a program where I need the same subroutine used multiple times, with just the item filter changed.  Would be nice to be able to copy the selected piece, along with any to either side and below that one somehow.

**Comment by MineMaarten** [comment]
Hmmm I did think about this before, but now I've got a way to do it I think! How about when you sneak-middle click you do this?:)

**Comment by ruifung** [comment]
instead of binding to middle click you should make it bind to pick block. (My middle mouse button is broken =/)

**Comment by RViper80** [comment]
That sounds like it should work.  And yeah, I agree that it would be nice to have it customizable, as my middle mouse is also getting there.

**Comment by MineMaarten** [comment]
Good suggestion. I'll add that too the usual copy function.
