### ISSUE TITLE
gauge outputs don't seem to work with, e.g., redcrystal?

### ISSUE THREAD

**Issue by seebs** [MineMaarten/PneumaticCraft#598]
So, I've been very fond of automagy's redcrystal, but it appears that things like the pressure gauge "emit redstone" in a way that is specific to vanilla redstone and doesn't seem to interact well with anything else. Not sure what's going on here. If I place a single bit of vanilla redstone, and then put other things next to it, they work fine.

**Comment by MineMaarten** [comment]
I believe the Pressure Gauge Tube Module also works fine with BuildCraft gates. So you sure it isn't the redcrystal doing things weird?:P

**Comment by seebs** [comment]
Not 100% sure, no. I am gonna try EIO conduits next. I think there's also some kind of redstone wire that a friend was trying and it wasn't working either.
