### ISSUE TITLE
Aerial Interfaces not work after crash!

### ISSUE THREAD

**Issue by TheBigBadWolf2** [MineMaarten/PneumaticCraft#601]
My Aerial Interfaces were acting funny last night. They wouldn't work until I opened up their GUIs.
This had happened after I crashed, a problem with the interaction between two other mods, and after I had to MCEdit another dimension.

**Comment by MineMaarten** [comment]
Can you find the crash? (It should be in the crash_logs folder in your instance) Or was the crash unrelated to PneumaticCraft?

**Comment by TheBigBadWolf2** [comment]
It was unrelated. Thermal Dynamics and Dimensional Pockets.

**Comment by MineMaarten** [comment]
Also 'not work', what was it doing? Just normal item interfacing, or feeding, or?

**Comment by TheBigBadWolf2** [comment]
One won't feed me. The other won't take the bowl back.
