### ISSUE TITLE
Not so empty tank!

### ISSUE THREAD

**Issue by TheBigBadWolf2** [MineMaarten/PneumaticCraft#602]
If you pull liquids out of say a liquid compressor, the GUI doesn't always update. I know I pulled all out b/c it was full, I turned it off, cut the fuel flow into it, and I had the amount in the tank that I pulled to as expected if I drained it all.

**Comment by Forecaster** [comment]
This happens with other tanks as well sometimes, for example when pulling fluid out of a Mariculture tank, sometimes it looks like there's a little bit left in it when it's actually empty.

It seems like it isn't updated visually on the last tick.

**Comment by MineMaarten** [comment]
It's a sync issue on my part, the server doesn't know how to update the client about an empty tank as of now. It will happen with more tanks (like refineries or the liquid hopper)
