### ISSUE TITLE
Wildcard functionality for entity names in pneumatic helmet with entity tracker

### ISSUE THREAD

**Issue by Forecaster** [MineMaarten/PneumaticCraft#603]
Please add [insert title here]

**Comment by RViper80** [comment]
Along with this, I've tried to put in multiple specific entities at once as well.  There's times where I only want to track a couple things that don't fit any of the @ categories.  Maybe it could be delimited by a semicolon or comma. (drone;villager;creeper)

**Comment by ruifung** [comment]
Yes please wildcard. Lycanite mobs can't be targetted using @mob and because of all the variations i cant use the name to target either

So please make something like *spriggan will target all mobs whose name ends with spriggan.
