### ISSUE TITLE
Refinery Redstone Control

### ISSUE THREAD

**Issue by killerboy9909** [MineMaarten/PneumaticCraft#611]
On my refinery setup (4 refineries stacked on top of each other), The redstone control setting keeps getting switched from "Any Signal" to "High Signal" and stops working as I don't have a signal applied to it. This happens randomly when I do not have the GUI open. I will set it, leave and come back a few minutes later to see that my refineries stopped producing the hydrocarbons because it somehow got changed to high. I play on single player so it cant be someone changing it. I tested this with a few other ones too. It happens with other stacks of 4 and stacks of 1, 2 and 3 as well.

**Comment by MineMaarten** [comment]
Ah! it appears like when you click on any of the output tanks, it switches the redstone state ;). This is fixed for next version.

**Comment by ruifung** [comment]
Is the refinery comparator compatible? So I can check if it has work to do? (So i can turn off the vortex pipes heating it.)

**Comment by MineMaarten** [comment]
nope, but sounds like something you might want to create another issue for.

**Comment by ruifung** [comment]
Yes, yes I will.
