### ISSUE TITLE
Advanced Liquid Compressor and Heat Sinks

### ISSUE THREAD

**Issue by killerboy9909** [MineMaarten/PneumaticCraft#612]
When using the heat sink on the advanced liquid compressor, placing one on the top says "bottom" temperature and placing one on bottom says "top" temperature. Also, since these get very hot, why not let your machines get heat from them?

**Comment by MineMaarten** [comment]
>When using the heat sink on the advanced liquid compressor, placing one on the top says "bottom" temperature and placing one on bottom says "top" temperature.

Intended behaviour

>Also, since these get very hot, why not let your machines get heat from them?

Uhm, what do you mean?

**Comment by killerboy9909** [comment]
The heat sinks say that they are hot on the waila tool thing. So if I put some refineries down next to it, could you make it so they get heat from the heat sink attached to the advanced liquid compressor?

**Comment by MineMaarten** [comment]
No. Use a Compressed Iron Block for that, that acts as a heat conductor.

**Comment by pyure** [comment]
killerboy9909, to clarify, you can do what you want by using the compressed iron block as a bridge.
