### ISSUE TITLE
Vortex Tube Shutoff

### ISSUE THREAD

**Issue by eractnod** [MineMaarten/PneumaticCraft#616]
I like the heating and cooling of the mod and I do like the vortex tube, but the one problem I have with it is it is always on and using air.  This is causing the use of a lot of RF or coal when the system is idle.  My suggestion is to add an inline shutoff valve that is controlled by redstone.  This way the vortex tube can be turned off when the system is idle and it is not needed to heat or cool something.  With 10 speed upgrades and 3 vortex tubes at various locations, I was going through about 1200 RF every few seconds at an idle state.  I finally removed the vortex tubes and now using a lot of lava with compression iron blocks to heat up the refinery.  Another suggestion is to add redstone control to the vortex tube itself, but I think the valve could be used in more places.

**Comment by Forecaster** [comment]
This already exists. It's called the regulator module. Wednesday, 05 August 2015, 05:47pm +02:00 from eractnod < notifications@github.com> :

**Comment by MineMaarten** [comment]
yup, Regulator Tube Module, a threshold of 0.0 bar = shutoff. Also, you could use this to regulate the amount of air used by the vortex tube when running, if you wanted to.
