### ISSUE TITLE
Little blank texture on controller 

### ISSUE THREAD

**Issue by lieven121** [MineMaarten/PneumaticCraft#617]
just above my cursor you see the opening 
![2015-08-06_01 26 15](https://cloud.githubusercontent.com/assets/7773244/9100430/20976a8a-3bdb-11e5-8f11-94cf9cdcc5d6.png)

**Comment by MineMaarten** [comment]
Fixed already with https://github.com/MineMaarten/PneumaticCraft/commit/3f7162b6f2f21705d0183b53f3ad37a751f5179b, which had been released already

**Comment by lieven121** [comment]
srr derp off me
