### ISSUE TITLE
Frames render where there used to be a frame, but where there no longer is a frame

### ISSUE THREAD

**Issue by Forecaster** [MineMaarten/PneumaticCraft#620]
http://imgur.com/m7EbkyO

I mean, what's up with that?

**Comment by Forecaster** [comment]
This may be Optifine's fault actually. I just added it, and this never happened before.

**Comment by GirafiStudios** [comment]
Only one way to find out. Try to remove Optifine :p

**Comment by Forecaster** [comment]
Also this is spamming the console: http://hastebin.com/equvisibac.avrasm

Along with visuals like these: http://imgur.com/MC6HiMc,o3b1GAB

This only happens while holding a frame though...

**Comment by Forecaster** [comment]
Seems it was indeed OF that was causing the frames to get stuck as well, since removing it appears to have made it stop.
