### ISSUE TITLE
Fix IGW links.

### ISSUE THREAD

**Issue by ruifung** [MineMaarten/PneumaticCraft#623]
There are broken links everywhere. (like the programer pieces)

**Comment by MineMaarten** [comment]
tested with latest PneumaticCraft and IGW? As I know I've fixed many links in PneumaticCraft to work with the 'new' IGW mod system.

**Comment by ruifung** [comment]
RIght, I forgot to check for updates. Ill test later and get back to you

**Comment by ruifung** [comment]
Given the randomness of those crashes that happens to me, I'll close this for now and reopen if it crashes.
