### ISSUE TITLE
Refinery Redstone Comparator support

### ISSUE THREAD

**Issue by ruifung** [MineMaarten/PneumaticCraft#625]
Comparator that outputs the amount of oil or other liquid left to process. (Or alternatively, just if it has work to do or not, since it can have a teeny tiny bit of fluid left thats too little to process.) 

This is so heating vortex tubes can be automatically shut off.

**Comment by MineMaarten** [comment]
It would probably be a 'has work', as it could as well be that your output tanks are full that prevents the refinery from running. This could possibly be applied to other machines as well (like the thermopneumatic processing plant).

And possibly BC gate support ;).
