### ISSUE TITLE
[Request] Creative upgrade for helmet

### ISSUE THREAD

**Issue by RisingDemon** [MineMaarten/PneumaticCraft#630]
I love the pneumatic helmet, especially with the hacking system, but having to keep refilling its air gets really annoying at times. I'd love an upgrade that changes that. I had a few ideas, in no particular order:

1. Ignore pressure completely. Even when empty, the helmet works. Not my favourite, just feels wrong.
2. Don't drain pressure. Require there to be some pressure, but don't decrease it while in use. My personal fave.
3. Some kind of portable compressor, maybe a thaumcraft infusion, that keeps the pressure up by consuming some fuel, like aer vis from a wand. Not a "creative" upgrade anymore, but a nice alternative. Kinda like this one, maybe in addition to ane of the others?

Another possibility might be a special nbt tag that applies item 1 or 2 from above. The upgrade could even apply to drones and the pneumatic tools, like the wrench or vortex cannon.

**Comment by MineMaarten** [comment]
Not sure how this would be useful. When you want to use it in creative (sounds like it), be in creative, and it won't drain. If you want to use it in survival, just use an Aerial Interface and piont a Charging Tube Module to the bottom of it: remote charging.
