### ISSUE TITLE
Drones losing inventory

### ISSUE THREAD

**Issue by nik0teen** [MineMaarten/PneumaticCraft#631]
As soon as i place my drones into the world they lose any upgrades I've placed in their inventory while on the charging station. I'm using Direwolf20's latest pack. Any ideas anyone?

Many Thanks
Nik0

**Comment by MineMaarten** [comment]
Which version of PneumaticCraft is the DW20 pack? As I know I've fixed this...

**Comment by nik0teen** [comment]
Hi MineMaarten its version 1.7.10 1.9.2-88, there also seems to be an issue when you place the drone in the programmer it randomly drops puzzle pieces on the floor, which can't be picked up but do follow you round if you have any sort of magnet in your inventory.
Thanks for the reply MM.....  loving your work
Nik0

**Comment by nik0teen** [comment]
i've since downloaded the latest version seems to have resolved the issues. Just need to sort out how to get lubricant now lol
Many thanks
Nik0

**Comment by MineMaarten** [comment]
cool
