### ISSUE TITLE
Buildcraft pump doesn't recognize oil when Pneumaticraft is present

### ISSUE THREAD

**Issue by JoTheVeteran** [MineMaarten/PneumaticCraft#634]
So I love your mod PneuMaticCraft Maarten and I thank you for all the hard work you've put into it, but it has been giving me a couple of headaches lately.
I found it tedious searching for those small oil wells that naturally spawn with PMC, empty them in like a minute, then move to the next. So I installed BuildCraft and pruned the world around my base with mcedit and voila! Huge BC oil spouts and lakes all around. I then picked my old trusty BC pump and 4 redstone engines and proceeded to the nearest well. Placed the pump over the oil and waited... and waited for it to extend, but nothing happened. I placed it over water, worked fine. Over oil, nada! I tried your gas pump, it goes straight through the oil continuously digging down. I remove PMC and the pump works fine over oil. I've also noticed that the Gasoline liquid that's supposed to be replaced with BC fuel, has a lava texture, and the oil when put to tanks (via bucket) has an error texture or is invisible. All these fix again if I remove PMC.
I bugged a bunch of Minecraft youtubers and searched for this a lot before making this post. I find it odd that no one else noticed this.
So can you shed some light in here my friend. I've taken a bunch of pics, unfortunately I had no idea how to compile my mods list into a single .txt file, so I made a collage of them as they appear inside the curse client.
http://s1383.photobucket.com/user/Jo_The_Veteran/library/Minecraft%20BC%20Pump

**Comment by JoTheVeteran** [comment]
I tried a clean instance and it worked fine, so it be a mod loading order issue. Any idea how to change that in my existing save?

**Comment by MineMaarten** [comment]
Not sure :|. It's something for me to resolve..

**Comment by JoTheVeteran** [comment]
Did some testing today. It's definitely a mod order thing. Removed PC and other than loosing all my PC progress BC worked fine. Then re-added PC and BC still worked. Loaded my save prior to removing PC and BC stopped working once again. Liquid textures are also fixed if you remove, save, then re-add PC.
You need to specify this somehow to the compatibility issues of the mod. Must be loaded with BC if BC is to be added to the pack, or others might stumble into the same thing I did.
