### ISSUE TITLE
[suggestion] puzzle piece to enable iteration

### ISSUE THREAD

**Issue by FinalMiner** [MineMaarten/PneumaticCraft#643]
Please consider a puzzle piece that would update other puzzle pieces each time it ran through the program. For example, a puzzle piece that would change an area piece's coordinates each time the drone looped through the program.

Use case: Drones doing a "dig" command could return to an equipment chest to replace broken equipment after each x layers were dug. Currently there is no way to do this without ComputerCraft, and it severely limits the use of drones as a mining mechanic or large-scale terrain clearing mechanic.

Implementation suggestion: The piece would update itself with each iteration, not the piece modified. It would attach between the action piece and the area piece(s). It would track its own "initial" values (how much to change the next piece's values per iteration) as well as its "current" values (to keep track of progress.) It would track "ceiling" values to determine a stopping point.

**Comment by MineMaarten** [comment]
Judging by this I don't think you've looked into variables yet. Install In-Game Wiki mod if you haven't already and read up ;). And put the Programmer in 'advanced' mode.
