### ISSUE TITLE
[suggestion] Aerial Interface Feeding you oxygen when under water.

### ISSUE THREAD

**Issue by CaptiveCreeper** [MineMaarten/PneumaticCraft#644]
When you are under water and you normally need to make sure you have oxygen and don't suffocate it would be cool if the Aerial Interface would keep your oxygen full so you could do deep diving without any worries of death.

**Comment by MineMaarten** [comment]
Hmm quite interesting.. maybe at the cost of a lot of a lot of air..

**Comment by Sprocks59** [comment]
It could also be an upgrade to be added to the helmet. Something like taking a air can and adding it to the upgrade slot, this could also be a buffer incase your system runs out of air pressure and once you hit 30% air in the tank you start to lose air slowly as a warning to get to the surface or drown.
