### ISSUE TITLE
[Request] Redstone control for plastic mixer

### ISSUE THREAD

**Issue by lengeltjes** [MineMaarten/PneumaticCraft#646]
It would help a lot in keeping an X amount of a certain color plastic stocked. Right now I either have to grab it manually every time, or I have the machine burn through my liquid plastic supply as soon as I lock the selection. Being able to turn it off based on a redstone signal. The thermopneumatic processing plant has redstone control already but I would like to see it for the plastic mixer too.

**Comment by lengeltjes** [comment]
I accidentally left in an unfinished sentence, my apologies.

**Comment by MineMaarten** [comment]
Hmm.... I already had plans for the redstone behaviour to set the selection depending on the redstone signal (so level 0 is black, level 1 is red (? the second one in any case).

But I guess I can also add the usual modes.

**Comment by cauliflower69** [comment]
Thanks MineMaarten, I came here to post the same as OP

**Comment by lengeltjes** [comment]
Thanks, MineMaarten :)
