### ISSUE TITLE
Please keep plants

### ISSUE THREAD

**Issue by user716** [MineMaarten/PneumaticCraft#648]
I heard something about plants being dropped in favor of oil. I would like for plants to be kept for decorative reasons, with plastic still being changed as planned.

**Comment by Forecaster** [comment]
The oil system has already been implemented. The plants still exist and can be used to make plastic at the moment. Most likely the plants will go away in the 1.8/1.9 transition.

**Comment by MineMaarten** [comment]
What Forecaster said. I've never heard anyone being positive about the aesthetics of the plants, so this surprises me. But even then, I'm afraid the plants will be removed either way in 1.8/1.9. They simply caused too many issues to keep around as well as the oil system, plus I don't want 2 different systems to exist.
