### ISSUE TITLE
Drone not holding upgrades

### ISSUE THREAD

**Issue by suprphrk** [MineMaarten/PneumaticCraft#655]
My PneumaticCraft drones won't hold any upgrades. I've put a life upgrade, 7 speed upgrades, and 24 dispenser upgrades in. Then I take the drone out of the charging station and place it in the world, it's still slow, only picks up one stack of items, and won't regenerate its health. When I then wrench it and put it back in the charging station, no upgrades are in the drone.

Is there a config I need to change?  File that didn't get the access changed correctly on?  I should mention I'm on Direwolf's 1.6.0 pack.

**Comment by Forecaster** [comment]
Is this a Logistics Drone or an advanced Drone?

**Comment by MineMaarten** [comment]
Outdated version

**Comment by suprphrk** [comment]
I assume advanced drone?  It just says "Drone", and it's item 5929 in the dw20 pack.  The PneumaticCraft version in his pack is 1.9.2-88.  Is that way outdated?

**Comment by MineMaarten** [comment]
It's fixed anyway in newer versions (sorry for the short answer, got this invalid bug report too many times already)

**Comment by suprphrk** [comment]
Can confirm. Upgraded to dw20 pack 1.7.0 and the upgrades took (PneumaticCraft v1.9.15-104). Keep up the good work.
