### ISSUE TITLE
Using ender IO Yeta wrench on advanced pressure tube gives you pressure tube...

### ISSUE THREAD

**Issue by Kazzamkablam** [MineMaarten/PneumaticCraft#662]
yup...

On pneumaticcraft 1.11.1.121

Only appears to happen to old pipes tho, for whatever reason.

**Comment by MineMaarten** [comment]
Hmm you are correct... Even with just a Pneumatic Wrench (I couldn't even manage to wrench off tubes with a Yeta Wrench).
