### ISSUE TITLE
Fuel Compatibility with Ender IO

### ISSUE THREAD

**Issue by GauHelldragon** [MineMaarten/PneumaticCraft#666]
It'd be really great if you could use EnderIO fuels in PneumaticCraft machines and PneumaticCraft fuels in EnderIO generators! I have been told you can use IMC with EIO to register fuels with them. 

https://github.com/SleepyTrousers/EnderIO/blob/master/src/main/java/crazypants/enderio/api/IMC.java#L107

Is there a similar thing EIO can do to register PnC fuels?

**Comment by MineMaarten** [comment]
I'll try to add compat from both sides :)
