### ISSUE TITLE
Drones that have been placed in creative mode shouldn't drop when executing "Suicide"

### ISSUE THREAD

**Issue by Forecaster** [MineMaarten/PneumaticCraft#671]
They don't drop when being wrenched, so it makes sense that they shouldn't drop on suicide either.

**Comment by MineMaarten** [comment]
That's not always the desired effect imo. There could be a huge delay between when the drone was placed down (maybe as a result of some bug it was replaced by an OP who was in creative). 

I can understand your use for it, but imo it's not good to implement, I see Drones not dropping as a result of this easily being considered as a bug.
