### ISSUE TITLE
com.google.gson.JsonNull

### ISSUE THREAD

**Issue by SvEgiiVEteR** [MineMaarten/PneumaticCraft#673]
123
http://paste.ubuntu.com/12306562/
line 40655
[14:12:06] [Client thread/ERROR] [FML/]: Caught exception from PneumaticCraft
java.lang.ClassCastException: com.google.gson.JsonNull cannot be cast to com.google.gson.JsonObject
121 ок

**Comment by MineMaarten** [comment]
I suspect this is a system dependent bug...

**Comment by SvEgiiVEteR** [comment]
I think it is a conflict with mods appeared. because it had not been a problem.
I ran to the assembly of mini games (few mods) and run without any problems.
sorry for bad english

if I can find a reason write.

**Comment by MineMaarten** [comment]
Well, seeing the amount of mods you're running with, it's hard to pinpoint. I've no clue what causes this. I can make it stop crashing you, but your config files still will be broken, with uncertain consequences.

**Comment by AEnterprise** [comment]
can you maybe put that file on pastebin or so? it maybe it's formatting got corrupted or so causing this

**Comment by SvEgiiVEteR** [comment]
currently am looking for problematic mod + noticed some config files 0 size.
eg
AmadronOffersPeriodic.cfg

**Comment by SvEgiiVEteR** [comment]
found..
Fossils_Archeology_Revival-1.7.10_Build-7.2.jar
why then if you install this mod.
there is a crash

**Comment by MineMaarten** [comment]
Only PneumaticCraft configs or also others?

**Comment by SvEgiiVEteR** [comment]
AmadronOffersPeriodic.cfg 0
and ProgrammingPuzzleBlacklist.cfg not even created.
all other config files are created. this mod, and others.

**Comment by MineMaarten** [comment]
I mean, does this happen to other mods their configs as well? (If tried with a clean config, as it appears that it happens when the files are generated initially)

**Comment by SvEgiiVEteR** [comment]
hmm .. I will try to check. I have a lot of mods and of course, many configs already configured. and remove all config instantly lead to breakage (conflicts biomes or worlds, and so etc.)

I know precisely when I delete FossilsArcheology
then your configs mod are no problems.

**Comment by MineMaarten** [comment]
yeah, you could temporarily remove FossilsArcheology, let PneumaticCraft generate the configs properly, and put it back in, and see how that goes. In any case it does sound like something for the author of FossilsArcheology to fix.

**Comment by SvEgiiVEteR** [comment]
it helped .. thanks.
