### ISSUE TITLE
Programmer UI features

### ISSUE THREAD

**Issue by sfPlayer1** [MineMaarten/PneumaticCraft#677]
The following extra features would be nice to have:

- Resizing to use more screen area
- An undo button
- Subroutines with their own editing page and some global library feature
- Variable selection from a list of available ones

**Comment by MineMaarten** [comment]
"Resizing to use more screen area" what do you mean? It already has zooming?
"Subroutines with their own editing page and some global library feature" I said that as a joke, not going to add this ;P. I will think about the 'coordinate sorting' piece though. Though I can't think of a general use for it (so if it will be useful for many more people than just you :P).

The other two suggestions: cool :)

**Comment by sfPlayer1** [comment]
I'm referring to resizing the actual gui to have less dead/unused space (https://i.imgur.com/L6B4lgy.png), but probably optionally due to varying peoples' preferences.

Subroutines or multiple pages with tabs are just an idea to handle more complex problems without making a mess. Said coordinate sorting piece suggests having some sort of library function, in this case SIMD-like min(vec1, vec2) and max. I wouldn't use pieces for each of those high level functions.

**Comment by MineMaarten** [comment]
Hmm I'd think because of screen resolutions your screen was determined _just_ too small to fit a step bigger UI size. :( It 'fully' covers my screen.
