### ISSUE TITLE
Server Crash when i upgrade to 1.11.6-126

### ISSUE THREAD

**Issue by Daphonic** [MineMaarten/PneumaticCraft#680]
https://www.dropbox.com/s/5h4wkofi5cr7x16/fml-server-latest.log?dl=0
Console Log

https://docs.google.com/document/d/1MHAwqcj0oV-xpxg0h0jdms-raqeg9vYwZx0uPEt1yX4/edit?usp=sharing
Crash Report

**Comment by MineMaarten** [comment]
Duplicate with https://github.com/MineMaarten/PneumaticCraft/issues/673 ?

**Comment by Daphonic** [comment]
I will try 673, It has to be a Curse Release for my Pack

The Version I have that works is 1.8.2-84

**Comment by Daphonic** [comment]
My bad #673 was an issue. I do have Fossiles. Let me try and remove it, than put back.

**Comment by Daphonic** [comment]
It looks like that was the Issue. Removed Fossials & Archeology Revival and put in the newest Version and worked.

**Comment by Daphonic** [comment]
but now the Clients are crashing... even with Fossials and Arch removed.

**Comment by Daphonic** [comment]
ok Figured it out. Thanks MineMaarten. That #673 was the answer to my problem.
