### ISSUE TITLE
Amadron auto-orders anything in your cart from the second page and below

### ISSUE THREAD

**Issue by Xandermud** [MineMaarten/PneumaticCraft#681]
When you put an item from the first page of the Amadron Tablet in your cart and close the gui, it remains in the cart upon opening it again. However, if you place an item in your cart from any of the other pages (below the first) and close the gui, when you open the gui again and scroll back to that page, item it isn't in the cart anymore and a drone comes to pick up the payment and drop off the item. This only triggers when you scroll to the correct page the item is on. If that isn't a clear description of the issue, I can record a video of it happening.

**Comment by MineMaarten** [comment]
it's pretty clear, tnx. I'll look into it.

**Comment by MineMaarten** [comment]
lol, it's actually clicking on the scrollbar that triggers it ;). Actually scrolling (with the scroll wheel) doesn't trigger it, which is why it didn't appear on testing. Fixed it in next version.
