### ISSUE TITLE
Refining Diesel in Refinery produces same products as Oil.

### ISSUE THREAD

**Issue by rtngtom** [MineMaarten/PneumaticCraft#687]
When pumped in via any mod pipe or container, Diesel, Kerosene, Gasoline, and LPG will behave as though they were Oil. I'm going to go out on a limb and say this is not intended, though you can feel free to correct me.

**Comment by MineMaarten** [comment]
I don't understand? The title of this issue describes something different as what you say now? 'Behaves'? you mean converts? which does sound veeeeerry weird if it does.

**Comment by Forecaster** [comment]
I think he means the refinery treats the as if they were oil, rather than the fluids behaving as though they were oil.

**Comment by rtngtom** [comment]
Sorry, English isn't really my best language. It's as Forecaster says.

**Comment by MineMaarten** [comment]
Hmpf actually it's because most mods don't check for 'canFill' like they should. If you'd use drones/Liquid Hopper to fill it it would work fine. But... I guess I'll fix it >.>.
