### ISSUE TITLE
Plastic Mixer Computercraft support/metgods

### ISSUE THREAD

**Issue by callmebackdraft** [MineMaarten/PneumaticCraft#690]
Hi Minemaarten,
I think it would be awesome if the plastic mixer had computercraft/opencomputers support.
In my opinion it could be a great addition for automation and the like.

Making the computer able to select the plastic type you whish to craft.
I hope you will consider this.

Kind regards

**Comment by MineMaarten** [comment]
Even though you can already select plastic to be fabricated with the special redstone mode, there isn't a mode to turn it off. So I can see the use in that. I'll look into it.
