### ISSUE TITLE
[Suggestion]Allow seismic sensor detect oil generated by other mods

### ISSUE THREAD

**Issue by wormzjl** [MineMaarten/PneumaticCraft#691]
Currently this item only detects oil generated by the default algorithm of pneumaticcraft.
However I would like use another mod (Custom ore generation or cofh core for example) to generate oil since they are easily customize-able.
Perhaps it could perform a scan on the column of blocks when right clicked?

**Comment by MineMaarten** [comment]
Yeah, they do currently, because I made them really efficient (requiring the world gen to register something). However, as this has been asked many times now, and it turns out it can be done in a acceptable way (in terms of performance), I'll look into it.
