### ISSUE TITLE
What is the address used by the in-game wiki ?

### ISSUE THREAD

**Issue by ExDomino** [MineMaarten/PneumaticCraft#694]
I have a laptop and I would like to read the wiki with it instead to be forced in-game. So I'm wondering, if the in-game wiki is taken online, where is the website to consult it in firefox/chrome please? The wiki on your official website said that is outdated and is for 1.6.4 only. Thanks in advance!

**Comment by MineMaarten** [comment]
No it's offline, 'in-game'. Use it in-game, or if you really want to, here are all the pages, raw. https://github.com/MineMaarten/PneumaticCraft/tree/master/resources/assets/pneumaticcraft/wiki/en_US

 It simply is too much effort to manage two wiki's, and if I have to choose (which I did), I would go for an in-game one.
