### ISSUE TITLE
Server crash like #697 with latest version

### ISSUE THREAD

**Issue by giuseppeM99** [MineMaarten/PneumaticCraft#698]
I'm using the latest version of pneumaticraft (1.11.10-132) and...
http://pastebin.com/bPCZArqV
Another crash in the server

**Comment by GirafiStudios** [comment]
Fixed with https://github.com/MineMaarten/PneumaticCraft/commit/ad8c6292214a68088e3dd73271addbc59c8cfb49

**Comment by GirafiStudios** [comment]
Caused by https://github.com/MineMaarten/PneumaticCraft/blob/a518d18212cf81d1ed358c688cc8fd026ab09101/src/pneumaticCraft/common/fluid/FluidPneumaticCraft.java#L20-#L27

**Comment by MineMaarten** [comment]
I can read a crashlog Girafi, tyvm. I'll close it and continue in #697
