### ISSUE TITLE
Check for default fluids in FluidRegistry instead of mod specific Fluid

### ISSUE THREAD

**Issue by ruifung** [MineMaarten/PneumaticCraft#700]
https://github.com/ExtraCells/ExtraCells2/issues/300

Because EC2's fluid handling is based on the fluid registry, all fluids stored in storage cells will be converted to whatever is the default Fluid for a given name (aka the first one registered.) I presume from this issue that you have some machines that are checking specifically for your own Fluid instead of any compatible names.

**Comment by MineMaarten** [comment]
Not the case as of 1.11.8. https://github.com/MineMaarten/PneumaticCraft/commit/a518d18212cf81d1ed358c688cc8fd026ab09101

**Comment by ruifung** [comment]
Whoops. Didn't notice that.
