### ISSUE TITLE
Cannot pump oil into Refinery v 11-133

### ISSUE THREAD

**Issue by Tekstack** [MineMaarten/PneumaticCraft#702]
All other liquids transfer correctly (i.e. plastic,lpg, etc.) between various machines, but I cannot pump oil into a refinery by any means on any side (including Enderio fluid conduits/BC Fluid pipes/ or even the Liquid Omni Hopper). I even tried using a traditional drone logistics drone, and the newer Logistics module with no avail. This was present from moving from v 127 to 133. Currently I am running a modified version of The Forgecraft Modpack by Pahimar.  Here is a link to screen to some screen shots http://imgur.com/a/pVZdk

**Comment by Forecaster** [comment]
What mod is the oil from?

**Comment by Tekstack** [comment]
BC, but i just noticed that i cannot place your oil into any inventory.

**Comment by Tekstack** [comment]
List of all Active mods/versions
http://hastebin.com/olorajufer.hs

**Comment by MineMaarten** [comment]
Thanks for the extensive bug report. It was something I missed when reworking the fluid handling I did. I was convinced I refactored them all.
