### ISSUE TITLE
Logistic frames disappearing on chunk unloading.

### ISSUE THREAD

**Issue by Tedyhere** [MineMaarten/PneumaticCraft#704]
In my modpack Modlife 3 on Curse Voice whenever a player leaves an area and the chunk unloads the logistic frames disappear from the chests they are placed on.  These are normal vanilla chests so I am not sure what is going on with this.  I have a video recorded if you need that I can provide it.  But I would just grab the pack and see what I am talking about.  If you need a copy of my world I can provide it.

**Comment by MineMaarten** [comment]
This is a semi-known problem. It's one of those that's hard to reproduce, and therefore difficult to pinpoint where the problem is. However, you make it sound it's very reliable to reproduce?

**Comment by Tedyhere** [comment]
I have reproduced it 100% of the time on my test world.

**Comment by MineMaarten** [comment]
Hmm I can confirm this. And this is different. The issue I was talking about made the frames disappear client only. This seems server side..

**Comment by MineMaarten** [comment]
Yes, I finally fixed this bitch!:P
