### ISSUE TITLE
Crash with Manometer used on a liquid hopper

### ISSUE THREAD

**Issue by Dominance** [MineMaarten/PneumaticCraft#708]
https://github.com/Beyond-Reality/Beyond-Reality-Divergence/issues/124

**Comment by MineMaarten** [comment]
The pastebin has been removed/expired, so I can't see the crashlog. I also tried to reproduce it on both SSP and SMP, to no avail. So more info is needed :).

**Comment by helkarakse** [comment]
New pastebin with the crash log, this one shouldn't expire: http://pastebin.com/S6eT3BFT

**Comment by MineMaarten** [comment]
Right that one works indeed. However, from the crashlog I can only gather you right clicked a machine that implements the heat mechanic, so did you mean a Liquid Compressor (as opposed to a Liquid Hopper). That would explain why I couldn't reproduce it.

Anyway, I know the issue now :).

**Comment by helkarakse** [comment]
I don't know the specifics of the crash, as this occurred to someone else. I can clarify if you still need more information; I only have the crash log from the server.

**Comment by Dominance** [comment]
Thanks MineMaarten
