### ISSUE TITLE
UI

### ISSUE THREAD

**Issue by shadoxxhd** [MineMaarten/PneumaticCraft#709]
could you make a standalone minimod for the helmet UI?

**Comment by MineMaarten** [comment]
I won't do that, sorry..

**Comment by shadoxxhd** [comment]
why (i don't mean the 'cheaty' functionality but the design, in the case you are worried)?

**Comment by MineMaarten** [comment]
No, I simply don't want to separate it from PneumaticCraft, not balance related in any way.
