### ISSUE TITLE
Support for Terrafirmacraft buckets

### ISSUE THREAD

**Issue by dexman545** [MineMaarten/PneumaticCraft#711]
I was wondering if it would be possible to add red/blue steel/wooden bucket variations of PC liquids for Terrafirmacraft. TFC removes the vanilla bucket, and therefore makes it normally impossible to obtain.

Thank you, 
Dex

**Comment by MineMaarten** [comment]
If TFC removes the normal bucket, I think it's only reasonable to state that TFC will have to come up with a solution.. I wonder why they don't auto-generate the buckets for instance.
