### ISSUE TITLE
[Suggestion] Elevator height upgrades

### ISSUE THREAD

**Issue by Axylxys** [MineMaarten/PneumaticCraft#713]
I know there's already a config option for the maximum height of an elevator, however it seemed surprising to me. Why not make it dynamic in game based on an upgrade system ? It could be the range upgrade for exemple, and would allow to adjust to what's needed for each elevator, as well as making it more balanced with cost for exemple.

I found the base height a bit low, and on the other hand stacking 20 layers of elevator bases or setting up the config to a crazy default amount that makes it look silly isn't really practical or fun, while the upgrade system looks like the perfect way to leave some adjustement room on this. Myabe something like, one upgrade = a layer of elevator bases, with a scaling cost based on the amount needed ? Or a specific upgrade involving elevator bases to balance the cost.

**Comment by notchriss** [comment]
I do not agree, I always find upgrade systems dull and boring. Stacking elevator basis ain't too fun either but it doesn't take long and it adds the feeling of some kind 'realism' :)

**Comment by MineMaarten** [comment]
Seeing I prefer the stacking system more, I won't implement a upgrade system as well (it's double). sorry!

**Comment by Vortiporius** [comment]
I have a tower from Bedrock to max height. In its current form for Minecraft 1.18.2, I cannot use this elevator for all of my floors. Already needing 96 elevator bases in height to go the full height of the tower, then needing to have it start a quarter of the way up the tower to even use it, it's pointless. I've spent hours on it, even tried glitching the bases beneath bedrock which I couldn't do. The stacking system is awful.

**Comment by Fayti1703** [comment]
@Vortiporius It looks like you're in the wrong repository; the current versions of this mod are in the  [TeamPneumatic/pnc-repressurized repository](https://github.com/TeamPneumatic/pnc-repressurized). You may want to [raise an issue there](https://github.com/TeamPneumatic/pnc-repressurized/issues).
