### ISSUE TITLE
Weird item placement when drone is exporting items

### ISSUE THREAD

**Issue by Forecaster** [MineMaarten/PneumaticCraft#715]
Instead of checking if there is already a stack of the same item with space in it when placing something into for example a chest, the drone will just place the item into the first valid slot, even if there is a stack of the same item in a later slot. It should try to find existing stacks no matter where they are first and place the items there to use the space as efficiently as possible.

**Comment by MineMaarten** [comment]
The placement isn't so 'weird'. afaik most mod's insertion methods work like this. Even Vanilla Hoppers do it. You might be confused with shift clicking in inventories, afaik the only place in Vanilla where this behaviour is used.

**Comment by Forecaster** [comment]
Maybe I just expect them to be smarter than a hopper ; )
