### ISSUE TITLE
New Chisel fork throwing an error/warning at startup

### ISSUE THREAD

**Issue by Hezer** [MineMaarten/PneumaticCraft#718]
Found this error line and didn't see it reported.

`[Client thread/ERROR] [PneumaticCraft/PneumaticCraft]: Neither Chisel 1 or Chisel 2's main mod class could be found, even though chisel is in the instance. Report to MineMaarten plax!`

I'm using 1.11.14-136 version of PneumaticCraft and the chisel is 2.9.1 version from this fork: http://minecraft.curseforge.com/projects/chisel

Also got this line after:
`[Client thread/ERROR] [PneumaticCraft/PneumaticCraft]: Chisel's ClientUtils inside ctmlib couldn't be found! No support for connected texture blocks for camouflage is given`

**Comment by MineMaarten** [comment]
Thanks for the report :). I'll look at fixing the support for this fork.

**Comment by chezpaul** [comment]
I still got this error:
[09:29:25] [Server thread/ERROR]: Chisel's ClientUtils inside ctmlib couldn't be found! No support for connected texture blocks for camouflage is given

Right after I installed the PneumaticCraft-1.7.10-1.12.2-145-universal mod onto my server.
Using Chisel-2.9.4.10

**Comment by MineMaarten** [comment]
It's literally the third issue that's open.... https://github.com/MineMaarten/PneumaticCraft/issues/766

**Comment by chezpaul** [comment]
Sorry, I had just done a google search and hit this issue directly.
