### ISSUE TITLE
Lubricant conflit with lubricant from hydraulicraft

### ISSUE THREAD

**Issue by Wykks** [MineMaarten/PneumaticCraft#720]
"Thermopneumatic Processing Plant" generate Lubricant from Hydraulicraft (why ?).

The issue comes when I try to make a "Speed upgrade" (from Pneumaticraft) which is supposed to take a lubricant bucket. It doesn't work because It's the one from Hydraulicraft.

I don't know if the craft of the speed upgrade is the only issue with Lubricant from hydraulicraft

**Comment by MineMaarten** [comment]
That's what the FluidRegistry should allow for. Now the real issue is the recipe not being able to deal with foreign buckets. I guess I should look for generic lubricant containers instead.

**Comment by JasonMcRay** [comment]
Similiar issue is happening in conjuntion with GregTech. When I process Diesel in the Processing Plant it gives me "some" lubricant. But I am unable to do anything with that lubricant, can't put it into buckets. Upon further inspection it indeed produces GT Lubricant.

@MineMaarten is the fix you done for this issue, also should fix that?

**Comment by MineMaarten** [comment]
If you have some way of getting some Lubricant bucket, it would be fixed yes. If you can't in the first place, then no.

**Comment by JasonMcRay** [comment]
GregTech doesnt add Lubricant Buckets, so the only Lubricant Bucket is available from PneumaticCraft, but since the Processing Plant creates GT Lubricant, I cant get the bucket at all.

**Comment by JasonMcRay** [comment]
Wouldn't be possible to make the PC Lubricant bucket "craftable" with use of any Lubricant from the FluidRegistry?
