### ISSUE TITLE
[Suggestion] Improve Temperature power

### ISSUE THREAD

**Issue by bluesaka111** [MineMaarten/PneumaticCraft#721]
Can you allow: 
+ Cool block temperature (which temperature below 5 degree celcius) to generate ice block as it contact with water and allow ice to spread (and increase spreading speed) as block temperature drop?

+ Hot block temperature (which temperature above 100 degree celcius) to act as lava and increase  power as temperature raise (ex: at 2000 degree celcius allow water turn into cobble stone and set anything that contact with hot block surface on fire)?

I would love to know what you think about my suggest and sorry about my english skill :(

**Comment by MineMaarten** [comment]
As of recent versions this is already happening, apart from the spreading part. And I don't like the sound of spreading, for gameplay reasons (it could be perceived as very annoying).
