### ISSUE TITLE
Vortex Tube heating up without pressurized air being supplied

### ISSUE THREAD

**Issue by DenTommes** [MineMaarten/PneumaticCraft#728]
I'm playing PneumaticCraft in the Infitech 2 Modpack and just encountered an issue:

![2015-10-08_16 31 14](https://cloud.githubusercontent.com/assets/12441387/10369380/3ec9b6e4-6dda-11e5-8b2c-97a10f1e332a.png)

The vortex tube heated to over 900C without any pressure beeing supplied to it.

I was trying to make a compact design for Gasoline production.

I'm currently trying to replicate the issue, but so far to no avail.

**Comment by MineMaarten** [comment]
Weeeeeird... But yes, I'd love to hear about a reliable way to reproduce it...

**Comment by DenTommes** [comment]
I tried reproducing the bug, but even when copying the exact same layout to another location, it never heated up again as much as in the above screenshot.

I tried breaking stuff around the original design, when I broke the torch beneath the thermopneumatic plant, the temperature dropped radically, so the torch is heating up the plant, which in return is heating up the vortex tube.

Replacing the torch brought the temperature slowly back up to 1400°C

I then proceeded to break other blocks around the vortex tube, when destroying enough blocks around it, it started to cool down. after replacing blocks it did not heat up again.

I was a little frustrated as I couldn't figure out a way to reproduce it, so I worked again in my SP world. I tried to copy the design and actually managed to get a vortex tube up to over 300°C without the use of pressurized air.

![2015-10-11_09 44 27](https://cloud.githubusercontent.com/assets/12441387/10415983/6359a490-7002-11e5-8589-738f4664eb46.png)


I started with a thermo-plant above a torch, connected to a vortex Tube on it's warm side.
it heated up to 71/43

 Blocking the cold side with a block, redstone dust for example resulted heated the Vortex tube up to 94/94
![2015-10-11_10 03 50](https://cloud.githubusercontent.com/assets/12441387/10415928/b3fa6ca2-6fff-11e5-8ce7-dcc2cd8f13da.png)

But no matter how many torches i placed around it, it got newer above this mark

I replaced the redstone with a torch, now reaching 160/240
Close, but that's not enough and there wasn't a torch on the cold side of the vortex tube when the problem surfaced for the first time.

I now started to block off the other sides of the design as the temperature only started to rise after I placed the buildcraft pipes in my SP world.

But, alas, it didn't help...

I then took a closer look at my second screenshot and saw another torch close to the thermo-plant:

Aaaand... the temperature started to run away!

I could even replace the torch behind the vortex tube with redstone and it still would keep on heating up
![2015-10-11_11 02 12](https://cloud.githubusercontent.com/assets/12441387/10416119/47ae6eaa-7008-11e5-8e18-c6677d202049.png)

I then removed the last placed torch after the tube heated up to above 1000°C and the temperature wouldn't drop down anymore!

**Comment by MineMaarten** [comment]
Yes, the torches are key here. I didn't realized they were there in the initial screenshot. This doesn't sound like a bug really, it's intented that when fully enclosed, no heat is lost, and therefore, a heat source will eventually bring up the temperature of a system to its temperature.

Now the thermal resistance of torches I've made very high, so while it's possible to get to a certain temperature, I wonder how fast you can _keep_ de thermopneumatic processing plant running. I want to say (and I hope) that it doesn't last for long, and the temperature will drop quickly to a point where the plant is running very slowly.

It would be really appreciate it if you could confirm this. If this is the case, the torches don't need nerfing. If it does run smoothly, I will have to, as ofc this is too easy ;).

**Comment by DenTommes** [comment]
I'm surprised that this is intentional behavior, I thought torches would just be able to increase temperature to a certain point.
But I'm sure you need to nerf the torches.

I'm currently testing how well the torch powered thermo-plant keeps up with a refinery running at maximum speed.

So far, it's not a problem, but just to be sure, there's no other method to get the refinery to run faster except by increasing it's temperature?

The refinery runs at 1600°C, the thermo-plant processes Diesel to Kerosene
![2015-10-11_11 59 59](https://cloud.githubusercontent.com/assets/12441387/10416257/9e21cb86-700f-11e5-8fcc-236f1ad2c035.png)

**Comment by mineguy46** [comment]
Torches are definitely overpowered at the moment, you can place a block of compressed iron next to a furnace, put torches around it and the furnace will run forever. Smelting each item in about 1.5 seconds.
![2015-10-12_10 45 40](https://cloud.githubusercontent.com/assets/11164711/10430689/89a4590c-70ce-11e5-8ae8-b50cc4691deb.png)
![2015-10-12_10 45 43](https://cloud.githubusercontent.com/assets/11164711/10430690/89a5493e-70ce-11e5-8ec1-32f568f4c91d.png)
![2015-10-12_10 45 47](https://cloud.githubusercontent.com/assets/11164711/10430691/89a751b6-70ce-11e5-9629-57f0056b225c.png)
