### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by PalePyth** [MineMaarten/PneumaticCraft#731]
---- Minecraft Crash Report ----
// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 10.10.15 14:44
Description: Exception in server tick loop

java.lang.NullPointerException: Exception in server tick loop
at net.minecraft.world.chunk.storage.ExtendedBlockStorage.func_150818_a(SourceFile:57)
at net.minecraft.world.chunk.Chunk.func_150807_a(Chunk.java:595)
at net.minecraft.world.World.func_147465_d(World.java:451)
at net.minecraft.world.gen.feature.WorldGenLakes.func_76484_a(SourceFile:79)
at pneumaticCraft.common.worldgen.WorldGeneratorPneumaticCraft.generateSurface(WorldGeneratorPneumaticCraft.java:44)
at pneumaticCraft.common.worldgen.WorldGeneratorPneumaticCraft.generate(WorldGeneratorPneumaticCraft.java:27)
at cpw.mods.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java:112)
at net.minecraft.world.gen.ChunkProviderServer.func_73153_a(ChunkProviderServer.java:280)
at fastcraft.a.d.a(F:84)
at fastcraft.Hooks.r(F:137)
at net.minecraft.world.chunk.Chunk.func_76624_a(Chunk.java:1055)
at net.minecraft.world.gen.ChunkProviderServer.originalLoadChunk(ChunkProviderServer.java:190)
at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:131)
at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:101)
at net.minecraft.server.MinecraftServer.func_71222_d(MinecraftServer.java:265)
at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:78)
at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:92)
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387)
at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
Minecraft Version: 1.7.10
Operating System: Windows 8.1 (amd64) version 6.3
Java Version: 1.8.0_45, Oracle Corporation
Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
Memory: 497812632 bytes (474 MB) / 1149145088 bytes (1095 MB) up to 2134114304 bytes (2035 MB)
JVM Flags: 11 total; -XX:HeapDumpPath=ThisTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2048M -XX:-UseAdaptiveSizePolicy -XX:-UseGCOverheadLimit -XX:+UseConcMarkSweepGC -XX:+CMSParallelRemarkEnabled -XX:+ParallelRefProcEnabled -XX:+CMSClassUnloadingEnabled -XX:+UseCMSInitiatingOccupancyOnly -Xmn128M -Xms256M
AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1492 65 mods loaded, 65 mods active
States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
UCHIJAA mcp{9.05} [Minecraft Coder Pack] (minecraft.jar)
UCHIJAA FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1492-1.7.10.jar)
UCHIJAA Forge{10.13.4.1492} [Minecraft Forge] (forge-1.7.10-10.13.4.1492-1.7.10.jar)
UCHIJAA appliedenergistics2-core{rv2-stable-10} [AppliedEnergistics2 Core] (minecraft.jar)
UCHIJAA CodeChickenCore{1.0.7.47} [CodeChicken Core] (minecraft.jar)
UCHIJAA NotEnoughItems{1.0.5.111} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.5.111-universal.jar)
UCHIJAA OpenComputers|Core{1.5.18.36} [OpenComputers (Core)] (minecraft.jar)
UCHIJAA WarpDriveCore{1.0.0.1} [WarpDriveCore] (minecraft.jar)
UCHIJAA {000} [CoFH ASM] (minecraft.jar)
UCHIJAA IC2{2.2.765-experimental} [IndustrialCraft 2] (industrialcraft-2-2.2.765-experimental.jar)
UCHIJAA ImmibisCore{59.1.2} [Immibis Core] (immibis-core-59.1.2.jar)
UCHIJAA AdvancedRepulsionSystems{59.0.3} [Advanced Repulsion Systems] (adv-repulsion-systems-59.0.3.jar)
UCHIJAA AgriCraft{1.7.10-1.3.1} [AgriCraft] (AgriCraft-1.7.10-1.3.1.jar)
UCHIJAA AppleCore{1.1.0} [AppleCore] (AppleCore-mc1.7.10-1.1.0.jar)
UCHIJAA appliedenergistics2{rv2-stable-10} [Applied Energistics 2] (appliedenergistics2-rv2-stable-10.jar)
UCHIJAA CoFHCore{1.7.10R3.0.3} [CoFH Core] (CoFHCore-[1.7.10]3.0.3-303.jar)
UCHIJAA Forestry{3.6.3.20} [Forestry for Minecraft] (forestry_1.7.10-3.6.3.20.jar)
UCHIJAA harvestcraft{1.7.10j} [Pam's HarvestCraft] (Pam's HarvestCraft 1.7.10j.jar)
UCHIJAA Railcraft{9.7.0.0} [Railcraft] (Railcraft_1.7.10-9.7.0.0.jar)
UCHIJAA gregtech{MC1710} [GregTech] (gregtech_1.7.10-5.09.01.jar)
UCHIJAA asielib{0.4.2} [asielib] (AsieLib-1.7.10-0.4.2.jar)
UCHIJAA bdlib{1.9.0.94} [BD Lib] (bdlib-1.9.0.94-mc1.7.10.jar)
UCHIJAA CarpentersBlocks{3.3.6} [Carpenter's Blocks] (Carpenter's Blocks v3.3.6 - MC 1.7.10.jar)
UCHIJAA ForgeMultipart{1.2.0.345} [Forge Multipart] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar)
UCHIJAA chisel{2.5.0.43} [Chisel 2] (Chisel2-2.5.0.43.jar)
UCHIJAA ComputerCraft{1.74} [ComputerCraft] (ComputerCraft1.74.jar)
UCHIJAA OpenComputers{1.5.18.36} [OpenComputers] (OpenComputers-MC1.7.10-1.5.18.36-universal.jar)
UCHIJAA MrTJPCoreMod{1.1.0.31} [MrTJPCore] (MrTJPCore-1.1.0.31-universal.jar)
UCHIJAA ProjRed|Core{4.7.0pre9.92} [ProjectRed Core] (ProjectRed-1.7.10-4.7.0pre9.92-Base.jar)
UCHIJAA Waila{1.5.10} [Waila] (Waila-1.5.10_1.7.10.jar)
UCHIJAA computronics{1.5.7} [Computronics] (Computronics-1.7.10-1.5.7.jar)
UCHIJAA enviromine{1.3.121} [EnviroMine] (EnviroMine-1.3.121.jar)
UCHIJAA extracells{2.2.73} [Extra Cells 2] (ExtraCells-1.7.10-2.2.73b129.jar)
UCHIJAA FastCraft{1.21} [FastCraft] (fastcraft-1.21.jar)
UCHIJAA ForgeRelocation{0.0.1.2} [ForgeRelocation] (ForgeRelocation-1.7.10-0.0.1.2-universal.jar)
UCHIJAA MCFrames{1.0} [MCFrames] (ForgeRelocation-1.7.10-0.0.1.2-universal.jar)
UCHIJAA RelocationFMP{0.0.1.2} [RelocationFMP] (ForgeRelocationFMP-1.7.10-0.0.1.2-universal.jar)
UCHIJAA gendustry{1.5.2.107} [GenDustry] (gendustry-1.5.2.107-mc1.7.10.jar)
UCHIJAA GregsLighting{1.11.2} [Greg's Lighting] (GregsLighting-1.11.2-mc1.7.10.jar)
UCHIJAA GTTweaker{1.0.9} [GTTweaker] (GTTweaker-1.7.10-1.0.9.jar)
UCHIJAA HardcoreDarkness{1.6} [Hardcore Darkness] (HardcoreDarkness-MC1.7.10-1.6.jar)
UCHIJAA HoloInventory{1.9.1.122} [HoloInventory] (HoloInventory-1.7.10-1.9.1.122.jar)
UCHIJAA IC2CA{1.14.5.03} [IndustrialCraft 2 Combo Armors] (ic2ca-1.7.10-1.14.5.03.jar)
UCHIJAA IC2NuclearControl{2.2.5a-GoingForTheKill} [Nuclear Control 2] (IC2NuclearControl-2.2.5a-GoingForTheKill.jar)
UCHIJAA LunatriusCore{1.1.2.21} [LunatriusCore] (LunatriusCore-1.7.10-1.1.2.21-universal.jar)
UCHIJAA InGameInfoXML{2.8.1.82} [InGame Info XML] (InGameInfoXML-1.7.10-2.8.1.82-universal.jar)
UCHIJAA inpure|core{1.7.10R1.0.0B9} [INpureCore] (INpureCore-[1.7.10]1.0.0B9-62.jar)
UCHIJAA JABBA{1.2.1} [JABBA] (Jabba-1.2.1a_1.7.10.jar)
UCHIJAA journeymap{@JMVERSION@} [JourneyMap] (journeymap-1.7.10-5.1.0-fairplay.jar)
UCHIJAA MineTweaker3{3.0.10} [MineTweaker 3] (MineTweaker3-1.7.10-3.0.10.jar)
UCHIJAA modtweaker2{0.9.2} [Mod Tweaker 2] (ModTweaker2-0.9.3.jar)
UCHIJAA numina{0.4.0.100} [Numina] (Numina-0.4.0.100.jar)
UCHIJAA powersuits{0.11.0.177} [MachineMuse's Modular Powersuits] (ModularPowersuits-0.11.0.177.jar)
UCHIJAA notenoughkeys{@MOD_VERSION@} [NotEnoughKEys] (NotEnoughKeys-1.7.10-1.0.0b30.jar)
UCHIJAA openmodularturrets{2.1.3-163} [Open Modular Turrets] (OpenModularTurrets-1.7.10-2.1.3-163.jar)
UCHIJAA plasmacraft{0.3.5-beta2} [PlasmaCraft] (PlasmaCraft-0.3.5-beta2.jar)
UCHIJAA PneumaticCraft{1.11.16-138} [PneumaticCraft] (PneumaticCraft-1.7.10-1.11.16-138-universal.jar)
UCHIJAA SpecialAI{1.1.1} [Special AI] (SpecialAI-1.7.10-1.1.1.jar)
UCHIJAA SpiceOfLife{1.2.4} [The Spice of Life] (SpiceOfLife-mc1.7.10-1.2.4.jar)
UCHIJAA toolbox{1.2.3} [Toolbox] (Toolbox-1.7.10-1.2.3.jar)
UCHIJAA WarpDrive{1.0.0} [WarpDrive] (WarpDrive-1.7.10-1.0.8.jar)
UCHIJAA bspkrsCore{6.16} [bspkrsCore] ([1.7.10]bspkrsCore-universal-6.16.jar)
UCHIJAA McMultipart{1.2.0.345} [Minecraft Multipart Plugin] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar)
UCHIJAA HungerOverhaul{1.7.10-1.0.0.jenkins75} [Hunger Overhaul] (HungerOverhaul-1.7.10-1.0.0.jar)
UCHIJAA ForgeMicroblock{1.2.0.345} [Forge Microblocks] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar)
GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
AE2 Version: stable rv2-stable-10 for Forge 10.13.2.1291
CoFHCore: -[1.7.10]3.0.3-303
List of loaded APIs:
* API_NEK (1.0.0) from NotEnoughKeys-1.7.10-1.0.0b30.jar
* AppleCoreAPI (1.1.0) from AppleCore-mc1.7.10-1.1.0.jar
* appliedenergistics2|API (rv2) from appliedenergistics2-rv2-stable-10.jar
* asielibAPI (1.1) from AsieLib-1.7.10-0.4.2.jar
* asielibAPI|chat (1.0) from AsieLib-1.7.10-0.4.2.jar
* asielibAPI|tile (1.0) from AsieLib-1.7.10-0.4.2.jar
* asielibAPI|tool (1.1) from AsieLib-1.7.10-0.4.2.jar
* BuildCraftAPI|core (1.4) from Railcraft_1.7.10-9.7.0.0.jar
* BuildCraftAPI|items (1.0) from Railcraft_1.7.10-9.7.0.0.jar
* BuildCraftAPI|statements (1.0) from Railcraft_1.7.10-9.7.0.0.jar
* BuildCraftAPI|tiles (1.1) from Railcraft_1.7.10-9.7.0.0.jar
* BuildCraftAPI|tools (1.0) from forestry_1.7.10-3.6.3.20.jar
* BuildCraftAPI|transport (4.0) from Railcraft_1.7.10-9.7.0.0.jar
* ChiselAPI (0.1.0) from Chisel2-2.5.0.43.jar
* ChiselAPI|Carving (0.1.0) from Chisel2-2.5.0.43.jar
* ChiselAPI|Rendering (0.1.0) from Chisel2-2.5.0.43.jar
* CoFHAPI (1.7.10R1.0.13) from CoFHCore-[1.7.10]3.0.3-303.jar
* CoFHAPI|block (1.7.10R1.0.13) from CoFHCore-[1.7.10]3.0.3-303.jar
* CoFHAPI|core (1.7.10R1.0.13) from CoFHCore-[1.7.10]3.0.3-303.jar
* CoFHAPI|energy (1.7.10R1.0.2) from IC2NuclearControl-2.2.5a-GoingForTheKill.jar
* CoFHAPI|fluid (1.7.10R1.0.13) from CoFHCore-[1.7.10]3.0.3-303.jar
* CoFHAPI|inventory (1.7.10R1.0.13) from CoFHCore-[1.7.10]3.0.3-303.jar
* CoFHAPI|item (1.7.10R1.0.13) from CoFHCore-[1.7.10]3.0.3-303.jar
* CoFHAPI|modhelpers (1.7.10R1.0.13) from CoFHCore-[1.7.10]3.0.3-303.jar
* CoFHAPI|tileentity (1.7.10R1.0.13) from CoFHCore-[1.7.10]3.0.3-303.jar
* CoFHAPI|transport (1.7.10R1.0.13) from CoFHCore-[1.7.10]3.0.3-303.jar
* CoFHAPI|world (1.7.10R1.0.13) from CoFHCore-[1.7.10]3.0.3-303.jar
* CoFHLib (1.7.10R1.0.3) from CoFHCore-[1.7.10]3.0.3-303.jar
* CoFHLib|audio (1.7.10R1.0.3) from CoFHCore-[1.7.10]3.0.3-303.jar
* CoFHLib|gui (1.7.10R1.0.3) from CoFHCore-[1.7.10]3.0.3-303.jar
* CoFHLib|gui|container (1.7.10R1.0.3) from CoFHCore-[1.7.10]3.0.3-303.jar
* CoFHLib|gui|element (1.7.10R1.0.3) from CoFHCore-[1.7.10]3.0.3-303.jar
* CoFHLib|gui|element|listbox (1.7.10R1.0.3) from CoFHCore-[1.7.10]3.0.3-303.jar
* CoFHLib|gui|slot (1.7.10R1.0.3) from CoFHCore-[1.7.10]3.0.3-303.jar
* CoFHLib|inventory (1.7.10R1.0.3) from CoFHCore-[1.7.10]3.0.3-303.jar
* CoFHLib|render (1.7.10R1.0.3) from CoFHCore-[1.7.10]3.0.3-303.jar
* CoFHLib|render|particle (1.7.10R1.0.3) from CoFHCore-[1.7.10]3.0.3-303.jar
* CoFHLib|util (1.7.10R1.0.3) from CoFHCore-[1.7.10]3.0.3-303.jar
* CoFHLib|util|helpers (1.7.10R1.0.3) from CoFHCore-[1.7.10]3.0.3-303.jar
* CoFHLib|util|position (1.7.10R1.0.3) from CoFHCore-[1.7.10]3.0.3-303.jar
* CoFHLib|world (1.7.10R1.0.3) from CoFHCore-[1.7.10]3.0.3-303.jar
* CoFHLib|world|feature (1.7.10R1.0.3) from CoFHCore-[1.7.10]3.0.3-303.jar
* ComputerCraft|API (1.74) from ComputerCraft1.74.jar
* ComputerCraft|API|FileSystem (1.74) from ComputerCraft1.74.jar
* ComputerCraft|API|Lua (1.74) from ComputerCraft1.74.jar
* ComputerCraft|API|Media (1.74) from ComputerCraft1.74.jar
* ComputerCraft|API|Peripheral (1.74) from ComputerCraft1.74.jar
* ComputerCraft|API|Permissions (1.74) from ComputerCraft1.74.jar
* ComputerCraft|API|Redstone (1.74) from ComputerCraft1.74.jar
* ComputerCraft|API|Turtle (1.74) from ComputerCraft1.74.jar
* computronicsAPI (1.3) from Computronics-1.7.10-1.5.7.jar
* computronicsAPI|chat (1.3) from Computronics-1.7.10-1.5.7.jar
* computronicsAPI|multiperipheral (1.1) from Computronics-1.7.10-1.5.7.jar
* computronicsAPI|tape (1.0) from Computronics-1.7.10-1.5.7.jar
* ForestryAPI|apiculture (3.5.0) from forestry_1.7.10-3.6.3.20.jar
* ForestryAPI|arboriculture (2.3.0) from forestry_1.7.10-3.6.3.20.jar
* ForestryAPI|circuits (2.0.0) from forestry_1.7.10-3.6.3.20.jar
* ForestryAPI|core (3.2.0) from forestry_1.7.10-3.6.3.20.jar
* ForestryAPI|farming (1.1.0) from forestry_1.7.10-3.6.3.20.jar
* ForestryAPI|food (1.1.0) from forestry_1.7.10-3.6.3.20.jar
* ForestryAPI|fuels (2.0.1) from forestry_1.7.10-3.6.3.20.jar
* ForestryAPI|genetics (3.3.0) from forestry_1.7.10-3.6.3.20.jar
* ForestryAPI|hives (4.1.0) from forestry_1.7.10-3.6.3.20.jar
* ForestryAPI|lepidopterology (1.1) from forestry_1.7.10-3.6.3.20.jar
* ForestryAPI|mail (3.0.0) from forestry_1.7.10-3.6.3.20.jar
* ForestryAPI|recipes (3.1.0) from forestry_1.7.10-3.6.3.20.jar
* ForestryAPI|storage (3.0.0) from forestry_1.7.10-3.6.3.20.jar
* ForestryAPI|world (1.1.0) from forestry_1.7.10-3.6.3.20.jar
* ForgeRelocation|API (0.0.1a) from ForgeRelocation-1.7.10-0.0.1.2-universal.jar
* gendustryAPI (2.1.0) from gendustry-1.5.2.107-mc1.7.10.jar
* IC2API (1.0) from industrialcraft-2-2.2.765-experimental.jar
* inpure|api (1.7) from INpureCore-[1.7.10]1.0.0B9-62.jar
* NuclearControlAPI (v1.0.5) from IC2NuclearControl-2.2.5a-GoingForTheKill.jar
* OpenComputersAPI|Component (5.6.2) from OpenComputers-MC1.7.10-1.5.18.36-universal.jar
* OpenComputersAPI|Core (5.6.2) from OpenComputers-MC1.7.10-1.5.18.36-universal.jar
* OpenComputersAPI|Driver (5.6.2) from OpenComputers-MC1.7.10-1.5.18.36-universal.jar
* OpenComputersAPI|Driver|Item (5.6.2) from OpenComputers-MC1.7.10-1.5.18.36-universal.jar
* OpenComputersAPI|Event (5.6.2) from OpenComputers-MC1.7.10-1.5.18.36-universal.jar
* OpenComputersAPI|FileSystem (5.6.2) from OpenComputers-MC1.7.10-1.5.18.36-universal.jar
* OpenComputersAPI|Internal (5.6.2) from OpenComputers-MC1.7.10-1.5.18.36-universal.jar
* OpenComputersAPI|Machine (5.6.2) from OpenComputers-MC1.7.10-1.5.18.36-universal.jar
* OpenComputersAPI|Manual (5.6.2) from OpenComputers-MC1.7.10-1.5.18.36-universal.jar
* OpenComputersAPI|Network (5.6.2) from OpenComputers-MC1.7.10-1.5.18.36-universal.jar
* OpenComputersAPI|Prefab (5.6.2) from OpenComputers-MC1.7.10-1.5.18.36-universal.jar
* PneumaticCraftApi (1.0) from PneumaticCraft-1.7.10-1.11.16-138-universal.jar
* RailcraftAPI|bore (1.0.0) from Railcraft_1.7.10-9.7.0.0.jar
* RailcraftAPI|carts (1.5.0) from Railcraft_1.7.10-9.7.0.0.jar
* RailcraftAPI|core (1.4.0) from Railcraft_1.7.10-9.7.0.0.jar
* RailcraftAPI|crafting (1.0.0) from Railcraft_1.7.10-9.7.0.0.jar
* RailcraftAPI|electricity (1.6.0) from Railcraft_1.7.10-9.7.0.0.jar
* RailcraftAPI|events (1.0.0) from Railcraft_1.7.10-9.7.0.0.jar
* RailcraftAPI|fuel (1.0.0) from Railcraft_1.7.10-9.7.0.0.jar
* RailcraftAPI|helpers (1.1.0) from Railcraft_1.7.10-9.7.0.0.jar
* RailcraftAPI|items (1.0.0) from Railcraft_1.7.10-9.7.0.0.jar
* RailcraftAPI|locomotive (1.0.1) from Railcraft_1.7.10-9.7.0.0.jar
* RailcraftAPI|signals (1.3.4) from Railcraft_1.7.10-9.7.0.0.jar
* RailcraftAPI|tracks (2.0.0) from Railcraft_1.7.10-9.7.0.0.jar
* Thaumcraft|API (4.2.2.0) from Railcraft_1.7.10-9.7.0.0.jar
* WailaAPI (1.2) from Waila-1.5.10_1.7.10.jar
AE2 Integration: IC2:ON, RotaryCraft:OFF, RC:ON, BC:OFF, RF:ON, RFItem:ON, MFR:OFF, DSU:ON, FZ:OFF, FMP:ON, RB:OFF, CLApi:OFF, Waila:ON, InvTweaks:OFF, NEI:ON, CraftGuide:OFF, Mekanism:OFF, ImmibisMicroblocks:OFF, BetterStorage:OFF
Profiler Position: N/A (disabled)
Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
Player Count: 0 / 8; []
Type: Integrated Server (map_client.txt)
Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by MineMaarten** [comment]
Can't reproduce

**Comment by PalePyth** [comment]
Get my modpack there https://dropmefiles.com/k3blH to reproduce.
I want you to fix it.

**Comment by MineMaarten** [comment]
Try asking nicely next time. A demand won't get me motivated. Neither does a plain crash without any explanation whatsoever. Obviously it's an inter-mod issue, as it doesn't happen with just PneumaticCraft. At that point it's for you to find out which mod is not working well with PneumaticCraft.

**Comment by SvEgiiVEteR** [comment]
https://github.com/MineMaarten/PneumaticCraft/issues/822
