### ISSUE TITLE
[Feature Suggestion] [Issue Tracker] Pasted Stacktrace Line

### ISSUE THREAD

**Issue by Fayti1703** [MineMaarten/PneumaticCraft#733]
I just had an idea, not related to the mod itself, but to the issue tracker:
If we were to see a bug report with a Stacktrace/Crashreport pasted in 
(not using pastebin, just put in like <insert wall of text here>),
the first comment to be made would be something like "(Holy cow)  we just won the lottery!", maybe with a link to explain what the reporter just did wrong.

I think this would be a funny little detail. Feel free to close this issue due to it being unrelated.

**Comment by MineMaarten** [comment]
imo it's a bit silly, and too less of a nuisance, too much work, and too less of a gain.
