### ISSUE TITLE
Galacticraft oil not accepted by Refinery

### ISSUE THREAD

**Issue by JasonMcRay** [MineMaarten/PneumaticCraft#734]
Galacticraft mod is adding an underground oil fields (similiar to PC). This oil can't be processed by PC Refinery (it behaves as normal oil (like Buildcraft or PneumaticCraft)).

**Comment by MineMaarten** [comment]
Version? As I had fixed this recently?

**Comment by JasonMcRay** [comment]
PC: 1.11.14-136
Galacticraft: 3.0.12.357

**Comment by JasonMcRay** [comment]
Also now tested with PC 1.11.16-138

The name of the oil is fluid.oilgc

**Comment by MineMaarten** [comment]
Oh, in that case it's really Galacticraft's issue for not to be compatible with 'oil', the 'normal' Oil name BC, PneumaticCraft and others use.

**Comment by JasonMcRay** [comment]
You are correct. I just noticed that GC just fixed something with their oil. Sorry for false report.
