### ISSUE TITLE
Add Biofuel/Biomass support to the Liquid Compressor

### ISSUE THREAD

**Issue by cornytrace** [MineMaarten/PneumaticCraft#735]
When placing down a liquid compressor, and trying to put in various fluids like Buildcraft Oil, Steam, Buildcraft fuel, Minefactory reloaded BioFuel, it wont accept them. It does accept normal lava and the PneumaticCraft fuels.
The Buildcraft fuel not working was understandable as it wasnt on the list, however, since it is equivalent to Gasoline, and there is already BC compatibility, wouldn't adding support be simple?
The BC Oil also doesnt seem to be supported, while there is support for it in the Refinery?
Biofuel also wasn't on the list but adding support for it would be nice as it is identical to Biomass.

There are also two different steam entries in the supported fuels entry with different values. As other mods unify all different steam liquids into one, and freely convert between them, it would be easier for the user if all Steam would only have one entry. Furthermore, it seems Thermal Foundation Steam is not supported.

I hope that adding these liquids doesn't take much effort, as it will massively increase mod interoperability and ease of pneumaticcraft earlygame if you already have an existing power system.

The 1.7.10 pack version 0.8.1
PneumaticCraft version 1.7.10-1.11.13-135

**Comment by MineMaarten** [comment]
Sigh... *grumbles about bug reports using older versions* http://minecraft.curseforge.com/projects/pneumaticcraft/files/2260927

As far as I can see the only thing missing is the biofuel/biomass support.

**Comment by MineMaarten** [comment]
After looking at the code, it turns out it biomass+biofuel was supported already.
