### ISSUE TITLE
Add liquid condition

### ISSUE THREAD

**Issue by Forecaster** [MineMaarten/PneumaticCraft#737]
For testing if area contains fluid blocks, which currently is not possible for most fluids.

**Comment by Tekstack** [comment]
Workaround - Condition block check for Air; i.e. Block >=1 Air (Any or all) then export liquid?

**Comment by MineMaarten** [comment]
We talked about this on IRC, apart from liquid blocks it would check on tanks, which was a missing thing anyway already.
