### ISSUE TITLE
[Suggestion] Add Block/Item/or Command to recall all Drones by Owner

### ISSUE THREAD

**Issue by Tekstack** [MineMaarten/PneumaticCraft#739]
With large networks of drones/complicated routines covering many blocks, sometimes a drone may go missing due to programming errors on part of the user and or other issues. It would be good to be able to recall the drones (especially useful for people just starting out programming drones given the overall early expense of everything needed to craft the precious drone). Also, as a server Owner, I have used drones in the past to enter corrupted chunks to destroy blocks causing issues without having to use MCedit (often not having the exact cords of the block but an "idea" or range) or out of range for world edit. A simple command to print the cords of all drones active by owner or all active named owner drones (i.e. "Logger") would be sufficient as well. Just food for thought!

**Comment by MineMaarten** [comment]
I'm not sure...

>With large networks of drones/complicated routines covering many blocks, sometimes a drone may go missing due to programming errors on part of the user and or other issues.

If using drones as exensively as described, it isn't that much more expensive to just add a 'goto $owner' when a certain global variable is set, into the main routine.

>especially useful for people just starting out programming drones given the overall early expense of everything needed to craft the precious drone

At that point programs aren't that complicated, and when things do go wrong, the chances are muuuch higher for the drone to end up in a non-chunkloaded area, at which point a way to recall drones won't help anyway.

>as a server Owner, I have used drones in the past to enter corrupted chunks to destroy blocks causing issues without having to use MCedit

Drones aren't really meant for that. However, you can log their current position by setting a global variable to the location of the drone $drone. This you can then display using a Remote. I suggest looking at IGW-Mod for more info.
