### ISSUE TITLE
tool tip boxes crash world (1.7.10)

### ISSUE THREAD

**Issue by burntbagle198** [MineMaarten/PneumaticCraft#740]
When ever i click on any of the tool tip boxes in any of the PneumaticCraft machine GUI's the game saves and quits to the menu.

since it didn't crash it didn't generate a crash report so ill past the relevant text from the console below

\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
-----------------------------------------------------------------
[B#328] [19:17:47] [Server thread/ERROR] [FML]: There was a critical exception handling a packet on channel PneumaticCraft
[B#328] java.lang.NullPointerException
[B#328] at cpw.mods.fml.common.network.FMLOutboundHandler$OutboundTarget$7.selectNetworks(FMLOutboundHandler.java:193) ~[FMLOutboundHandler$OutboundTarget$7.class:?]
[B#328] at cpw.mods.fml.common.network.FMLOutboundHandler.write(FMLOutboundHandler.java:273) ~[FMLOutboundHandler.class:?]
[B#328] at io.netty.channel.DefaultChannelHandlerContext.invokeWrite(DefaultChannelHandlerContext.java:644) ~[DefaultChannelHandlerContext.class:?]
[B#328] at io.netty.channel.DefaultChannelHandlerContext.write(DefaultChannelHandlerContext.java:698) ~[DefaultChannelHandlerContext.class:?]
[B#328] at io.netty.channel.DefaultChannelHandlerContext.write(DefaultChannelHandlerContext.java:637) ~[DefaultChannelHandlerContext.class:?]
[B#328] at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:115) ~[MessageToMessageEncoder.class:?]
[B#328] at io.netty.handler.codec.MessageToMessageCodec.write(MessageToMessageCodec.java:116) ~[MessageToMessageCodec.class:?]
[B#328] at io.netty.channel.DefaultChannelHandlerContext.invokeWrite(DefaultChannelHandlerContext.java:644) ~[DefaultChannelHandlerContext.class:?]
[B#328] at io.netty.channel.DefaultChannelHandlerContext.write(DefaultChannelHandlerContext.java:698) ~[DefaultChannelHandlerContext.class:?]
[B#328] at io.netty.channel.DefaultChannelHandlerContext.writeAndFlush(DefaultChannelHandlerContext.java:688) ~[DefaultChannelHandlerContext.class:?]
[B#328] at io.netty.channel.DefaultChannelHandlerContext.writeAndFlush(DefaultChannelHandlerContext.java:717) ~[DefaultChannelHandlerContext.class:?]
[B#328] at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:893) ~[DefaultChannelPipeline.class:?]
[B#328] at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:239) ~[AbstractChannel.class:?]
[B#328] at cpw.mods.fml.common.network.simpleimpl.SimpleNetworkWrapper.sendToAllAround(SimpleNetworkWrapper.java:210) ~[SimpleNetworkWrapper.class:?]
[B#328] at pneumaticCraft.common.network.NetworkHandler.sendToAllAround(NetworkHandler.java:123) ~[NetworkHandler.class:?]
[B#328] at pneumaticCraft.common.EventHandlerPneumaticCraft.onMobTargetSet(EventHandlerPneumaticCraft.java:260) ~[EventHandlerPneumaticCraft.class:?]
[B#328] at cpw.mods.fml.common.eventhandler.ASMEventHandler_449_EventHandlerPneumaticCraft_onMobTargetSet_LivingSetAttackTargetEvent.invoke(.dynamic) ~[?:?]
[B#328] at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:?]
[B#328] at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138) ~[EventBus.class:?]
[B#328] at net.minecraftforge.common.ForgeHooks.onLivingSetAttackTarget(ForgeHooks.java:282) ~[ForgeHooks.class:?]
[B#328] at net.minecraft.entity.EntityLivingBase.func_70604_c(EntityLivingBase.java:379) ~[sv.class:?]
[B#328] at net.minecraft.entity.EntityLivingBase.func_70097_a(EntityLivingBase.java:796) ~[sv.class:?]
[B#328] at net.minecraft.entity.monster.EntityMob.func_70097_a(SourceFile:54) ~[yg.class:?]
[B#328] at net.minecraft.world.Explosion.func_77278_a(Explosion.java:138) ~[agw.class:?]
[B#328] at net.minecraft.world.World.func_72885_a(World.java:2412) ~[ahb.class:?]
[B#328] at net.minecraft.world.World.func_72876_a(World.java:2403) ~[ahb.class:?]
[B#328] at com.domochevsky.quiverbow.weapons.PowderKnuckle.func_77648_a(PowderKnuckle.java:52) ~[PowderKnuckle.class:?]
[B#328] at net.minecraftforge.common.ForgeHooks.onPlaceItemIntoWorld(ForgeHooks.java:505) ~[ForgeHooks.class:?]
[B#328] at net.minecraft.item.ItemStack.func_77943_a(ItemStack.java:128) ~[add.class:?]
[B#328] at net.jamezo97.clonecraft.build.BlockItemRegistry.init2(BlockItemRegistry.java:148) ~[BlockItemRegistry.class:?]
[B#328] at net.jamezo97.clonecraft.build.BlockItemRegistry.init(BlockItemRegistry.java:236) ~[BlockItemRegistry.class:?]
[B#328] at net.jamezo97.clonecraft.CloneCraft.postInit(CloneCraft.java:197) ~[CloneCraft.class:?]
[B#328] at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_79]
[B#328] at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_79]
[B#328] at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_79]
[B#328] at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.7.0_79]
[B#328] at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532) ~[modpack.jar:?]
[B#328] at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source) ~[?:?]
[B#328] at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_79]
[B#328] at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.7.0_79]
[B#328] at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[guava-17.0.jar:?]
[B#328] at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[guava-17.0.jar:?]
[B#328] at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[guava-17.0.jar:?]
[B#328] at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[guava-17.0.jar:?]
[B#328] at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[guava-17.0.jar:?]
[B#328] at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212) ~[LoadController.class:?]
[B#328] at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190) ~[LoadController.class:?]
[B#328] at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_79]
[B#328] at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_79]
[B#328] at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_79]
[B#328] at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.7.0_79]
[B#328] at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[guava-17.0.jar:?]
[B#328] at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[guava-17.0.jar:?]
[B#328] at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[guava-17.0.jar:?]
[B#328] at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[guava-17.0.jar:?]
[B#328] at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[guava-17.0.jar:?]
[B#328] at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119) ~[LoadController.class:?]
[B#328] at cpw.mods.fml.common.Loader.initializeMods(Loader.java:742) ~[Loader.class:?]
[B#328] at cpw.mods.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:311) ~[FMLClientHandler.class:?]
[B#328] at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:552) ~[bao.class:?]
[B#328] at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878) ~[bao.class:?]
[B#328] at net.minecraft.client.main.Main.main(SourceFile:148) ~[minecraft.jar:?]
[B#328] at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_79]
[B#328] at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_79]
[B#328] at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_79]
[B#328] at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.7.0_79]
[B#328] at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) ~[launchwrapper-1.11.jar:?]
[B#328] at net.minecraft.launchwrapper.Launch.main(Launch.java:28) ~[launchwrapper-1.11.jar:?]
[B#328] [19:17:47] [Server thread/INFO]: Stopping server
[B#328] [19:17:47] [Server thread/INFO]: Saving players
[B#328] [19:17:47] [Server thread/INFO]: Saving worlds
[B#328] [19:17:47] [Server thread/INFO]: Saving chunks for level 'Sams a *****'/Overworld
[B#328] [19:17:47] [Server thread/INFO]: Saving chunks for level 'Sams a *****'/Nether
[B#328] [19:17:47] [Server thread/INFO]: Saving chunks for level 'Sams a *****'/The Last Millenium
[B#328] [19:17:49] [Server thread/INFO] [FML]: Unloading dimension 0
[B#328] [19:17:49] [Server thread/INFO] [FML]: Unloading dimension -1
[B#328] [19:17:49] [Server thread/INFO] [FML]: Unloading dimension -112
[B#328] [19:17:51] [Server thread/INFO] [FML]: Applying holder lookups
[B#328] [19:17:51] [Server thread/WARN] [FML]: Unable to lookup chisel:cobblestoneWall for public static com.cricketcraft.chisel.block.BlockCarvableWall com.cricketcraft.chisel.init.ChiselBlocks.cobblestoneWall. Is there something wrong with the registry?
[B#328] [19:17:51] [Server thread/WARN] [FML]: Unable to lookup chisel:obsidian2 for public static com.cricketcraft.chisel.block.BlockCarvable com.cricketcraft.chisel.init.ChiselBlocks.obsidian2. Is there something wrong with the registry?
[B#328] [19:17:51] [Server thread/WARN] [FML]: Unable to lookup chisel:voidstonerunic for public static com.cricketcraft.chisel.block.BlockCarvable com.cricketcraft.chisel.init.ChiselBlocks.voidstonerunic. Is there something wrong with the registry?
[B#328] [19:17:51] [Server thread/WARN] [FML]: Unable to lookup chisel:circuits for public static com.cricketcraft.chisel.block.BlockCarvable com.cricketcraft.chisel.init.ChiselBlocks.circuits. Is there something wrong with the registry?
[B#328] [19:17:51] [Server thread/WARN] [FML]: Unable to lookup chisel:arcane for public static com.cricketcraft.chisel.block.BlockCarvable com.cricketcraft.chisel.init.ChiselBlocks.arcane. Is there something wrong with the registry?
[B#328] [19:17:51] [Server thread/WARN] [FML]: Unable to lookup chisel:thaumium for public static com.cricketcraft.chisel.block.BlockCarvable com.cricketcraft.chisel.init.ChiselBlocks.thaumium. Is there something wrong with the registry?
[B#328] [19:17:51] [Server thread/WARN] [FML]: Unable to lookup chisel:tallow for public static com.cricketcraft.chisel.block.BlockCarvable com.cricketcraft.chisel.init.ChiselBlocks.tallow. Is there something wrong with the registry?
[B#328] [19:17:51] [Server thread/WARN] [FML]: Unable to lookup chisel:bloodRune for public static com.cricketcraft.chisel.block.BlockCarvable com.cricketcraft.chisel.init.ChiselBlocks.bloodRune. Is there something wrong with the registry?
[B#328] [19:17:51] [Server thread/WARN] [FML]: Unable to lookup chisel:bloodBrick for public static com.cricketcraft.chisel.block.BlockCarvable com.cricketcraft.chisel.init.ChiselBlocks.bloodBrick. Is there something wrong with the registry?
[B#328] [19:17:51] [Server thread/INFO] [FML]: Holder lookups applied
[B#328] [19:17:51] [pool-6-thread-1/INFO] [EnderIO]: ServerChannelRegister: Dimensional Transceiver data saved to C:\Users\curti\AppData\Roaming\.technic\modpacks\o-hot-dam-this-is-my-jam\saves\Sams a *****\enderio\dimensionalTransceiver.json
[B#328] [19:17:51] [Client thread/INFO] [MapWriter]: Mw.close: closing...
[B#328] [19:17:51] [Client thread/INFO] [MapWriter]: waiting for 215 tasks to finish...
[B#328] [19:17:51] [Server thread/INFO] [ProjectE]: Completed server-stop actions.
[B#328] [19:17:52] [Client thread/INFO] [MapWriter]: done

**Comment by MineMaarten** [comment]
So... How can I reproduce this? It doesn't happen for me when just having PneumaticCraft..
