### ISSUE TITLE
Lubricant conflict with RotaryCraft

### ISSUE THREAD

**Issue by notchriss** [MineMaarten/PneumaticCraft#741]
I am aware there was a similar issue submitted before, but my problem is the exact opposite: all I can get from Pneumaticraft's TPP is RotaryCraft's lubricant. And I can't use it to craft Speed Upgrade, hence Speed Upgrade is unattainable in my world :( 

I am using PneumaticCraft-1.7.10-1.11.16-138-universal, RotaryCraft 1.7.10 V9b and forge-1.7.10-10.13.4.1448-1.7.10-universal

**Comment by MineMaarten** [comment]
Sounds like https://github.com/MineMaarten/PneumaticCraft/issues/720 ?

**Comment by notchriss** [comment]
Yes it seems like it's the same issue just with RotaryCraft's lubricant

**Comment by MineMaarten** [comment]
Cool, in that case it's fixed in next version and this issue is a duplicate.
