### ISSUE TITLE
Server Crash on version 17-139

### ISSUE THREAD

**Issue by Tedyhere** [MineMaarten/PneumaticCraft#742]
Crashes on Server Start-up

---- Minecraft Crash Report ----
// Daisy, daisy...

Time: 10/21/15 11:27 PM
Description: Exception in server tick loop

cpw.mods.fml.common.LoaderException: java.lang.NoClassDefFoundError: net/minecraft/client/gui/GuiScreen
	at cpw.mods.fml.common.LoadController.transition(LoadController.java:163)
	at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:559)
	at cpw.mods.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:88)
	at cpw.mods.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:314)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:117)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
Caused by: java.lang.NoClassDefFoundError: net/minecraft/client/gui/GuiScreen
	at pneumaticCraft.common.progwidgets.WidgetRegistrator.init(WidgetRegistrator.java:47)
	at pneumaticCraft.PneumaticCraft.PreInit(PneumaticCraft.java:96)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
	at sun.reflect.GeneratedMethodAccessor5.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
	at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:556)
	... 5 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.gui.GuiScreen
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 33 more
Caused by: java.lang.RuntimeException: Attempted to load class bdw for invalid side SERVER
	at cpw.mods.fml.common.asm.transformers.SideTransformer.transform(SideTransformer.java:50)
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176)
	... 35 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_60, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1374421456 bytes (1310 MB) / 1665138688 bytes (1588 MB) up to 3795845120 bytes (3620 MB)
	JVM Flags: 0 total; 
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1492 102 mods loaded, 102 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCH	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCH	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1492-1.7.10-universal.jar) 
	UCH	Forge{10.13.4.1492} [Minecraft Forge] (forge-1.7.10-10.13.4.1492-1.7.10-universal.jar) 
	UCH	Aroma1997Core{1.0.2.16} [Aroma1997Core] (Aroma1997Core-1.7.10-1.0.2.16.jar) 
	UCH	CodeChickenCore{1.0.7.47} [CodeChicken Core] (minecraft.jar) 
	UCH	NotEnoughItems{1.0.5.118} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.5.118-universal.jar) 
	UCH	<CoFH ASM>{000} [CoFH ASM] (minecraft.jar) 
	UCH	debug{1.0} [debug] (denseores-1.6.2.jar) 
	UCH	bspkrsCore{6.15} [bspkrsCore] ([1.7.10]bspkrsCore-universal-6.15.jar) 
	UCH	StartingInventory{1.7.10.r03} [StartingInventory] ([1.7.10]StartingInventory-universal-1.7.10.r03.jar) 
	UCH	Treecapitator{1.7.10} [Treecapitator] ([1.7.10]Treecapitator-universal-2.0.4.jar) 
	UCH	CoFHCore{1.7.10R3.0.4B1} [CoFH Core] (CoFHCore-[1.7.10]3.0.4B1-308.jar) 
	UCH	BuildCraft|Core{7.1.11} [BuildCraft] (buildcraft-7.1.11.jar) 
	UCH	BuildCraft|Transport{7.1.11} [BC Transport] (buildcraft-7.1.11.jar) 
	UCH	BuildCraft|Silicon{7.1.11} [BC Silicon] (buildcraft-7.1.11.jar) 
	UCH	BuildCraft|Factory{7.1.11} [BC Factory] (buildcraft-7.1.11.jar) 
	UCH	ThermalFoundation{1.7.10R1.2.0} [Thermal Foundation] (ThermalFoundation-[1.7.10]1.2.0-102.jar) 
	UCH	ThermalExpansion{1.7.10R4.0.3B1} [Thermal Expansion] (ThermalExpansion-[1.7.10]4.0.3B1-218.jar) 
	UCH	LogisticsPipes{0.9.3.61} [Logistics Pipes] (logisticspipes-0.9.3.61.jar) 
	UCH	additionalpipes{4.7.0} [Additional Pipes] (additionalpipes-4.7.0.jar) 
	UCH	AncientWarfare{2.4.113-beta-MC1.7.10} [Ancient Warfare Core] (ancientwarfare-2.4.113-beta-MC1.7.10-FULL.jar) 
	UCH	AncientWarfareAutomation{2.4.113-beta-MC1.7.10} [Ancient Warfare Automation] (ancientwarfare-2.4.113-beta-MC1.7.10-FULL.jar) 
	UCH	AncientWarfareNEIPlugin{2.4.113-beta-MC1.7.10} [Ancient Warfare NEI Plugin] (ancientwarfare-2.4.113-beta-MC1.7.10-FULL.jar) 
	UCH	AncientWarfareNpc{2.4.113-beta-MC1.7.10} [Ancient Warfare NPCs] (ancientwarfare-2.4.113-beta-MC1.7.10-FULL.jar) 
	UCH	AncientWarfareStructure{2.4.113-beta-MC1.7.10} [Ancient Warfare Structures] (ancientwarfare-2.4.113-beta-MC1.7.10-FULL.jar) 
	UCH	Aroma1997CoreHelper{1.0.2.16} [Aroma1997Core|Helper] (Aroma1997Core-1.7.10-1.0.2.16.jar) 
	UCH	BiblioCraft{1.11.2} [BiblioCraft] (BiblioCraft[v1.11.2][MC1.7.10].jar) 
	UCH	Highlands{2.2.3} [Highlands] (Highlands-1.7.2-v-2.2.3.jar) 
	UCH	BiblioWoodsHighlands{1.4} [BiblioWoods Highlands Edition] (BiblioWoods[Highlands][v1.4].jar) 
	UCH	BNBGamingLib{2.2.0} [BNBGamingLib] (BNBGamingLib-2.2.0.jar) 
	UCH	BuildCraft|Builders{7.1.11} [BC Builders] (buildcraft-7.1.11.jar) 
	UCH	BuildCraft|Energy{7.1.11} [BC Energy] (buildcraft-7.1.11.jar) 
	UCH	BuildCraft|Robotics{7.1.11} [BC Robotics] (buildcraft-7.1.11.jar) 
	UCH	BuildCraft|Compat{7.1.2} [BuildCraft Compat] (buildcraft-compat-7.1.2.jar) 
	UCH	eureka{3.0.2} [Eureka] (Eureka-1.7.10-3.0.2.jar) 
	UCH	bcadditions{2.2.2} [BuildCraft Additions] (BuildcraftAdditions-1.7.10-2.2.2.jar) 
	UCH	Waila{1.5.10} [Waila] (Waila-1.5.10_1.7.10.jar) 
	UCH	Calculator{1.8.4} [Calculator] (Calculator-1.7.10-1.8.4.jar) 
	UCH	CarpentersBlocks{3.3.7} [Carpenter's Blocks] (Carpenter's Blocks v3.3.7 - MC 1.7.10.jar) 
	UCH	ChickenChunks{1.3.4.19} [ChickenChunks] (ChickenChunks-1.7.10-1.3.4.19-universal.jar) 
	UCH	ForgeMultipart{1.2.0.345} [Forge Multipart] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	UCH	Railcraft{9.7.0.0} [Railcraft] (Railcraft_1.7.10-9.7.0.0.jar) 
	UCH	chisel{2.9.3.9} [Chisel] (Chisel-2.9.3.9.jar) 
	UCH	ChiselFacades{1.7.10-2.12-chiselteam} [Chisel Facades] (ChiselFacades-1.7.10-2.12-chiselteam.jar) 
	UCH	CompactMachines{1.7.10-1.20} [Compact Machines] (compactmachines-1.7.10-1.20.jar) 
	UCH	lootablebodies{1.3.5} [DrCyano's Lootable Bodies] (CyanosLootableBodies-1.3.5-backport.jar) 
	UCH	DimensionalControl{0.14.0} [DimensionalControl] (DimensionalControl-0.14.0.jar) 
	UCH	OmnisCore{0.1.0} [Omnis Core] (OmnisCore-1.7.10 - 0.0.6-universal.jar) 
	UCH	dimensionalPockets{0.11.4.1} [Dimensional Pockets] (DimensionalPockets-1.7.10-0.11.4.1-universal.jar) 
	UCH	Enchiridion{1.3} [Enchiridion] (Enchiridion 2-1.7.10-2.0.2a.jar) 
	UCH	Enchiridion2{2.0.2a} [Enchiridion 2] (Enchiridion 2-1.7.10-2.0.2a.jar) 
	UCH	endercore{1.7.10-0.1.0.26_beta} [EnderCore] (EnderCore-1.7.10-0.1.0.26_beta.jar) 
	UCH	EnderStorage{1.4.7.37} [EnderStorage] (EnderStorage-1.7.10-1.4.7.37-universal.jar) 
	UCH	enderutilities{0.4.3} [Ender Utilities] (enderutilities-1.7.10-0.4.3.jar) 
	UCH	etfuturum{1.4.4} [Et Futurum] (Et Futurum-1.4.4.jar) 
	UCH	McMultipart{1.2.0.345} [Minecraft Multipart Plugin] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	UCH	funkylocomotion{1.0} [Funky Locomotion] (funky-locomotion-1.7.10-beta-7.jar) 
	UCH	GekosLasers{1.7.10R0.8} [Geko's Lasers] (GekosLasers-1.7.10-0.8.jar) 
	UCH	iChunUtil{4.2.2} [iChunUtil] (iChunUtil-4.2.2.jar) 
	UCH	GraviGun{4.0.0-beta} [GraviGun] (GravityGun-4.0.0-beta.jar) 
	UCH	GYTH{1.1.0} [Get Ya' Tanks Here] (Gyth-1.1.0-1.7.10.jar) 
	UCH	HelpFixer{1.0.7} [HelpFixer] (HelpFixer-1.0.7.jar) 
	UCH	ibench{1.0.12} [iBench] (ibench-1.7.10-1.0.12.jar) 
	UCH	ImmersiveEngineering{0.5.4} [Immersive Engineering] (ImmersiveEngineering-0.5.4.jar) 
	UCH	immersiveintegration{0.5.4} [Immersive Integration] (immersiveintegration-0.5.4.jar) 
	UCH	InfernalMobs{1.6.0} [Infernal Mobs] (InfernalMobs-1.7.10.jar) 
	UCH	inpure|core{1.7.10R1.0.0B9} [INpureCore] (INpureCore-[1.7.10]1.0.0B9-62.jar) 
	UCH	interdictionpillar{1.7.10-1.0.0} [Interdiction Pillar] (interdictionpillar-1.1.0.jar) 
	UCH	ironbackpacks{0.5.0} [Iron Backpacks] (Iron Backpacks-1.7.10-1.0.4-universal.jar) 
	UCH	llibrary{0.4.3} [LLibrary] (llibrary-0.4.3-1.7.10.jar) 
	UCH	meteors{2.14.3} [Falling Meteors] (meteors-1.7.10-2.14.3.jar) 
	UCH	MineTweaker3{3.0.10} [MineTweaker 3] (MineTweaker3-1.7.10-3.0.10B.jar) 
	UCH	numina{0.4.0.131} [Numina] (Numina-0.4.0.131.jar) 
	UCH	powersuits{0.11.0.283} [MachineMuse's Modular Powersuits] (ModularPowersuits-0.11.0.283.jar) 
	UCH	MonsterSwarm{1.0.4} [Monster Swarm] (MonsterSwarm-1.0.4.jar) 
	UCH	NEIAddons{1.12.13.6} [NEI Addons] (neiaddons-fu-1.12.13.6-mc1.7.10.jar) 
	UCH	NEIAddons|Developer{1.12.13.6} [NEI Addons: Developer Tools] (neiaddons-fu-1.12.13.6-mc1.7.10.jar) 
	UCH	NEIAddons|AppEng{1.12.13.6} [NEI Addons: Applied Energistics 2] (neiaddons-fu-1.12.13.6-mc1.7.10.jar) 
	UCH	NEIAddons|Botany{1.12.13.6} [NEI Addons: Botany] (neiaddons-fu-1.12.13.6-mc1.7.10.jar) 
	UCH	NEIAddons|Forestry{1.12.13.6} [NEI Addons: Forestry] (neiaddons-fu-1.12.13.6-mc1.7.10.jar) 
	UCH	NEIAddons|CraftingTables{1.12.13.6} [NEI Addons: Crafting Tables] (neiaddons-fu-1.12.13.6-mc1.7.10.jar) 
	UCH	NEIAddons|ExNihilo{1.12.13.6} [NEI Addons: Ex Nihilo] (neiaddons-fu-1.12.13.6-mc1.7.10.jar) 
	UCH	openmodularturrets{2.1.5-184} [Open Modular Turrets] (OpenModularTurrets-1.7.10-2.1.5-184.jar) 
	UCE	PneumaticCraft{1.11.17-139} [PneumaticCraft] (PneumaticCraft-1.7.10-1.11.17-139-universal.jar) 
	UCH	PortalGun{4.0.0-beta-5} [PortalGun] (PortalGun-4.0.0-beta-5.jar) 
	UCH	Quadrum{1.2.0} [Quadrum] (Quadrum-1.7.10-1.2.0.B13-universal.jar) 
	UCH	RandomThings{2.2.4} [Random Things] (RandomThings-2.2.4.jar) 
	UCH	RefinedRelocation{1.1.10} [Refined Relocation] (RefinedRelocation-mc1.7.10-1.1.10.jar) 
	UCH	rftools{3.50} [RFTools] (rftools-3.50.jar) 
	UCH	Roguelike{1.3.6.3} [Roguelike Dungeons] (roguelike-1.7.10-1.3.6.3.jar) 
	UCH	sodacantorches{01.06.00} [Sodacan Torches] (sodacantorches-01.06.00.jar) 
	UCH	StevesWorkshop{0.5.1} [Steve's Workshop] (StevesWorkshop-0.5.1.jar) 
	UCH	StorageDrawers{1.7.10-1.6.2} [Storage Drawers] (StorageDrawers-1.7.10-1.6.2.jar) 
	UCH	SuperMultiDrills{1.1.1} [Super Multi-Drills] (SuperMultiDrills-1.7.10-1.1.1-18.jar) 
	UCH	Sync{4.0.0} [Sync] (Sync-4.0.0.jar) 
	UCH	ThermalDynamics{1.7.10R1.1.0} [Thermal Dynamics] (ThermalDynamics-[1.7.10]1.1.0-161.jar) 
	UCH	ToolUtilities{0.0.1} [Tool Utilities] (ToolUtilities-MC1.7.10-0.0.1-16.jar) 
	UCH	Triumph{0.9.0} [Triumph] (Triumph-0.9.0.jar) 
	UCH	wailaplugins{MC1.7.10-0.1.2-21} [WAILA Plugins] (WAILAPlugins-MC1.7.10-0.1.2-21.jar) 
	UCH	ZombieInfection{@VERSION@} [Zombie Infection] (Zombie Infection-1.7.10-1.3.0.jar) 
	UCH	denseores{1.0} [Dense Ores] (denseores-1.6.2.jar) 
	UCH	ForgeMicroblock{1.2.0.345} [Forge Microblocks] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	CoFHCore: -[1.7.10]3.0.4B1-308
	ThermalFoundation: -[1.7.10]1.2.0-102
	ThermalExpansion: -[1.7.10]4.0.3B1-218
	ThermalDynamics: -[1.7.10]1.1.0-161
	DPAnalytics Crash Check: Will analyze crash-log before shutdown and send it to the Dimensional Pockets developer
	Profiler Position: N/A (disabled)
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)

**Comment by pharaun** [comment]
I was able to reproduce this with a different config as well. Downgraded to -16 for now

**Comment by MineMaarten** [comment]
classic :P. I really need to learn to test the SMP side, I act under the assumption it always does, seeing it's a 'small' update :P.
