### ISSUE TITLE
Crash when looking at a Tinkers' Mechworks Signal Bus with Waila and PneumaticCraft installed.

### ISSUE THREAD

**Issue by Rukachan** [MineMaarten/PneumaticCraft#744]
The tile explains everything, please let me know if I should report this to the Tinkers' Mechworks team.

Probably similar to https://github.com/SlimeKnights/TinkersMechworks/issues/82
Crash log http://pastebin.com/rKwUyQc9

Minecraft 1.7.10
Forge 10.13.4.1448
PneumaticCraft-1.7.10-1.11.18-140
TConstruct-1.7.10-1.8.7
Mantle-1.7.10-0.3.2
TMechworks-1.7.10-0.2.14.100
Waila-1.5.10_1.7.10

**Comment by Rukachan** [comment]
I should also mention that by disabling waila in the third_party_enabling in the PneumaticCraft config the problem does not appear.

**Comment by MineMaarten** [comment]
I really don't see how PneumaticCraft could be the cause of this? Are you really saying the crash does not happen when taking out just PneumaticCraft?

**Comment by Rukachan** [comment]
Yes, in my ~60 mod modpack, this crash does not happen when taking out PneumaticCraft or when disabling its Waila interaction. I too was surprised when I realised that.

**Comment by Rukachan** [comment]
May I ask why was this closed? Considering that I can still reproduce it in 1.12.3-146.

**Comment by MineMaarten** [comment]
The issue linked ( SlimeKnights/TinkersMechworks#82 ) indicates to me it's not PneumaticCraft's issue, but rather Waila's or Tinkers.
