### ISSUE TITLE
Missing texture in Programmer

### ISSUE THREAD

**Issue by DoctorTDM** [MineMaarten/PneumaticCraft#748]
For some reason all of the textures for the puzzle blocks in the programmer are just white squares, which match the background of the programming screen. i also can't see the place to put the thing you want programmed. I tried to see if this was interference but it was not a different mod as i removed all the others.

PneumaticCraft 1.7.10-1.11.14-136-universal
![2015-11-01_00 22 16](https://cloud.githubusercontent.com/assets/15535738/10867723/6aecf594-802f-11e5-84fc-198c2b9e02f9.png)

**Comment by MineMaarten** [comment]
Hmm that's very strange. I can't reproduce it using the version specified. I suspected some missing texture issue due to being one OS being more picky than another with casing, but I've verified they are exactly equal.... This does only happen with the Programmer GUI?

**Comment by DoctorTDM** [comment]
Yes, but i believe that the scroll bars are affected as well as they are
the same color but i may be mistaken about that. here is an image of the
scroll buttons as well as a picture of the programming pieces on the
creative menu

**Comment by DoctorTDM** [comment]
I forgot to mention. Is there anything i can do to help you figure this
out? A folder to send to you maybe?

**Comment by MineMaarten** [comment]
Not really... Now my suspicion is that texture rendering is turned off... if so I can fix it :).

**Comment by MineMaarten** [comment]
Ok, I can't reproduce it at all, but I've added some protection to make sure the texture rendering is on at the places where you told it gives problems. 

Are you using optifine by chance? and if so, try without optifine?

**Comment by DoctorTDM** [comment]
i have never used optifine before. however when i encountered the problem i
was using other mods. however i deduced that it was them because i removed
and then reinstalled all the files for minecraft to make sure it wasn't a
mod interference.
