### ISSUE TITLE
world crash with elevator caller

### ISSUE THREAD

**Issue by Lorenzo77** [MineMaarten/PneumaticCraft#749]
hello,

i put down 32 elevator on a 2x2 pattern (8 elevator by Y), i put frame on all this and add a lot of caller ... almost 40 or more until the game crash ... and now each time i try to load the world i have this error :
http://pastebin.com/mHebF9pC

-------------------------------------------------
can we use gas lift without other mods adding pipe ?
i have try so many things and nothing work, always the same message in the GUI : no tanks

**Comment by MineMaarten** [comment]
Yes, please split up the issues. And yes, you can use the gas lift... the Liquid Hopper is a tank... And so is a refinery itself for example... And wait whut... the Gas Lift has an internal tank? So you could use logistics drones/Liquid Hoppers to transport the oil... What exactly does the GUI say?

**Comment by Lorenzo77** [comment]
okkkkk ... i was trying to make some derivation from the pressure tube going down from the gas lift and even try vacum to pump liquid ^^

in the problems tab : not enough tank space to pump / connect up a tank

i just try with the hopper for liquid and i can output in a thermalfactory tank ... but still have the same message in the gui (problems tab)... i suppose it always stay on ?

**Comment by MineMaarten** [comment]
After testing I see what you mean. Yes, the warning it supposed to stay on. It simply tells you the pump can't work anymore, because it's full of oil already, so there isn't any work left.
