### ISSUE TITLE
the IGW help for "Drone Condition: Entity" and "Condition: Entity" are swap

### ISSUE THREAD

**Issue by Lorenzo77** [MineMaarten/PneumaticCraft#753]
hello

the IGW help for "Drone Condition: Entity" and "Condition: Entity" are swap

--
can i really submit a new issue for each problem i found ?

**Comment by MineMaarten** [comment]
Confirmed and fixed!

And yes, new issue for every problem found, see https://github.com/MineMaarten/PneumaticCraft/issues/754#issuecomment-153303254
