### ISSUE TITLE
can't drag puzzle piece : Drone Condition Items/Liquid/Entity

### ISSUE THREAD

**Issue by Lorenzo77** [MineMaarten/PneumaticCraft#754]
hello

in the programmer, i cant drag this pieces :
Drone Condition: Entity
Drone Condition: Items
Drone Condition: Liquid
there is exactly 1 pixel active (for the drag) in the center but that' all, if i click and drag anywhere else on this pieces nothing work :(

----------
just a little request here (cant undestand how to do it in the pull request ^^) :
i miss something for drone debugging ... in almost all programming language there"s a console log or something like this ... maybe you can add a puzzle piece for outputing variable content or text in the minecraft console or in a text file ?
or just have a debug mode tracing in the minecraft console the puzzle piece name currently active ... this can help to find problems.
maybe it's me but i find this hard to undestand why my drone is not moving or why it's not doing this or that.

----------
the deeper i go in PNC and the better i like it ... i have tons of ideas/requests but i'm sure you don't have tons of time ^^

**Comment by MineMaarten** [comment]
I'll look at the dragging bug.

As for the request, it sounds like #717 ? If not, separate issue please. Also, a pull request is only for coders, who intend to implement the feature for me, basically taking away the effort for me to code it.

**Comment by MineMaarten** [comment]
I can't reproduce it I'm afraid. I tried both dragging them out of the panel, and when they are already in the program. For the record, which of these two didn't work?

Also, which version are you running?

**Comment by Lorenzo77** [comment]
when i try to add them to the program (dragging them out of the panel)

---
thanks for the infos, i will take care !

**Comment by MineMaarten** [comment]
And PneumaticCraft version?

**Comment by Lorenzo77** [comment]
the last build : PneumaticCraft-1.7.10-1.11.18-140-universal.jar

**Comment by MineMaarten** [comment]
Hmm ok... there was an issue with this in a previous version, caused by the scrollbar behind the panel. And I can reproduce it with that in mind.

**Comment by Lorenzo77** [comment]
i have more intel, and yes i think you are right, because all the piece :
Drone Condition: Entity
Drone Condition: Items
Drone Condition: Liquid
Drone Condition: Pressure (didnt try this one before)
are in the same colonne and all the 4 from the colonne dont work as expected.

if i aim and click a part of a piece in front of the scrollbar or to the right the panel close and i dont drag the piece (except for the dot in the center) ... but if i aim for the 2 or 3 pixels on the left i can drag it
should i try to remove all the mods except PNC ?

**Comment by MineMaarten** [comment]
No, I have enough info, thanks! I can reproduce it, so from now on I can do any more tests if necessary :P.

**Comment by MineMaarten** [comment]
Ok, I think I've fixed it, but I'm not entirely sure, as I can't reliably reproduce the issue every time. Leave a comment in here if the new version does not fix it :)
