### ISSUE TITLE
ComputerCraft/OpenComputers support?

### ISSUE THREAD

**Issue by JCBurnside** [MineMaarten/PneumaticCraft#755]
I know this mod used to have support for cc and oc but in version 1.7.10-1.11.16-138 the opencomputers cables won't connect to the elevators. I tried putting them on the side and bottom but it won't connect.  I checked the configs and the support is enabled.  Am I doing something wrong because in a previous version I could hook up the cables to the bottom of the elevator just fine.

**Comment by JCBurnside** [comment]
Actually I dug through the code and found just the support for opencomputers was dropped.  I saw the api for computercraft being loaded but why not opencomputers?

**Comment by MineMaarten** [comment]
>Actually I dug through the code and found just the support for opencomputers was dropped. I saw the api for computercraft being loaded but why not opencomputers?

Uhhh that doesn't make sense? I haven't changed anything to the OC support in a whiiiiile. This whole issue confuses me really.

Because I really don't have any understanding of OC whatsoever (and no interest in learning the mod), @Vexatos , could you help me to find out what's happening here..?

**Comment by Vexatos** [comment]
@JCBurnside It was changed to indirect support to avoid various issues. Just place an adapter next to the block you would like to interface with. This is not a bug.

**Comment by JCBurnside** [comment]
@Vexatos  oh ok. thank you.  I didn't realize that it was the I need the adapter.  In a previous version I could hook up the cable directly.  Thank you for the help
