### ISSUE TITLE
Add option in block condition to ignore fluids

### ISSUE THREAD

**Issue by Forecaster** [MineMaarten/PneumaticCraft#760]
Currently the block condition checks for any block, which includes fluids.

My mining program has a subroutine dedicated to scanning the mining area using foreach and testing if each block is a fluid block, and if it is the drone will go there to have the security upgrade destroy it. This just because fluid blocks interfere with the block conditions that check if each sub-job is done by seeing if there are blocks left to dig out.

But looping through each block in the mining area takes a very long time. It would be great if the block conditions would simply ignore fluids, since they cannot be dug, and you cannot exclude them using item filters.

PS. The subroutine also checks the entire area for fluids first, and if there are no fluids in it it wont have to loop through it.

**Comment by MineMaarten** [comment]
This sounds like this is ideal in your case, but for other users it simply doesn't make sense to let fluid blocks act like air...

**Comment by AEnterprise** [comment]
maybe an upgraded one then or an option? there are cases where it would be usefull for plenty of people

**Comment by Forecaster** [comment]
Have it be an "Ignore Fluids" option like "Check for Air"?
