### ISSUE TITLE
Add chat broadcast command

### ISSUE THREAD

**Issue by Forecaster** [MineMaarten/PneumaticCraft#761]
My current mining program is designed allow my drones to work even when I'm not present using Railcraft world anchors (chunk loaders), still working out some kinks but generally it's worked.

So I can now set an area for them to mine, and then I can leave the server, close my client and work on other things while they work, but I can't tell when they're done!

I'd love to have a command that allows the drones to send messages to chat, which I could see in the console. It would also be useful for allowing the drones to communicate in-game as well of course.

**Comment by MineMaarten** [comment]
I can see a lot of spam happening in less managed servers, sorry

**Comment by Forecaster** [comment]
Undesired puzzle pieces can be disabled though.

**Comment by MineMaarten** [comment]
If you want admin like tools like printing something in chat/log when something happens, use command blocks. drones can emit redstone.

**Comment by Forecaster** [comment]
You can't use command blocks in survival mode.
