### ISSUE TITLE
EMC

### ISSUE THREAD

**Issue by NicosaurusRex99** [MineMaarten/PneumaticCraft#764]
Using the amadron delivery system you can order  an emerald for 27 paper
27 paper emc = 864
1 emerald emc = 16,384
I think thats a little problem
This is using projectE for emc i am sure its the same for EE3

I suggest a something like getting the mod to check for emc and then adjust values to suit this problem

**Comment by GirafiStudios** [comment]
Well the same "problem" would be in vanilla villager trading then.

**Comment by NicosaurusRex99** [comment]
It would but trades expire after a while so that isn't as much of a problem

**Comment by Forecaster** [comment]
Amadron trades are randomized every in game day.

**Comment by MineMaarten** [comment]
Both Girafi and Forecaster answered this well :)

**Comment by NicosaurusRex99** [comment]
I think its still a little problem but if you say its fine i wont bother argue with you
