### ISSUE TITLE
Serious topic

### ISSUE THREAD

**Issue by NicosaurusRex99** [MineMaarten/PneumaticCraft#768]
I know that this isn't an issue at all but i think that MineMaarten is really cool because he attempts to respond to all serious posts. i just wanted to post this here because all issue finders would see this and hopefully agree. Thank you MineMaarten for being kind and awesome!

**Comment by MineMaarten** [comment]
And just on this occasion my eyes lost track of the github somehow ;). But thanks for the compliment. Unfortunately I can't keep this issue open, as it will just distract me everytime I see the topic title and go look what the issue is about :P.
