### ISSUE TITLE
The elevator receives a half of pressure of a pipe

### ISSUE THREAD

**Issue by StrikS** [MineMaarten/PneumaticCraft#770]
Hello, thank you for amazing mod.
I noticed that bug when began to use volume upgrade in the elevator.
![elevator](https://cloud.githubusercontent.com/assets/15943769/11302538/e9c9398c-8fbf-11e5-82b6-57ad440de3fc.gif)

**Comment by MineMaarten** [comment]
Thanks for the detailed graphic!
I've tested it myself but couldn't reproduce it.... Is there a chunk boundary in between the elevator and the tube next to it by a chance?
