### ISSUE TITLE
Minor Achievement Issues

### ISSUE THREAD

**Issue by TigersFangs** [MineMaarten/PneumaticCraft#772]
Using PneumaticCraft v1.12.1-144 and Buildcraft v7.1.11

I've noticed that the PneumaticCraft Achievements are not working correctly regarding picking up a bucket of oil.  With both installed BC oil is defaulted for the fluid registry(which from my understanding is supposed to happen).  The achievement(Black Gold) will not trigger when picking up BC oil with a bucket.  I spawned in a bucket of PC oil, placed it in the world, and then picked it up; but the achievement still did not trigger.  So I spawned another bucket of PC oil and dropped it on the ground as an item, then picked it back up.  This did trigger the achievement correctly.  After this discovery I examined the first bucket of PC oil that I picked up and found that when I picked it up, it converted to a bucket of BC oil.  From what I understand of Forge Fluids, this does make sense, but it also breaks the chain of achievements.  Like I stated in the title, it is a relatively minor issue, but one that I thought should be brought up in case it was something that you wanted to look at.

As a side note, both "Black Gold" and "Building up the Pressure!" become available after completing "The First Explosion (of many)".  I'm not sure if this is intentional or not, but given that they are arranged linearly, I am assuming not. :)

Thanks for an AMAZING mod @MineMaarten !

EDIT:  The Seismic Sensor also seems to work differently with BC oil, only detecting it if you are right clicking on a block directly above it and not calculating the quantity of buckets available.  The chat message also changes color mid message when oil is found.

**Comment by MineMaarten** [comment]
The Seismic Sensor works the same for both types of oil, and it's intentional.
