### ISSUE TITLE
Crash when adding Pneumaticraft to my modpack. 

### ISSUE THREAD

**Issue by cauliflower69** [MineMaarten/PneumaticCraft#773]
Looks like an issue with Computercraft. Pack works fine without Pneumaticraft 

http://pastebin.com/TgHtJMn3

**Comment by adamcogx** [comment]
The cause is actually Compact Machines v1.7.10-1.21.

**Comment by MineMaarten** [comment]
Yes, that makes sense @adamcogx , thanks! It's another case of other mods including API's they shouldn't...
