### ISSUE TITLE
Crash when exporting to pastebin

### ISSUE THREAD

**Issue by Darkosto** [MineMaarten/PneumaticCraft#775]
My client crashed when clicking the export to pastbin button in the programmer. This crash also happened while playing on a server. 

http://pastebin.com/EUctAzfD

Thank you for the help, sir!
Darkosto

**Comment by MineMaarten** [comment]
Interesting... which programming pieces did you try to export? Just the Inventoyr Import + Entity Attack? Or?

**Comment by Darkosto** [comment]
I had a program with the following: Start, pick up items, 2x area, and import to chest
