### ISSUE TITLE
Universal sensor resets between server restarts

### ISSUE THREAD

**Issue by Forecaster** [MineMaarten/PneumaticCraft#781]
I keep finding my refinery shut down because the sensor that is supposed to regulate the heat input is set to nothing. It remembers the mode its set to (block -> heat), but the field where the level is set is empty, instead of the 500 I keep setting it to.

**Comment by MineMaarten** [comment]
It's only a sync issue... So serverside it's fine (confirmed after testing). So it's weird that it doesn't work for you after a restart.
