### ISSUE TITLE
Fireworks instead of air

### ISSUE THREAD

**Issue by Bobbleton** [MineMaarten/PneumaticCraft#784]
Whenever I have a leak in the system or vent on my friend's server, instead of air coming out with a hiss, fireworks rapidly gush out.
![2015-12-24_05 46 18](https://cloud.githubusercontent.com/assets/16426198/11993743/9d34767e-aa02-11e5-8e72-97ec29278c0d.png)
![2015-12-24_05 46 23](https://cloud.githubusercontent.com/assets/16426198/11993746/a3c5b444-aa02-11e5-8448-b915b93b5f2b.png)
![2015-12-24_05 46 27](https://cloud.githubusercontent.com/assets/16426198/11993748/a6d71498-aa02-11e5-8e33-78dc29f333d6.png)
![2015-12-24_05 46 41](https://cloud.githubusercontent.com/assets/16426198/11993750/aa59d768-aa02-11e5-8ec3-970e0d98c825.png)
![2015-12-24_05 46 48](https://cloud.githubusercontent.com/assets/16426198/11993752/aeda42dc-aa02-11e5-896a-0df0df1413bc.png)

**Comment by Forecaster** [comment]
It's not steam. It's air.

And this seems like some sort of holiday easter egg.

**Comment by Bobbleton** [comment]
Whoops, don't know why I closed it.

**Comment by MineMaarten** [comment]
It _was_ an holiday easter egg. It however was removed a LONG time ago after I got sick of people reporting it as bug, of which this is another perfect example.

So... update >.> (I'm also getting sick of people reporting bugs with ancient versions)
