### ISSUE TITLE
Sentry Turret sounds are a bit weird

### ISSUE THREAD

**Issue by XFactHD** [MineMaarten/PneumaticCraft#786]
While the sound of the sentry slowing down after shooting has a range of about 42 blocks, the shooting sound only has a range of about 14 blocks and the sound when the sentry speeds up has a range of about 30 blocks.

**Comment by MineMaarten** [comment]
Not really considered a bug, I knew it sounded weird right from the point I implemented it, but I couldn't get to sound better at the time..
