### ISSUE TITLE
Chargin Station's Object's GUI Bug 1.7.10

### ISSUE THREAD

**Issue by Blue64** [MineMaarten/PneumaticCraft#788]
When viewing the Charging Station, it's possible to open the Pressure display and see the current pressure amount, and it goes up/down accordingly as the compressed air flows around the system, ***BUT***, If you put an Object into the Charging Station's Charging slot, and then open the GUI for placing the Upgrades into said item (Pneumatic Helmet for example), if you open ***THAT*** GUI's Pressure display, it does not change, despite the fact that it's obviously gaining/losing air (being in the Charging Station's Charging Slot). If you add/remove something that changes the ```bar``` it will update the GUI, but it still remains frozen for as long as you are looking at that GUI.

I also notice that if you repeatedly Add & Remove the Capacity Upgrades, it keeps cutting into the ```bar``` (and the available air supply inside the object), but I'm guessing this was intentional, although some kind of "charging" would be nice for these items, I can understand where it'd need to get a heavy rewrite (a Drone for example would need a "second inventory" for it's various canisters that don't stack due to the charge not matching, unless of course you rewrote it to a ```max stack size``` of ```1``` and allowed it to have it's ```max capacity``` augmented up to ```64``` times, this also would be a good method for the other upgrades as well, similar to the ```Blood Magic Fluid Containers```, just remember to not use the ```int``` that can go negative ```;)```)

**Comment by MineMaarten** [comment]
About the Volume Upgrade, yes this is intentional, and I like the balance aspect of it that it makes you lose air if you're not careful. So it will stay as it is right now.

**Comment by MineMaarten** [comment]
(As this is a very minor visual bug this is only fixed in MC1.8.9)

**Comment by Blue64** [comment]
cool with me :) :+1:
