### ISSUE TITLE
Config option to allow liquid heat/cold sources to no decay *enhancement

### ISSUE THREAD

**Issue by dalgrim** [MineMaarten/PneumaticCraft#790]
Perhaps you could add a config option to allow liquids (lava,gelid cryo, etc) to decay slower or not at all. I know there are some existing players on my server that area grumbling that they have to completely rebuild their pneumaticCraft rooms because of the lava->obsidian change. It would be nice to have a config option to revert it to the way it was before or at least have the decay/change time scalable.

**Comment by MineMaarten** [comment]
Sorry but no, the old behaviour was wayyyyyy OP.
