### ISSUE TITLE
Support with Texture Packs

### ISSUE THREAD

**Issue by Korra0504** [MineMaarten/PneumaticCraft#791]
Hi,

I have a problem with the gui from your Security Station. I can't add a Name when i have a Texture Pack  with a ascii.png with a resolution higher than 128x128

Can you fix this please :+1:

**Comment by MineMaarten** [comment]
Tested with a 512x512 ascii.png, and it works fine:
![2016-01-10_22 33 03](https://cloud.githubusercontent.com/assets/5345405/12224197/885e786c-b7ea-11e5-909f-3d2935c24d9c.png)

Please add a screenshot and a pack I can reproduce this with please :+1:
