### ISSUE TITLE
Pneumatic Helmet problem...

### ISSUE THREAD

**Issue by TCAS** [MineMaarten/PneumaticCraft#792]
Hi all, 

When I put the pneumatic helmet, the option interface opens and I can not close.

https://www.dropbox.com/s/4rfw6dexg8ezbip/Captura%20de%20pantalla%202016-01-08%2014.03.18.png?dl=0

Thanks for the help.

Ups.. I think is the same problem in this post:

https://github.com/MineMaarten/PneumaticCraft/issues/767

**Comment by MineMaarten** [comment]
I think so
