### ISSUE TITLE
Crash when placing AE2 Pressure P2P against Aerial Interface

### ISSUE THREAD

**Issue by XFactHD** [MineMaarten/PneumaticCraft#793]
If I place a Pressure P2P directly against an Aerial Interface the game crashes when I try to enter the world after restarting the game.
Crash: http://pastebin.com/x3ZdSUk4
AE2: rv3-beta 2
PC: 1.7.10-1.12.1-144

**Comment by MineMaarten** [comment]
I've spoken with Yueh, and a fix will be required on AE2's side.
