### ISSUE TITLE
Crash after remove of PneumaticCraft

### ISSUE THREAD

**Issue by Anghelos92** [MineMaarten/PneumaticCraft#797]
I have a modpack which I am still finishing to build, before I installed PneumaticCraft everything was fine. Then I Installed PneumaticCraft and everything was fine, awesome mod by the way, but then I had to remove it to try the modpack without PneumaticCraft but now minecraft loads succesfully but crashes when start a new or a saved world. If I put pneumaticCraft inside the mod folder instead the save world or the new world loads successfully, can you help me? Thank you.

**Comment by XFactHD** [comment]
You won't get any help without providing a crash report. Please put it on pastebin.com or gist.github.com and post the link here.

**Comment by Anghelos92** [comment]
Thank you for your answer but I just resolved the problem by myself this way: I deleted Railcraft configs and let Forge regenerate it, now minecraft can run without problems without PneumaticCraft, which however i will re-add in my minecraft, i just unistalled it to make a test.
