### ISSUE TITLE
Random crash while in Nether (1.8.9)

### ISSUE THREAD

**Issue by BBoldt** [MineMaarten/PneumaticCraft#798]
Just walking around in the nether and *poof* client crash.
http://tehnut.info/share/kF1rLHdXFK.txt

**Comment by MineMaarten** [comment]
Thanks for the report :)

**Comment by BBoldt** [comment]
@MineMaarten Was the fixed version released yet?

I can't find it if it was. This bug is getting a bit annoying, it happens quite frequently while just walking around in the nether.

**Comment by MineMaarten** [comment]
It was not, I didn't realise it happened often. I'll release a version now, should be on curse in around 15 minutes.

**Comment by BBoldt** [comment]
Thanks!

**Comment by BBoldt** [comment]
Again: https://gist.github.com/1e0c9efaaa2256067c69

* PneumaticCraft-1.8.9-1.13.3-4-universal.jar
* Forge 1715

**Comment by BBoldt** [comment]
Actually the crashlog is slightly different this time, but it was in the nether.

**Comment by MineMaarten** [comment]
Ok, it should be fixed with https://github.com/MineMaarten/PneumaticCraft/commit/52a7b9d4d29dcf7bd997cf4762e4ea55484f98ed
It's on curse shortly.
