### ISSUE TITLE
Nerf Fire as a heat source

### ISSUE THREAD

**Issue by wormzjl** [MineMaarten/PneumaticCraft#801]
Gnenrally you can refine oil without the need for energy :P
![image](https://cloud.githubusercontent.com/assets/2989009/12529946/4b852f0e-c1d5-11e5-805d-b3a55cba27bd.png)

**Comment by Forecaster** [comment]
Using what version of pneumaticcraft?

**Comment by wormzjl** [comment]
PneumaticCraft-1.7.10-1.12.4-147-universal

**Comment by XFactHD** [comment]
I think this is somewhat intended, you could even use a torch as heat source. But it depends on the speed if there is a bug or not.

**Comment by MineMaarten** [comment]
Ah dangit, I forgot to nerf Fire! Thanks for that, you'll be punished by your honesty muhaha

**Comment by wormzjl** [comment]
Using build 150. I can still refine oil with fire :P
