### ISSUE TITLE
Thaumcraft Upgrade not working

### ISSUE THREAD

**Issue by JasonMcRay** [MineMaarten/PneumaticCraft#802]
I just tried Thaumcraft upgrade for Pneumatic Helmet, but it doesnt seem to do anything. It isnt even mentioned when i put the helmet on and it starts to load with different messages. No message about the Thaumcraft Update detected or anything.

Tested on PC: 1.12.1-144

**Comment by MineMaarten** [comment]
It isn't considered as the other upgrades no. It will not be displayed when loading up the helmet.

The only thing the upgrade should do is do the same as the goggles of revealing: show aura nodes, and show aspects inside aspect containing blocks. Does this work?

**Comment by JasonMcRay** [comment]
Nope it did not work. I was looking at already scanned block and did not showed any Aspects. havent checked the Aura nodes.

**Comment by MineMaarten** [comment]
Well, it works for me, just having a Pneumatic Helmet with only the Thaumcraft Upgrade in it, on MC1.7.10.
![2016-01-29_16 56 13](https://cloud.githubusercontent.com/assets/5345405/12680286/3fc4baf8-c6a9-11e5-86f7-5434851e9a8e.png)

**Comment by JasonMcRay** [comment]
Hmm.. I will tried that again today and will let you know, but no idea what I might be doing wrong

**Comment by MineMaarten** [comment]
I'm going to assume it was fine, as you've opened a different issue since.

**Comment by JasonMcRay** [comment]
Oh yes... sorry forgot to write in here... I was just massive derp :) I had a brain freeze, and was trying to look at scanned block like grass :)
