### ISSUE TITLE
[Suggestion] Space drone

### ISSUE THREAD

**Issue by XFactHD** [MineMaarten/PneumaticCraft#806]
It seems a bit unrealistic that a drone with propellers can fly in a vacuum. Therefore I suggest a space drone that is accelerated by pressurized air thrusters. This drone should also not take suffocation damage (the GC API offers an interface for that).

**Comment by PrincessRTFM** [comment]
But does Galacticraft provide a way to determine what dimensions are supposed to be a vacuum? And what about pressurized areas within those dimensions? Assuming it's actually possible to implement the features necessary to make it realistic, it may still be more trouble than it's worth.

**Comment by XFactHD** [comment]
I think you can also determine whether you are in a vacuum or not. You can definitely check if the dimension provider is an instance of the Galacticraft world provider.

**Comment by PrincessRTFM** [comment]
What should happen to the drone if it's in a vacuum? Either by placing it in one, or by opening an airlock to a vacuum? On planets, it can fall to the ground, but what about space stations, which don't have proper gravity? I'm not saying I dislike the idea (it's kinda cool), I'm just curious.

**Comment by XFactHD** [comment]
The sense of this drone is that it is being used in the vacuum if space. On planets with a gas atmosphere, the drone can be accelerated by propellers that move air around. In the vacuum you need something like a thruster to accelerate because they work with recoil (Newton's laws).

**Comment by Nonsanity** [comment]
A jetted done would still work in a pressurized environment. It would be designed for micro-gravity environments—which is petty much just two of the Galacticraft dimensions: space station orbit and the asteroid belt.

In those dimensions, propeller-driven drones wouldn't work due to no atmosphere, and in pressurized areas they just aren't programmed to handle the micro-gravity. They'll use far too much thrust. :)

**Comment by XFactHD** [comment]
On moon and mars you also couldn't use propeller-driven drones because there is no atmosphere. Propellers need something to push against (air), thrusters don't need that. Also, to be able to fly the way they are doing right now, they have a gyroscope. With that, they could adjust the thrust power.

**Comment by MineMaarten** [comment]
As this seems like a very limited interaction with a mod while being a lot of work still, and no gameplay difference, just a visual difference, this is not going to happen.

**Comment by XFactHD** [comment]
Would it nonetheless be possible to have the drone implement the interface that makes it be able to breathe in space because it is quite annoying when your drones suffocate in space although they aren't a living entity.
