### ISSUE TITLE
Pressure chamber do not compress iron (1.8.9)

### ISSUE THREAD

**Issue by AngelCry** [MineMaarten/PneumaticCraft#813]
PC 1.13.5-6 (MC 1.8.9, Forge 1724), cant get chamber to work. is already known issue? if i put iron ingots in chamber by hand, then they just disappear once pressure up to needed level. well, i add 2 interfaces, hopper and chest in hope is work this way. this time i at least do not lost ingots, but still dont get compressed iron. hopper put ingots into chamer and after a bit time they come in chest unchanged. i understand, PC for 1.8.9 now just alpha, just want to be sure if you know about all issues. i checked opened issues, but not see anything similar. sorry if i overlook some.
Add: ok, i found what causes this - not enough pressure. after i up pressure to about 2+ bar, chamber with interfaces maked compressed iron. before i guess is been enough pressure because indicator meet green zone and iron ingots disappear - i got feel they going to be processed. anyway, automated version of chamber seems to work fine, but i still wonder what happen with manual version? if pressure are low, i guess ingots will stay untouched. also, will be good to have some tips about needed pressure  just in chamber GUI. may be some marks on gauge or something.

**Comment by tahg** [comment]
They probably disappeared because that's what items do after 5 minutes.  You need an Item Life Upgrade in the chamber to avoid this.  Also, it should show in the red ! tab if you have any issues, including not enough pressure.  The interfaces only take a little bit of pressure.  When you added those they just pulled the ingots in and out before they had a chance to change.  You need to disable the output interface until the items are done.

**Comment by AngelCry** [comment]
oh, well, i feel so stupid now. you right, issue with manual chamber loading just because getting needed pressure with 1 compressor takes longer than item despawn. usually once you put something in some machine you dont need to care about despawn, is why i even dont think is can happen. may be default despawn time inside chamber can be increased? because right now manual loading looks useless. also is a bit hard to guess if you need some upgarde when you going to make your first ingots in chamber :D
i closing issue btw i still think ppl who just start using PC need a bit more care - manual loading looks as good start before some automation, till you understand you cant get it working w/o some upgrades or adding more compressors.

**Comment by MineMaarten** [comment]
Item Life Upgrade, it says it in the upgrade tab.
