### ISSUE TITLE
Amadron crashes when opening its GUI on a dedi server

### ISSUE THREAD

**Issue by tahg** [MineMaarten/PneumaticCraft#815]
Crashlog: http://pastebin.com/sqUMK1BY

**Comment by tahg** [comment]
Seems to be fixed with commit 3c4ed1d.  See also issue #805 May require further testing.

**Comment by MineMaarten** [comment]
This should've fixed it actually: https://github.com/MineMaarten/PneumaticCraft/commit/4fad19e43091533d14fb80a36e3a56b785382e86
