### ISSUE TITLE
Crash on pressing O outside chat.

### ISSUE THREAD

**Issue by Zethalion** [MineMaarten/PneumaticCraft#823]
After updating to PneumaticCraft-1.7.10-1.12.6-149-universal, not enough keys faultily handles the keypress for PneumaticCraft while O isn't bind to PneumaticCraft.
http://pastebin.com/VzCGaDq5

Previous version used was PneumaticCraft-1.7.10-1.11.6-126-universal
Not Enough keys: NotEnoughKeys-1.7.10-1.0.0b29

**Comment by XFactHD** [comment]
I once had this crash with Tinker's Construct. You need to update NotEnoughKeys.

**Comment by Zethalion** [comment]
Tried the NOK update. Now I get constantly Tinkers amor GUI. 

I'll close this one because NOK isn't working properly.
