### ISSUE TITLE
Thermopneumatic Processing Plant/Lubricant

### ISSUE THREAD

**Issue by Minerva-BOS** [MineMaarten/PneumaticCraft#826]
It appears that as soon as the machine gets hot enough to produce lubricant, the machine ignores the redstone dust input and switches the recipe to Kerosene.

**Comment by MineMaarten** [comment]
Don't power it with pressure in that case. Lubricant doesn't need it.

**Comment by thiakil** [comment]
I Get this even with 0 pressure in it; it just complains that there's not enough pressure in the Problems panel. Full stack of redstone in the slot always. Version 1.7.10-1.12.4-147 if it matters (will update soon as is part of mod pack my partner and I use)
