### ISSUE TITLE
Compressing Iron Ingots

### ISSUE THREAD

**Issue by JasonMcRay** [MineMaarten/PneumaticCraft#827]
Would it be possible to add support for couple of other "exploding" items to make compressed ingots? I am asking this since GregTech has moved TNT creation to be pain. And other explosion mechanics doesnt work.

Tested IC2 Dynamite - Obliterates the Iron Ingots
GT Powderbarrel - Obliterates the Iron Ingots
industrial TNT - Obliterates the Iron Ingots
Tiny TNT (AE2) - Obliterates the Iron Ingots

Probably everything that can explode is not going to work.

Also on similiar note... how to get Compressed Iron Ingots on servers where TNT explosions are banned?

**Comment by bookerthegeek** [comment]
Tiny tnt

**Comment by XFactHD** [comment]
If tnt is banned, tiny tnt is most likely also banned.

**Comment by bookerthegeek** [comment]
Odd, due to tiny tnt having no block damage. If it is I would suggest asking the server administration to unban it

**Comment by XFactHD** [comment]
It does a little bit of block damage.

**Comment by JasonMcRay** [comment]
Well as i mentioned also Tiny TNT is not able to produce Compressed Ingots.

**Comment by XFactHD** [comment]
I know, I just wanted to mention this.

**Comment by Forecaster** [comment]
I would say that it's the server owners responsibility to provide an alternative way of getting compressed iron. Like buying it or something.

**Comment by MineMaarten** [comment]
Any regularly created explosion should work. It triggers an explosion event added by Forge. Please bug the authors of the mods of the explosion mechanics to trigger this event. I've already done so a long time ago for AE's tiny TNT, apparently they haven't implemented it still.

Meanwhile, Creeper explosions work fine
