### ISSUE TITLE
Stops the drones

### ISSUE THREAD

**Issue by MrFungor** [MineMaarten/PneumaticCraft#828]
Drones do not work when there is no Steve. Chunks loaded correctly. So thinking about? Tree Farm on the drones do not work when I'm not around. This is bad. Very bad =(
P.S. sorry for my bad English

**Comment by MineMaarten** [comment]
Version?

**Comment by MrFungor** [comment]
PneumaticCraft - 1.12.6-149

**Comment by MrFungor** [comment]
Oh ... This is only a problem on the server. KCauldron, one of the latest builds, 1.7.10. 
Forge 10.13.4.1614.
Maybe somehow to fix it? Just I don't know

**Comment by MineMaarten** [comment]
I expect something with permissions. Cauldron is outside my scope though, sorry
