### ISSUE TITLE
Unable to compress villagers into mechanics

### ISSUE THREAD

**Issue by grouNDfx** [MineMaarten/PneumaticCraft#829]
PneumaticCraft Version: 1.13.8-12
No other mods present

I can't seem to get a villager to compress into a mechanic. I have broken the compressor right before it dies but it still offers the same trades and doesn't change in appearance.

**Comment by Fayti1703** [comment]
Can confirm. Villager dies uncompressed in chamber.

**Comment by KJP12** [comment]
Possibly due to the fact that adding a villager into 1.8 is extremely hard without making your own entity, meaning he can't just wipe all of the villager trade data and change a flag.

**Comment by MineMaarten** [comment]
Yes, I can confirm PneumaticCraft villagers aren't in the 1.8 version of PneumaticCraft. And as their use has been replaced by Amadron, and I never implemented the real way of how I wanted to spawn the villagers, I doubt they'll ever make an appearance again. So use Amadron ;)
