### ISSUE TITLE
Pneumatic Elevator snapping

### ISSUE THREAD

**Issue by Fayti1703** [MineMaarten/PneumaticCraft#831]
If a player is above an elevator while it is moving, he/she snaps on top of the elevator in one of two ways:

- If the elevator is moving downwards, the player snaps onto the elevator client- and server-side.
- If the elevator is moving upwards, the player snaps onto the elevator only client-side for a frame or so, then snaps up to the top server- and client-side.

This may be due to the player-wiggle-prevention thing.

**Comment by MineMaarten** [comment]
Known behaviour. I've been struggling a long time to get Elevators to work reliably, and this method, while it has this side effect, is far the best way I've come up with. So we gotta deal with it, even though imo it's not a big deal.
