### ISSUE TITLE
Drones Stopping Their Program?

### ISSUE THREAD

**Issue by zzApotheosis** [MineMaarten/PneumaticCraft#848]
Minecraft 1.7.10
MCP v9.05
FML v7.10.99.99
Minecraft Forge 10.13.4.1614
FastCraft 1.23
PneumaticCraft-1.7.10-1.12.7-150-universal

I've made a simple program for a drone so that it picks up items from a certain location (My farm), and exports the items to an inventory (which then loads onto my cargo rocket, and launches to the moon :P), but it seems as though when the drone gets to a certain distance away from me, it will just stop moving. The chunks are properly loaded with ChickenChunks. And the drone will resume when I get closer to it... Not sure what's happening here, but I really want to use the drones to transport items from the farm to the rocket, because 1) the drones are awesome, and 2) it fits the theme of the rocket launching. I'd rather have drones move my items than itemducts, conveyor belts, or item conduits.

You can see my struggles here:
https://drive.google.com/file/d/0B_wljXPJi507c2lhUjduaUxITFE/view?usp=sharing
(I forgot to turn off the music. Sorry if you don't like it xD)

Maybe it's too far away? I'm not sure, but no matter what, the drone will stop running when it gets too far from me. It also happens at the other end too. If I'm standing at the rocket, it will stop functioning when it gets back to the farm.

Edit 1: Quick update. I'd like to report that this drone in the video functions normally when I'm not in the dimension... So if I was at my home on the moon, the drone would gather farm resources and load it to the cargo rocket as usual, no problems. For some reason, when I'm around the farm or rocket (My "Earth Factory"), it does not work properly as shown in the video. Also, forgot to mention: Thanks for this outstanding mod!

**Comment by Tekstack** [comment]
It defiantly looks like a chunkloading issue. What mod are you using for your chunkloading? Also, when you are teleporting quickly from chunk to chunk, I have a feeling the "ticket" requests to forceload chunks are not being properly handled (as if you were still in the chunk, so the mod isn't requesting a ticket from forge). When you go to a new dim. the mod recognizes you are no longer there and works properly. I'm not an expert on Forge's chunkloading by any means, but i would suggest trying a different chunkloader (ie. dimensional anchor/world anchor/etc. if you are using Chicken Chunks or vise versa).

**Comment by zzApotheosis** [comment]
Yeah, I might try that. I'm also using OptiFine so I'm not entirely sure if the "optimized" chunkloading is affecting it in any way. I'll tinker around with OF settings and try different chunkloaders and see if that helps. Currently, I'm using ChickenChunks, and it's worth noting that in the video, the chunk loader's boundaries are right on the edge of the drone's path, so maybe PneumaticCraft is checking to see if the drone may be heading into an unloaded chunk, and if so it halts the drone's movement?

**Comment by mindforger** [comment]
`Currently, I'm using ChickenChunks` those Chunkloaders are bonked since 1.7
they do not always load dimensions as they should, the cause random unload and reload events causing TPS spikes and ot top that all, they leave the entities sometimes in half baked stages, so when a reload happens the machines are all borked and need a reset (especially the AE2 guys know this issue with chicken chunks)
