### ISSUE TITLE
Add config option for gas lift pressure requirements?

### ISSUE THREAD

**Issue by fluffle** [MineMaarten/PneumaticCraft#849]
Hi,

I'm playing TechNodefirmacraft, a 1.7.10 modpack by @Bunsan which is based around the Terrafirmacraft (TFC) mod. This pack also contains Pneumaticcraft and I'm starting to get into oil drilling and plastic production.

TFC's default sea height is y=144 instead of y=64, which means that the gas lift cannot be given enough pressure to reach oil wells deep underground with the current pressure requirements. These are static and defined here:

https://github.com/MineMaarten/PneumaticCraft/blob/master/src/pneumaticCraft/common/tileentity/TileEntityGasLift.java#L213

I can drill 90 blocks downwards with a pressure requirement of 0.05 bar per metre of depth (4.5/0.05). Much of the oil I'm after requires me to drill over 100 blocks down. I can work around this by drilling part of the way down then re-siting my gas lift, but I think it could be helpful to make the pressure-per-metre a configuration option.

Cheers,
--fluffle

**Comment by Bunsan** [comment]
This can be closed. We've added an addon to the pack that adds an advanced gas lift that can drill down from the surface of a TFC world.

**Comment by fluffle** [comment]
Oh, my bad, I completely missed that in NEI.
