### ISSUE TITLE
ComputerCraft Better Support

### ISSUE THREAD

**Issue by dannysmc95** [MineMaarten/PneumaticCraft#854]
Hello,

So I was actually wondering is there anyways to control the output with ComputerCraft. So we are working on a city where players can get pressure from tubes running through the city, my question is:

"Is there a way of controlling the flow of power out of a compressor? Like say I am pumping 10bars through a tube, can I control that and add ways of releasing the pressure or capping someone to 5bars?"

Thanks.

**Comment by Forecaster** [comment]
Regulator tube module and redstone signal or advanced pcb.
