### ISSUE TITLE
Some retextures.

### ISSUE THREAD

**Issue by IceLagTun** [MineMaarten/PneumaticCraft#903]
Some time ago I made retextures for myself and since I don't play 1.7.10 anymore I can't find what to do with them. They look cool IMO and fire looks much better than an original, so I decided to put them here. Hope someone or even dev will find them useful. 

![aircompressoractive](https://cloud.githubusercontent.com/assets/2061234/26095577/c81d592c-3a26-11e7-9c43-e22b4ccee0f6.png)
![advancedaircompressor](https://cloud.githubusercontent.com/assets/2061234/26095576/c81c7e12-3a26-11e7-9012-6952cea8df1c.png)
![advancedaircompressoractive](https://cloud.githubusercontent.com/assets/2061234/26095578/c81e6254-3a26-11e7-8a3a-70eaccc60f3b.png)
![aircompressor](https://cloud.githubusercontent.com/assets/2061234/26095579/c82a9ec0-3a26-11e7-8c24-9bcb033b7b88.png)

**Comment by ArukaAlter** [comment]
The last update on the mod was last year, I'd suggest putting up a resource pack on CurseForge instead.
