### ISSUE TITLE
Crash on 1.12.2

### ISSUE THREAD

**Issue by matyklugDebbuged** [MineMaarten/PneumaticCraft#908]
Caught exception from pneumaticcraft (java.lang.VerifyError: Operand stack underflow
Exception Details:
  Location:
    net/minecraft/server/management/PlayerInteractionManager.getBlockReachDistance()D @11: dmul
  Reason:
    Attempt to pop empty stack.
  Current Frame:
    bci: @11
    flags: { }
    locals: { 'net/minecraft/server/management/PlayerInteractionManager' }
    stack: { 'net/minecraft/entity/player/EntityPlayerMP', double, double_2nd }
  Bytecode:
    0x0000000: 2ab4 0048 2ab4 0048 b802 2e6b b200 c1b6
    0x0000010: 00c5 b900 cb01 00af                    
)
[crash-2017-12-25_21.41.56-client.txt](https://github.com/MineMaarten/PneumaticCraft/files/1586140/crash-2017-12-25_21.41.56-client.txt)

**Comment by MaartenKok8** [comment]
Thanks for the report, this is the old PneumaticCraft repo though, I've created an issue there for your problem: https://github.com/TeamPneumatic/pnc-repressurized/issues/88

Further discussion will continue there. 

I've also added a 'template body' in this repo which should hint future users to post issues at the new repo :)
